// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "sc_FIFO_DCT.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sc_FIFO_DCT::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<1> sc_FIFO_DCT::ap_const_lv1_0 = "0";
const sc_lv<32> sc_FIFO_DCT::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> sc_FIFO_DCT::ap_const_lv1_1 = "1";
const sc_lv<32> sc_FIFO_DCT::ap_const_lv32_1 = "1";
const sc_lv<2> sc_FIFO_DCT::ap_const_lv2_0 = "00";
const sc_logic sc_FIFO_DCT::ap_const_logic_0 = sc_dt::Log_0;

sc_FIFO_DCT::sc_FIFO_DCT(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sc_FIFO_DCT_mA_U = new sc_FIFO_DCT_DCT_a("sc_FIFO_DCT_mA_U");
    sc_FIFO_DCT_mA_U->clk(clock);
    sc_FIFO_DCT_mA_U->reset(reset);
    sc_FIFO_DCT_mA_U->address0(sc_FIFO_DCT_mA_address0);
    sc_FIFO_DCT_mA_U->ce0(sc_FIFO_DCT_mA_ce0);
    sc_FIFO_DCT_mA_U->we0(grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_we0);
    sc_FIFO_DCT_mA_U->d0(grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_d0);
    sc_FIFO_DCT_mA_U->q0(sc_FIFO_DCT_mA_q0);
    sc_FIFO_DCT_mB_U = new sc_FIFO_DCT_sc_FIeOg("sc_FIFO_DCT_mB_U");
    sc_FIFO_DCT_mB_U->clk(clock);
    sc_FIFO_DCT_mB_U->reset(reset);
    sc_FIFO_DCT_mB_U->address0(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mB_address0);
    sc_FIFO_DCT_mB_U->ce0(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mB_ce0);
    sc_FIFO_DCT_mB_U->we0(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mB_we0);
    sc_FIFO_DCT_mB_U->d0(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mB_d0);
    sc_FIFO_DCT_mC_U = new sc_FIFO_DCT_DCT_a("sc_FIFO_DCT_mC_U");
    sc_FIFO_DCT_mC_U->clk(clock);
    sc_FIFO_DCT_mC_U->reset(reset);
    sc_FIFO_DCT_mC_U->address0(sc_FIFO_DCT_mC_address0);
    sc_FIFO_DCT_mC_U->ce0(sc_FIFO_DCT_mC_ce0);
    sc_FIFO_DCT_mC_U->we0(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_we0);
    sc_FIFO_DCT_mC_U->d0(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_d0);
    sc_FIFO_DCT_mC_U->q0(sc_FIFO_DCT_mC_q0);
    grp_sc_FIFO_DCT_data_out_fu_160 = new sc_FIFO_DCT_data_out("grp_sc_FIFO_DCT_data_out_fu_160");
    grp_sc_FIFO_DCT_data_out_fu_160->ap_clk(clock);
    grp_sc_FIFO_DCT_data_out_fu_160->ap_rst(reset);
    grp_sc_FIFO_DCT_data_out_fu_160->dout_din(grp_sc_FIFO_DCT_data_out_fu_160_dout_din);
    grp_sc_FIFO_DCT_data_out_fu_160->dout_full_n(dout_full_n);
    grp_sc_FIFO_DCT_data_out_fu_160->dout_write(grp_sc_FIFO_DCT_data_out_fu_160_dout_write);
    grp_sc_FIFO_DCT_data_out_fu_160->sc_FIFO_DCT_mC_address0(grp_sc_FIFO_DCT_data_out_fu_160_sc_FIFO_DCT_mC_address0);
    grp_sc_FIFO_DCT_data_out_fu_160->sc_FIFO_DCT_mC_ce0(grp_sc_FIFO_DCT_data_out_fu_160_sc_FIFO_DCT_mC_ce0);
    grp_sc_FIFO_DCT_data_out_fu_160->sc_FIFO_DCT_mC_q0(sc_FIFO_DCT_mC_q0);
    grp_sc_FIFO_DCT_data_out_fu_160->s_DCT(grp_sc_FIFO_DCT_data_out_fu_160_s_DCT);
    grp_sc_FIFO_DCT_data_out_fu_160->s_done(grp_sc_FIFO_DCT_data_out_fu_160_s_done);
    grp_sc_FIFO_DCT_data_out_fu_160->s_done_ap_vld(grp_sc_FIFO_DCT_data_out_fu_160_s_done_ap_vld);
    grp_sc_FIFO_DCT_DCT_fu_192 = new sc_FIFO_DCT_DCT("grp_sc_FIFO_DCT_DCT_fu_192");
    grp_sc_FIFO_DCT_DCT_fu_192->ap_clk(clock);
    grp_sc_FIFO_DCT_DCT_fu_192->ap_rst(reset);
    grp_sc_FIFO_DCT_DCT_fu_192->sc_FIFO_DCT_mA_address0(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mA_address0);
    grp_sc_FIFO_DCT_DCT_fu_192->sc_FIFO_DCT_mA_ce0(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mA_ce0);
    grp_sc_FIFO_DCT_DCT_fu_192->sc_FIFO_DCT_mA_q0(sc_FIFO_DCT_mA_q0);
    grp_sc_FIFO_DCT_DCT_fu_192->sc_FIFO_DCT_mB_address0(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mB_address0);
    grp_sc_FIFO_DCT_DCT_fu_192->sc_FIFO_DCT_mB_ce0(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mB_ce0);
    grp_sc_FIFO_DCT_DCT_fu_192->sc_FIFO_DCT_mB_we0(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mB_we0);
    grp_sc_FIFO_DCT_DCT_fu_192->sc_FIFO_DCT_mB_d0(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mB_d0);
    grp_sc_FIFO_DCT_DCT_fu_192->sc_FIFO_DCT_mC_address0(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_address0);
    grp_sc_FIFO_DCT_DCT_fu_192->sc_FIFO_DCT_mC_ce0(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_ce0);
    grp_sc_FIFO_DCT_DCT_fu_192->sc_FIFO_DCT_mC_we0(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_we0);
    grp_sc_FIFO_DCT_DCT_fu_192->sc_FIFO_DCT_mC_d0(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_d0);
    grp_sc_FIFO_DCT_DCT_fu_192->sc_FIFO_DCT_exec_cnt_i(sc_FIFO_DCT_exec_cnt);
    grp_sc_FIFO_DCT_DCT_fu_192->sc_FIFO_DCT_exec_cnt_o(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_exec_cnt_o);
    grp_sc_FIFO_DCT_DCT_fu_192->sc_FIFO_DCT_exec_cnt_o_ap_vld(grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_exec_cnt_o_ap_vld);
    grp_sc_FIFO_DCT_DCT_fu_192->s_buffered(grp_sc_FIFO_DCT_DCT_fu_192_s_buffered);
    grp_sc_FIFO_DCT_DCT_fu_192->s_working(grp_sc_FIFO_DCT_DCT_fu_192_s_working);
    grp_sc_FIFO_DCT_DCT_fu_192->s_working_ap_vld(grp_sc_FIFO_DCT_DCT_fu_192_s_working_ap_vld);
    grp_sc_FIFO_DCT_DCT_fu_192->s_DCT(grp_sc_FIFO_DCT_DCT_fu_192_s_DCT);
    grp_sc_FIFO_DCT_DCT_fu_192->s_DCT_ap_vld(grp_sc_FIFO_DCT_DCT_fu_192_s_DCT_ap_vld);
    grp_sc_FIFO_DCT_DCT_fu_192->s_done(grp_sc_FIFO_DCT_DCT_fu_192_s_done);
    grp_sc_FIFO_DCT_buffering_fu_228 = new sc_FIFO_DCT_buffering("grp_sc_FIFO_DCT_buffering_fu_228");
    grp_sc_FIFO_DCT_buffering_fu_228->ap_clk(clock);
    grp_sc_FIFO_DCT_buffering_fu_228->ap_rst(reset);
    grp_sc_FIFO_DCT_buffering_fu_228->din_dout(din_dout);
    grp_sc_FIFO_DCT_buffering_fu_228->din_empty_n(din_empty_n);
    grp_sc_FIFO_DCT_buffering_fu_228->din_read(grp_sc_FIFO_DCT_buffering_fu_228_din_read);
    grp_sc_FIFO_DCT_buffering_fu_228->sc_FIFO_DCT_mA_address0(grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_address0);
    grp_sc_FIFO_DCT_buffering_fu_228->sc_FIFO_DCT_mA_ce0(grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_ce0);
    grp_sc_FIFO_DCT_buffering_fu_228->sc_FIFO_DCT_mA_we0(grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_we0);
    grp_sc_FIFO_DCT_buffering_fu_228->sc_FIFO_DCT_mA_d0(grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_d0);
    grp_sc_FIFO_DCT_buffering_fu_228->s_buffered(grp_sc_FIFO_DCT_buffering_fu_228_s_buffered);
    grp_sc_FIFO_DCT_buffering_fu_228->s_buffered_ap_vld(grp_sc_FIFO_DCT_buffering_fu_228_s_buffered_ap_vld);
    grp_sc_FIFO_DCT_buffering_fu_228->s_working(grp_sc_FIFO_DCT_buffering_fu_228_s_working);

    SC_METHOD(thread_s_DCT);
    dont_initialize();
    sensitive << ( clock.pos() );

    SC_METHOD(thread_s_buffered);
    dont_initialize();
    sensitive << ( clock.pos() );

    SC_METHOD(thread_s_done);
    dont_initialize();
    sensitive << ( clock.pos() );

    SC_METHOD(thread_s_working);
    dont_initialize();
    sensitive << ( clock.pos() );

    SC_METHOD(thread_sc_FIFO_DCT_exec_cnt);
    dont_initialize();
    sensitive << ( clock.pos() );

    SC_METHOD(thread_ap_CS_fsm);

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_din_read);
    sensitive << ( grp_sc_FIFO_DCT_buffering_fu_228_din_read );

    SC_METHOD(thread_dout_din);
    sensitive << ( grp_sc_FIFO_DCT_data_out_fu_160_dout_din );
    sensitive << ( grp_sc_FIFO_DCT_data_out_fu_160_dout_write );

    SC_METHOD(thread_dout_write);
    sensitive << ( grp_sc_FIFO_DCT_data_out_fu_160_dout_write );

    SC_METHOD(thread_grp_sc_FIFO_DCT_DCT_fu_192_s_buffered);
    sensitive << ( sc_FIFO_DCT_ssdm_s_load_fu_260_p1 );
    sensitive << ( sc_FIFO_DCT_ssdm_1_load_fu_264_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( s_buffered );

    SC_METHOD(thread_grp_sc_FIFO_DCT_DCT_fu_192_s_done);
    sensitive << ( sc_FIFO_DCT_ssdm_s_load_fu_260_p1 );
    sensitive << ( sc_FIFO_DCT_ssdm_1_load_fu_264_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( s_done );

    SC_METHOD(thread_grp_sc_FIFO_DCT_buffering_fu_228_s_working);
    sensitive << ( sc_FIFO_DCT_ssdm_s_load_fu_260_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( s_working );

    SC_METHOD(thread_grp_sc_FIFO_DCT_data_out_fu_160_s_DCT);
    sensitive << ( sc_FIFO_DCT_ssdm_s_load_fu_260_p1 );
    sensitive << ( sc_FIFO_DCT_ssdm_1_load_fu_264_p1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( s_DCT );

    SC_METHOD(thread_sc_FIFO_DCT_mA_address0);
    sensitive << ( grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mA_address0 );
    sensitive << ( grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mA_ce0 );
    sensitive << ( grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_address0 );
    sensitive << ( grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_ce0 );

    SC_METHOD(thread_sc_FIFO_DCT_mA_ce0);
    sensitive << ( grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mA_ce0 );
    sensitive << ( grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_ce0 );

    SC_METHOD(thread_sc_FIFO_DCT_mC_address0);
    sensitive << ( grp_sc_FIFO_DCT_data_out_fu_160_sc_FIFO_DCT_mC_address0 );
    sensitive << ( grp_sc_FIFO_DCT_data_out_fu_160_sc_FIFO_DCT_mC_ce0 );
    sensitive << ( grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_address0 );
    sensitive << ( grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_ce0 );

    SC_METHOD(thread_sc_FIFO_DCT_mC_ce0);
    sensitive << ( grp_sc_FIFO_DCT_data_out_fu_160_sc_FIFO_DCT_mC_ce0 );
    sensitive << ( grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_ce0 );

    SC_METHOD(thread_sc_FIFO_DCT_ssdm_1_load_fu_264_p1);

    SC_METHOD(thread_sc_FIFO_DCT_ssdm_2_load_fu_268_p1);

    SC_METHOD(thread_sc_FIFO_DCT_ssdm_s_load_fu_260_p1);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( clock.pos() );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sc_FIFO_DCT_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, clock, "(port)clock");
    sc_trace(mVcdFile, reset, "(port)reset");
    sc_trace(mVcdFile, enable, "(port)enable");
    sc_trace(mVcdFile, dout_din, "(port)dout_din");
    sc_trace(mVcdFile, dout_full_n, "(port)dout_full_n");
    sc_trace(mVcdFile, dout_write, "(port)dout_write");
    sc_trace(mVcdFile, din_dout, "(port)din_dout");
    sc_trace(mVcdFile, din_empty_n, "(port)din_empty_n");
    sc_trace(mVcdFile, din_read, "(port)din_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, sc_FIFO_DCT_mA_address0, "sc_FIFO_DCT_mA_address0");
    sc_trace(mVcdFile, sc_FIFO_DCT_mA_ce0, "sc_FIFO_DCT_mA_ce0");
    sc_trace(mVcdFile, sc_FIFO_DCT_mA_q0, "sc_FIFO_DCT_mA_q0");
    sc_trace(mVcdFile, sc_FIFO_DCT_mC_address0, "sc_FIFO_DCT_mC_address0");
    sc_trace(mVcdFile, sc_FIFO_DCT_mC_ce0, "sc_FIFO_DCT_mC_ce0");
    sc_trace(mVcdFile, sc_FIFO_DCT_mC_q0, "sc_FIFO_DCT_mC_q0");
    sc_trace(mVcdFile, sc_FIFO_DCT_ssdm_s_load_fu_260_p1, "sc_FIFO_DCT_ssdm_s_load_fu_260_p1");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, sc_FIFO_DCT_ssdm_1_load_fu_264_p1, "sc_FIFO_DCT_ssdm_1_load_fu_264_p1");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_data_out_fu_160_dout_din, "grp_sc_FIFO_DCT_data_out_fu_160_dout_din");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_data_out_fu_160_dout_write, "grp_sc_FIFO_DCT_data_out_fu_160_dout_write");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_data_out_fu_160_sc_FIFO_DCT_mC_address0, "grp_sc_FIFO_DCT_data_out_fu_160_sc_FIFO_DCT_mC_address0");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_data_out_fu_160_sc_FIFO_DCT_mC_ce0, "grp_sc_FIFO_DCT_data_out_fu_160_sc_FIFO_DCT_mC_ce0");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_data_out_fu_160_s_DCT, "grp_sc_FIFO_DCT_data_out_fu_160_s_DCT");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_data_out_fu_160_s_done, "grp_sc_FIFO_DCT_data_out_fu_160_s_done");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_data_out_fu_160_s_done_ap_vld, "grp_sc_FIFO_DCT_data_out_fu_160_s_done_ap_vld");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mA_address0, "grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mA_address0");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mA_ce0, "grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mA_ce0");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mB_address0, "grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mB_address0");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mB_ce0, "grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mB_ce0");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mB_we0, "grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mB_we0");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mB_d0, "grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mB_d0");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_address0, "grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_address0");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_ce0, "grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_ce0");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_we0, "grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_we0");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_d0, "grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_d0");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_exec_cnt_o, "grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_exec_cnt_o");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_exec_cnt_o_ap_vld, "grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_exec_cnt_o_ap_vld");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_s_buffered, "grp_sc_FIFO_DCT_DCT_fu_192_s_buffered");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_s_working, "grp_sc_FIFO_DCT_DCT_fu_192_s_working");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_s_working_ap_vld, "grp_sc_FIFO_DCT_DCT_fu_192_s_working_ap_vld");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_s_DCT, "grp_sc_FIFO_DCT_DCT_fu_192_s_DCT");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_s_DCT_ap_vld, "grp_sc_FIFO_DCT_DCT_fu_192_s_DCT_ap_vld");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_DCT_fu_192_s_done, "grp_sc_FIFO_DCT_DCT_fu_192_s_done");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_buffering_fu_228_din_read, "grp_sc_FIFO_DCT_buffering_fu_228_din_read");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_address0, "grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_address0");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_ce0, "grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_ce0");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_we0, "grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_we0");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_d0, "grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_d0");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_buffering_fu_228_s_buffered, "grp_sc_FIFO_DCT_buffering_fu_228_s_buffered");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_buffering_fu_228_s_buffered_ap_vld, "grp_sc_FIFO_DCT_buffering_fu_228_s_buffered_ap_vld");
    sc_trace(mVcdFile, grp_sc_FIFO_DCT_buffering_fu_228_s_working, "grp_sc_FIFO_DCT_buffering_fu_228_s_working");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, sc_FIFO_DCT_exec_cnt, "sc_FIFO_DCT_exec_cnt");
    sc_trace(mVcdFile, s_buffered, "s_buffered");
    sc_trace(mVcdFile, s_working, "s_working");
    sc_trace(mVcdFile, s_DCT, "s_DCT");
    sc_trace(mVcdFile, s_done, "s_done");
    sc_trace(mVcdFile, sc_FIFO_DCT_ssdm_2_load_fu_268_p1, "sc_FIFO_DCT_ssdm_2_load_fu_268_p1");
#endif

    }
    mHdltvinHandle.open("sc_FIFO_DCT.hdltvin.dat");
    mHdltvoutHandle.open("sc_FIFO_DCT.hdltvout.dat");
}

sc_FIFO_DCT::~sc_FIFO_DCT() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete sc_FIFO_DCT_mA_U;
    delete sc_FIFO_DCT_mB_U;
    delete sc_FIFO_DCT_mC_U;
    delete grp_sc_FIFO_DCT_data_out_fu_160;
    delete grp_sc_FIFO_DCT_DCT_fu_192;
    delete grp_sc_FIFO_DCT_buffering_fu_228;
}

void sc_FIFO_DCT::thread_s_DCT() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, sc_FIFO_DCT_ssdm_s_load_fu_260_p1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, sc_FIFO_DCT_ssdm_1_load_fu_264_p1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, sc_FIFO_DCT_ssdm_2_load_fu_268_p1.read()))) {
        s_DCT = ap_const_lv1_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sc_FIFO_DCT_DCT_fu_192_s_DCT_ap_vld.read())) {
        s_DCT =  (sc_lv<1>) (grp_sc_FIFO_DCT_DCT_fu_192_s_DCT.read());
    }
}

void sc_FIFO_DCT::thread_s_buffered() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, sc_FIFO_DCT_ssdm_s_load_fu_260_p1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, sc_FIFO_DCT_ssdm_1_load_fu_264_p1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, sc_FIFO_DCT_ssdm_2_load_fu_268_p1.read()))) {
        s_buffered = ap_const_lv1_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sc_FIFO_DCT_buffering_fu_228_s_buffered_ap_vld.read())) {
        s_buffered =  (sc_lv<1>) (grp_sc_FIFO_DCT_buffering_fu_228_s_buffered.read());
    }
}

void sc_FIFO_DCT::thread_s_done() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, sc_FIFO_DCT_ssdm_s_load_fu_260_p1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, sc_FIFO_DCT_ssdm_1_load_fu_264_p1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, sc_FIFO_DCT_ssdm_2_load_fu_268_p1.read()))) {
        s_done = ap_const_lv1_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sc_FIFO_DCT_data_out_fu_160_s_done_ap_vld.read())) {
        s_done =  (sc_lv<1>) (grp_sc_FIFO_DCT_data_out_fu_160_s_done.read());
    }
}

void sc_FIFO_DCT::thread_s_working() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, sc_FIFO_DCT_ssdm_s_load_fu_260_p1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, sc_FIFO_DCT_ssdm_1_load_fu_264_p1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, sc_FIFO_DCT_ssdm_2_load_fu_268_p1.read()))) {
        s_working = ap_const_lv1_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sc_FIFO_DCT_DCT_fu_192_s_working_ap_vld.read())) {
        s_working =  (sc_lv<1>) (grp_sc_FIFO_DCT_DCT_fu_192_s_working.read());
    }
}

void sc_FIFO_DCT::thread_sc_FIFO_DCT_exec_cnt() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, sc_FIFO_DCT_ssdm_s_load_fu_260_p1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, sc_FIFO_DCT_ssdm_1_load_fu_264_p1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, sc_FIFO_DCT_ssdm_2_load_fu_268_p1.read()))) {
        sc_FIFO_DCT_exec_cnt = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_exec_cnt_o_ap_vld.read())) {
        sc_FIFO_DCT_exec_cnt = grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_exec_cnt_o.read();
    }
}

void sc_FIFO_DCT::thread_ap_CS_fsm() {
    ap_CS_fsm = ap_const_lv2_0;
}

void sc_FIFO_DCT::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read().range(0, 0);
}

void sc_FIFO_DCT::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read().range(1, 1);
}

void sc_FIFO_DCT::thread_din_read() {
    din_read = grp_sc_FIFO_DCT_buffering_fu_228_din_read.read();
}

void sc_FIFO_DCT::thread_dout_din() {
    dout_din = grp_sc_FIFO_DCT_data_out_fu_160_dout_din.read();
}

void sc_FIFO_DCT::thread_dout_write() {
    dout_write = grp_sc_FIFO_DCT_data_out_fu_160_dout_write.read();
}

void sc_FIFO_DCT::thread_grp_sc_FIFO_DCT_DCT_fu_192_s_buffered() {
    grp_sc_FIFO_DCT_DCT_fu_192_s_buffered =  (sc_logic) (s_buffered.read()[0]);
}

void sc_FIFO_DCT::thread_grp_sc_FIFO_DCT_DCT_fu_192_s_done() {
    grp_sc_FIFO_DCT_DCT_fu_192_s_done =  (sc_logic) (s_done.read()[0]);
}

void sc_FIFO_DCT::thread_grp_sc_FIFO_DCT_buffering_fu_228_s_working() {
    grp_sc_FIFO_DCT_buffering_fu_228_s_working =  (sc_logic) (s_working.read()[0]);
}

void sc_FIFO_DCT::thread_grp_sc_FIFO_DCT_data_out_fu_160_s_DCT() {
    grp_sc_FIFO_DCT_data_out_fu_160_s_DCT =  (sc_logic) (s_DCT.read()[0]);
}

void sc_FIFO_DCT::thread_sc_FIFO_DCT_mA_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_ce0.read())) {
        sc_FIFO_DCT_mA_address0 = grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mA_ce0.read())) {
        sc_FIFO_DCT_mA_address0 = grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mA_address0.read();
    } else {
        sc_FIFO_DCT_mA_address0 = "XXXXXX";
    }
}

void sc_FIFO_DCT::thread_sc_FIFO_DCT_mA_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_ce0.read())) {
        sc_FIFO_DCT_mA_ce0 = grp_sc_FIFO_DCT_buffering_fu_228_sc_FIFO_DCT_mA_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mA_ce0.read())) {
        sc_FIFO_DCT_mA_ce0 = grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mA_ce0.read();
    } else {
        sc_FIFO_DCT_mA_ce0 = sc_logic('X');
    }
}

void sc_FIFO_DCT::thread_sc_FIFO_DCT_mC_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_ce0.read())) {
        sc_FIFO_DCT_mC_address0 = grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sc_FIFO_DCT_data_out_fu_160_sc_FIFO_DCT_mC_ce0.read())) {
        sc_FIFO_DCT_mC_address0 = grp_sc_FIFO_DCT_data_out_fu_160_sc_FIFO_DCT_mC_address0.read();
    } else {
        sc_FIFO_DCT_mC_address0 = "XXXXXX";
    }
}

void sc_FIFO_DCT::thread_sc_FIFO_DCT_mC_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_ce0.read())) {
        sc_FIFO_DCT_mC_ce0 = grp_sc_FIFO_DCT_DCT_fu_192_sc_FIFO_DCT_mC_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sc_FIFO_DCT_data_out_fu_160_sc_FIFO_DCT_mC_ce0.read())) {
        sc_FIFO_DCT_mC_ce0 = grp_sc_FIFO_DCT_data_out_fu_160_sc_FIFO_DCT_mC_ce0.read();
    } else {
        sc_FIFO_DCT_mC_ce0 = sc_logic('X');
    }
}

void sc_FIFO_DCT::thread_sc_FIFO_DCT_ssdm_1_load_fu_264_p1() {
    sc_FIFO_DCT_ssdm_1_load_fu_264_p1 = ap_const_lv1_0;
}

void sc_FIFO_DCT::thread_sc_FIFO_DCT_ssdm_2_load_fu_268_p1() {
    sc_FIFO_DCT_ssdm_2_load_fu_268_p1 = ap_const_lv1_0;
}

void sc_FIFO_DCT::thread_sc_FIFO_DCT_ssdm_s_load_fu_260_p1() {
    sc_FIFO_DCT_ssdm_s_load_fu_260_p1 = ap_const_lv1_0;
}

void sc_FIFO_DCT::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"reset\" :  \"" << reset.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"enable\" :  \"" << enable.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"dout_din\" :  \"" << dout_din.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"dout_full_n\" :  \"" << dout_full_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"dout_write\" :  \"" << dout_write.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"din_dout\" :  \"" << din_dout.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"din_empty_n\" :  \"" << din_empty_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"din_read\" :  \"" << din_read.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

