// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _sc_FIFO_DCT_Prc1_HH_
#define _sc_FIFO_DCT_Prc1_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct sc_FIFO_DCT_Prc1 : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > sync;
    sc_out< sc_logic > error;
    sc_out< sc_logic > error_ap_vld;
    sc_in< sc_lv<8> > din;
    sc_out< sc_logic > s_start;
    sc_out< sc_logic > s_start_ap_vld;
    sc_in< sc_logic > s_working;
    sc_out< sc_lv<6> > sc_FIFO_DCT_mA_V_address0;
    sc_out< sc_logic > sc_FIFO_DCT_mA_V_ce0;
    sc_out< sc_logic > sc_FIFO_DCT_mA_V_we0;
    sc_out< sc_lv<18> > sc_FIFO_DCT_mA_V_d0;


    // Module declarations
    sc_FIFO_DCT_Prc1(sc_module_name name);
    SC_HAS_PROCESS(sc_FIFO_DCT_Prc1);

    ~sc_FIFO_DCT_Prc1();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<32> > i0_reg_132;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > i0_3_phi_fu_161_p4;
    sc_signal< sc_lv<1> > ap_CS_fsm_state3;
    sc_signal< sc_lv<32> > i0_2_phi_fu_147_p6;
    sc_signal< sc_lv<1> > tmp_read_fu_86_p2;
    sc_signal< sc_lv<1> > tmp_21_read_fu_92_p2;
    sc_signal< sc_lv<32> > i0_4_fu_175_p2;
    sc_signal< sc_lv<1> > tmp_16_fu_182_p2;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state2;
    static const sc_lv<3> ap_ST_fsm_state3;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_40;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_error();
    void thread_error_ap_vld();
    void thread_i0_2_phi_fu_147_p6();
    void thread_i0_3_phi_fu_161_p4();
    void thread_i0_4_fu_175_p2();
    void thread_s_start();
    void thread_s_start_ap_vld();
    void thread_sc_FIFO_DCT_mA_V_address0();
    void thread_sc_FIFO_DCT_mA_V_ce0();
    void thread_sc_FIFO_DCT_mA_V_d0();
    void thread_sc_FIFO_DCT_mA_V_we0();
    void thread_tmp_16_fu_182_p2();
    void thread_tmp_21_read_fu_92_p2();
    void thread_tmp_read_fu_86_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
