// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _sc_FIFO_DCT_HH_
#define _sc_FIFO_DCT_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "sc_FIFO_DCT_Prc2.h"
#include "sc_FIFO_DCT_Prc1.h"
#include "sc_FIFO_DCT_sc_FIeOg.h"
#include "sc_FIFO_DCT_sc_FIfYi.h"

namespace ap_rtl {

struct sc_FIFO_DCT : public sc_module {
    // Port declarations 8
    sc_in_clk clock;
    sc_in< sc_logic > reset;
    sc_in< sc_logic > sync;
    sc_out< sc_logic > data_ok;
    sc_out< sc_logic > done;
    sc_out< sc_logic > error;
    sc_in< sc_lv<8> > din;
    sc_out< sc_lv<8> > dout;


    // Module declarations
    sc_FIFO_DCT(sc_module_name name);
    SC_HAS_PROCESS(sc_FIFO_DCT);

    ~sc_FIFO_DCT();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_FIFO_DCT_sc_FIeOg* sc_FIFO_DCT_mA_V_U;
    sc_FIFO_DCT_sc_FIfYi* sc_FIFO_DCT_mB_V_U;
    sc_FIFO_DCT_Prc2* grp_sc_FIFO_DCT_Prc2_fu_86;
    sc_FIFO_DCT_Prc1* grp_sc_FIFO_DCT_Prc1_fu_118;
    sc_signal< sc_lv<6> > sc_FIFO_DCT_mA_V_address0;
    sc_signal< sc_logic > sc_FIFO_DCT_mA_V_ce0;
    sc_signal< sc_lv<18> > sc_FIFO_DCT_mA_V_q0;
    sc_signal< sc_lv<1> > sc_FIFO_DCT_ssdm_s_load_fu_146_p1;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc2_fu_86_data_ok;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc2_fu_86_data_ok_ap_vld;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc2_fu_86_done;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc2_fu_86_done_ap_vld;
    sc_signal< sc_lv<8> > grp_sc_FIFO_DCT_Prc2_fu_86_dout;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc2_fu_86_dout_ap_vld;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc2_fu_86_s_start_i;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc2_fu_86_s_start_o;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc2_fu_86_s_start_o_ap_vld;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc2_fu_86_s_working;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc2_fu_86_s_working_ap_vld;
    sc_signal< sc_lv<6> > grp_sc_FIFO_DCT_Prc2_fu_86_sc_FIFO_DCT_mA_V_address0;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc2_fu_86_sc_FIFO_DCT_mA_V_ce0;
    sc_signal< sc_lv<6> > grp_sc_FIFO_DCT_Prc2_fu_86_sc_FIFO_DCT_mB_V_address0;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc2_fu_86_sc_FIFO_DCT_mB_V_ce0;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc2_fu_86_sc_FIFO_DCT_mB_V_we0;
    sc_signal< sc_lv<18> > grp_sc_FIFO_DCT_Prc2_fu_86_sc_FIFO_DCT_mB_V_d0;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc1_fu_118_error;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc1_fu_118_error_ap_vld;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc1_fu_118_s_start;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc1_fu_118_s_start_ap_vld;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc1_fu_118_s_working;
    sc_signal< sc_lv<6> > grp_sc_FIFO_DCT_Prc1_fu_118_sc_FIFO_DCT_mA_V_address0;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc1_fu_118_sc_FIFO_DCT_mA_V_ce0;
    sc_signal< sc_logic > grp_sc_FIFO_DCT_Prc1_fu_118_sc_FIFO_DCT_mA_V_we0;
    sc_signal< sc_lv<18> > grp_sc_FIFO_DCT_Prc1_fu_118_sc_FIFO_DCT_mA_V_d0;
    sc_signal< sc_lv<1> > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > s_start;
    sc_signal< sc_lv<1> > s_working;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_data_ok();
    void thread_done();
    void thread_dout();
    void thread_error();
    void thread_s_start();
    void thread_s_working();
    void thread_ap_CS_fsm();
    void thread_ap_CS_fsm_state2();
    void thread_grp_sc_FIFO_DCT_Prc1_fu_118_s_working();
    void thread_grp_sc_FIFO_DCT_Prc2_fu_86_s_start_i();
    void thread_sc_FIFO_DCT_mA_V_address0();
    void thread_sc_FIFO_DCT_mA_V_ce0();
    void thread_sc_FIFO_DCT_ssdm_s_load_fu_146_p1();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
