// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "sc_FIFO_DCT_DCT.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sc_FIFO_DCT_DCT::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic sc_FIFO_DCT_DCT::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state1 = "1";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state2 = "10";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state3 = "100";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state4 = "1000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state5 = "10000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state6 = "100000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state7 = "1000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state8 = "10000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state9 = "100000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state10 = "1000000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state11 = "10000000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state12 = "100000000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<25> sc_FIFO_DCT_DCT::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_3 = "11";
const sc_lv<1> sc_FIFO_DCT_DCT::ap_const_lv1_1 = "1";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_4 = "100";
const sc_lv<1> sc_FIFO_DCT_DCT::ap_const_lv1_0 = "0";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_5 = "101";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_6 = "110";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_7 = "111";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_A = "1010";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_B = "1011";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_D = "1101";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_E = "1110";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_F = "1111";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_10 = "10000";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_13 = "10011";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_14 = "10100";
const sc_lv<4> sc_FIFO_DCT_DCT::ap_const_lv4_0 = "0000";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_2 = "10";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_C = "1100";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_15 = "10101";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_16 = "10110";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_17 = "10111";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_1 = "1";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<4> sc_FIFO_DCT_DCT::ap_const_lv4_8 = "1000";
const sc_lv<4> sc_FIFO_DCT_DCT::ap_const_lv4_1 = "1";
const sc_lv<3> sc_FIFO_DCT_DCT::ap_const_lv3_0 = "000";
const sc_lv<3> sc_FIFO_DCT_DCT::ap_const_lv3_6 = "110";
const sc_lv<3> sc_FIFO_DCT_DCT::ap_const_lv3_5 = "101";
const sc_lv<3> sc_FIFO_DCT_DCT::ap_const_lv3_4 = "100";
const sc_lv<3> sc_FIFO_DCT_DCT::ap_const_lv3_3 = "11";
const sc_lv<3> sc_FIFO_DCT_DCT::ap_const_lv3_2 = "10";
const sc_lv<3> sc_FIFO_DCT_DCT::ap_const_lv3_1 = "1";
const sc_lv<32> sc_FIFO_DCT_DCT::ap_const_lv32_1F = "11111";
const sc_lv<14> sc_FIFO_DCT_DCT::ap_const_lv14_0 = "00000000000000";
const sc_lv<15> sc_FIFO_DCT_DCT::ap_const_lv15_7F = "1111111";

sc_FIFO_DCT_DCT::sc_FIFO_DCT_DCT(sc_module_name name) : sc_module(name), mVcdFile(0) {
    b_a_U = new sc_FIFO_DCT_DCT_b_a("b_a_U");
    b_a_U->clk(ap_clk);
    b_a_U->reset(ap_rst);
    b_a_U->address0(b_a_address0);
    b_a_U->ce0(b_a_ce0);
    b_a_U->q0(b_a_q0);
    b_U = new sc_FIFO_DCT_DCT_b("b_U");
    b_U->clk(ap_clk);
    b_U->reset(ap_rst);
    b_U->address0(b_address0);
    b_U->ce0(b_ce0);
    b_U->q0(b_q0);
    a_U = new sc_FIFO_DCT_DCT_a("a_U");
    a_U->clk(ap_clk);
    a_U->reset(ap_rst);
    a_U->address0(a_address0);
    a_U->ce0(a_ce0);
    a_U->we0(a_we0);
    a_U->d0(s_0_reg_1709);
    a_U->q0(a_q0);
    sc_FIFO_DCT_mul_8bkb_U0 = new sc_FIFO_DCT_mul_8bkb<1,4,8,32,32>("sc_FIFO_DCT_mul_8bkb_U0");
    sc_FIFO_DCT_mul_8bkb_U0->clk(ap_clk);
    sc_FIFO_DCT_mul_8bkb_U0->reset(ap_rst);
    sc_FIFO_DCT_mul_8bkb_U0->din0(b_a_load_reg_1715);
    sc_FIFO_DCT_mul_8bkb_U0->din1(sc_FIFO_DCT_mA_load_reg_1720);
    sc_FIFO_DCT_mul_8bkb_U0->ce(ap_var_for_const0);
    sc_FIFO_DCT_mul_8bkb_U0->dout(grp_fu_895_p2);
    sc_FIFO_DCT_mul_3cud_U1 = new sc_FIFO_DCT_mul_3cud<1,4,32,8,32>("sc_FIFO_DCT_mul_3cud_U1");
    sc_FIFO_DCT_mul_3cud_U1->clk(ap_clk);
    sc_FIFO_DCT_mul_3cud_U1->reset(ap_rst);
    sc_FIFO_DCT_mul_3cud_U1->din0(a_load_reg_1884);
    sc_FIFO_DCT_mul_3cud_U1->din1(b_load_reg_1889);
    sc_FIFO_DCT_mul_3cud_U1->ce(ap_var_for_const0);
    sc_FIFO_DCT_mul_3cud_U1->dout(grp_fu_1290_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_address0);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( tmp_3_cast_fu_1100_p1 );
    sensitive << ( tmp_10_cast_fu_1206_p1 );

    SC_METHOD(thread_a_ce0);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_a_we0);
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_b_a_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_6_cast_fu_835_p1 );

    SC_METHOD(thread_b_a_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_b_address0);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( tmp_11_cast_fu_1216_p1 );

    SC_METHOD(thread_b_ce0);
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_exitcond1_fu_747_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i0_reg_299 );

    SC_METHOD(thread_exitcond2_fu_766_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i1_reg_391 );

    SC_METHOD(thread_exitcond3_fu_1109_p2);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( i1_1_reg_596 );

    SC_METHOD(thread_exitcond4_fu_806_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( i2_reg_497 );

    SC_METHOD(thread_exitcond5_fu_1177_p2);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( i2_2_reg_702 );

    SC_METHOD(thread_i0_1_fu_753_p2);
    sensitive << ( i0_reg_299 );

    SC_METHOD(thread_i0_cast_fu_743_p1);
    sensitive << ( i0_reg_299 );

    SC_METHOD(thread_i1_1_cast_fu_1105_p1);
    sensitive << ( i1_1_reg_596 );

    SC_METHOD(thread_i1_2_fu_772_p2);
    sensitive << ( i1_reg_391 );

    SC_METHOD(thread_i1_3_fu_1115_p2);
    sensitive << ( i1_1_reg_596 );

    SC_METHOD(thread_i2_1_fu_812_p2);
    sensitive << ( i2_reg_497 );

    SC_METHOD(thread_i2_2_cast_fu_1173_p1);
    sensitive << ( i2_2_reg_702 );

    SC_METHOD(thread_i2_3_fu_1183_p2);
    sensitive << ( i2_2_reg_702 );

    SC_METHOD(thread_i2_cast_fu_802_p1);
    sensitive << ( i2_reg_497 );

    SC_METHOD(thread_newSel10_fu_1408_p3);
    sensitive << ( s_0_6_reg_1899 );
    sensitive << ( sel_tmp7_reg_1907 );
    sensitive << ( s_7_6_19_reg_607 );

    SC_METHOD(thread_newSel11_fu_1414_p3);
    sensitive << ( s_7_6_19_reg_607 );
    sensitive << ( or_cond6_fu_1404_p2 );
    sensitive << ( newSel10_fu_1408_p3 );

    SC_METHOD(thread_newSel12_fu_1429_p3);
    sensitive << ( s_0_6_reg_1899 );
    sensitive << ( sel_tmp7_reg_1907 );
    sensitive << ( s_6_6_reg_619 );

    SC_METHOD(thread_newSel13_fu_1435_p3);
    sensitive << ( s_6_6_reg_619 );
    sensitive << ( or_cond6_fu_1404_p2 );
    sensitive << ( newSel12_fu_1429_p3 );

    SC_METHOD(thread_newSel14_fu_1450_p3);
    sensitive << ( s_0_6_reg_1899 );
    sensitive << ( sel_tmp5_reg_1918 );
    sensitive << ( s_7_32_reg_631 );

    SC_METHOD(thread_newSel15_fu_1456_p3);
    sensitive << ( s_7_32_reg_631 );
    sensitive << ( or_cond6_fu_1404_p2 );
    sensitive << ( newSel14_fu_1450_p3 );

    SC_METHOD(thread_newSel16_fu_1348_p3);
    sensitive << ( grp_fu_1290_p2 );
    sensitive << ( sel_tmp5_fu_1305_p2 );
    sensitive << ( s_7_11_reg_643 );

    SC_METHOD(thread_newSel17_fu_1471_p3);
    sensitive << ( s_0_6_reg_1899 );
    sensitive << ( sel_tmp11_reg_1924 );
    sensitive << ( s_7_12_reg_655 );

    SC_METHOD(thread_newSel18_fu_1477_p3);
    sensitive << ( or_cond4_reg_1929 );
    sensitive << ( s_7_12_reg_655 );
    sensitive << ( newSel17_fu_1471_p3 );

    SC_METHOD(thread_newSel19_fu_1364_p3);
    sensitive << ( grp_fu_1290_p2 );
    sensitive << ( sel_tmp11_fu_1315_p2 );
    sensitive << ( s_7_13_reg_667 );

    SC_METHOD(thread_newSel1_fu_1019_p3);
    sensitive << ( s_7_3_reg_402 );
    sensitive << ( or_cond2_fu_1009_p2 );
    sensitive << ( newSel_fu_1013_p3 );

    SC_METHOD(thread_newSel2_fu_1076_p3);
    sensitive << ( s_0_5_reg_1730 );
    sensitive << ( sel_tmp8_reg_1755 );
    sensitive << ( s_7_6_reg_450 );

    SC_METHOD(thread_newSel3_fu_1034_p3);
    sensitive << ( s_0_5_reg_1730 );
    sensitive << ( sel_tmp_reg_1738 );
    sensitive << ( s_6_3_reg_414 );

    SC_METHOD(thread_newSel4_fu_1040_p3);
    sensitive << ( s_6_3_reg_414 );
    sensitive << ( or_cond2_fu_1009_p2 );
    sensitive << ( newSel3_fu_1034_p3 );

    SC_METHOD(thread_newSel5_fu_1082_p3);
    sensitive << ( or_cond_reg_1760 );
    sensitive << ( s_7_6_reg_450 );
    sensitive << ( newSel2_fu_1076_p3 );

    SC_METHOD(thread_newSel6_fu_1055_p3);
    sensitive << ( s_0_5_reg_1730 );
    sensitive << ( sel_tmp4_reg_1749 );
    sensitive << ( s_7_2_12_reg_426 );

    SC_METHOD(thread_newSel7_fu_1061_p3);
    sensitive << ( s_7_2_12_reg_426 );
    sensitive << ( or_cond2_fu_1009_p2 );
    sensitive << ( newSel6_fu_1055_p3 );

    SC_METHOD(thread_newSel8_fu_969_p3);
    sensitive << ( grp_fu_895_p2 );
    sensitive << ( sel_tmp8_fu_920_p2 );
    sensitive << ( s_7_8_reg_462 );

    SC_METHOD(thread_newSel9_fu_953_p3);
    sensitive << ( grp_fu_895_p2 );
    sensitive << ( sel_tmp4_fu_910_p2 );
    sensitive << ( s_7_4_reg_438 );

    SC_METHOD(thread_newSel_fu_1013_p3);
    sensitive << ( s_0_5_reg_1730 );
    sensitive << ( sel_tmp_reg_1738 );
    sensitive << ( s_7_3_reg_402 );

    SC_METHOD(thread_or_cond1_fu_941_p2);
    sensitive << ( sel_tmp8_fu_920_p2 );
    sensitive << ( sel_tmp6_fu_915_p2 );

    SC_METHOD(thread_or_cond2_fu_1009_p2);
    sensitive << ( sel_tmp2_reg_1744 );
    sensitive << ( sel_tmp4_reg_1749 );

    SC_METHOD(thread_or_cond3_fu_947_p2);
    sensitive << ( or_cond_fu_935_p2 );
    sensitive << ( or_cond1_fu_941_p2 );

    SC_METHOD(thread_or_cond4_fu_1330_p2);
    sensitive << ( sel_tmp13_fu_1325_p2 );
    sensitive << ( sel_tmp12_fu_1320_p2 );

    SC_METHOD(thread_or_cond5_fu_1336_p2);
    sensitive << ( sel_tmp11_fu_1315_p2 );
    sensitive << ( sel_tmp10_fu_1310_p2 );

    SC_METHOD(thread_or_cond6_fu_1404_p2);
    sensitive << ( sel_tmp9_reg_1913 );
    sensitive << ( sel_tmp5_reg_1918 );

    SC_METHOD(thread_or_cond7_fu_1342_p2);
    sensitive << ( or_cond4_fu_1330_p2 );
    sensitive << ( or_cond5_fu_1336_p2 );

    SC_METHOD(thread_or_cond_fu_935_p2);
    sensitive << ( sel_tmp3_fu_930_p2 );
    sensitive << ( sel_tmp1_fu_925_p2 );

    SC_METHOD(thread_p_lshr_cast_fu_1502_p1);
    sensitive << ( tmp_24_reg_1874 );

    SC_METHOD(thread_p_lshr_f_cast_fu_1520_p1);
    sensitive << ( tmp_25_fu_1511_p4 );

    SC_METHOD(thread_p_neg_fu_1267_p2);
    sensitive << ( s_0_2_21_fu_1257_p2 );

    SC_METHOD(thread_p_neg_t_fu_1505_p2);
    sensitive << ( p_lshr_cast_fu_1502_p1 );

    SC_METHOD(thread_s_0_2_21_fu_1257_p2);
    sensitive << ( tmp26_fu_1251_p2 );
    sensitive << ( tmp23_fu_1233_p2 );

    SC_METHOD(thread_s_0_fu_886_p2);
    sensitive << ( tmp20_fu_880_p2 );
    sensitive << ( tmp17_fu_862_p2 );

    SC_METHOD(thread_s_7_16_fu_1422_p3);
    sensitive << ( or_cond7_reg_1934 );
    sensitive << ( s_7_6_19_reg_607 );
    sensitive << ( newSel11_fu_1414_p3 );

    SC_METHOD(thread_s_7_17_fu_1443_p3);
    sensitive << ( or_cond7_reg_1934 );
    sensitive << ( s_6_6_reg_619 );
    sensitive << ( newSel13_fu_1435_p3 );

    SC_METHOD(thread_s_7_1_fu_1048_p3);
    sensitive << ( or_cond3_reg_1765 );
    sensitive << ( s_6_3_reg_414 );
    sensitive << ( newSel4_fu_1040_p3 );

    SC_METHOD(thread_s_7_28_fu_985_p3);
    sensitive << ( grp_fu_895_p2 );
    sensitive << ( s_7_27_reg_474 );
    sensitive << ( sel_tmp1_fu_925_p2 );

    SC_METHOD(thread_s_7_29_fu_993_p3);
    sensitive << ( s_7_27_reg_474 );
    sensitive << ( sel_tmp3_fu_930_p2 );
    sensitive << ( s_7_28_fu_985_p3 );

    SC_METHOD(thread_s_7_30_fu_1001_p3);
    sensitive << ( grp_fu_895_p2 );
    sensitive << ( s_7_10_reg_486 );
    sensitive << ( sel_tmp3_fu_930_p2 );

    SC_METHOD(thread_s_7_33_fu_1464_p3);
    sensitive << ( or_cond7_reg_1934 );
    sensitive << ( s_7_32_reg_631 );
    sensitive << ( newSel15_fu_1456_p3 );

    SC_METHOD(thread_s_7_34_fu_1356_p3);
    sensitive << ( or_cond7_fu_1342_p2 );
    sensitive << ( s_7_11_reg_643 );
    sensitive << ( newSel16_fu_1348_p3 );

    SC_METHOD(thread_s_7_35_fu_1484_p3);
    sensitive << ( or_cond7_reg_1934 );
    sensitive << ( s_7_12_reg_655 );
    sensitive << ( newSel18_fu_1477_p3 );

    SC_METHOD(thread_s_7_36_fu_1372_p3);
    sensitive << ( or_cond4_fu_1330_p2 );
    sensitive << ( s_7_13_reg_667 );
    sensitive << ( newSel19_fu_1364_p3 );

    SC_METHOD(thread_s_7_37_fu_1380_p3);
    sensitive << ( grp_fu_1290_p2 );
    sensitive << ( s_7_14_reg_679 );
    sensitive << ( sel_tmp12_fu_1320_p2 );

    SC_METHOD(thread_s_7_38_fu_1388_p3);
    sensitive << ( s_7_14_reg_679 );
    sensitive << ( sel_tmp13_fu_1325_p2 );
    sensitive << ( s_7_37_fu_1380_p3 );

    SC_METHOD(thread_s_7_39_fu_1396_p3);
    sensitive << ( grp_fu_1290_p2 );
    sensitive << ( s_7_15_reg_691 );
    sensitive << ( sel_tmp13_fu_1325_p2 );

    SC_METHOD(thread_s_7_3_14_fu_1069_p3);
    sensitive << ( or_cond3_reg_1765 );
    sensitive << ( s_7_2_12_reg_426 );
    sensitive << ( newSel7_fu_1061_p3 );

    SC_METHOD(thread_s_7_5_fu_961_p3);
    sensitive << ( or_cond3_fu_947_p2 );
    sensitive << ( s_7_4_reg_438 );
    sensitive << ( newSel9_fu_953_p3 );

    SC_METHOD(thread_s_7_7_fu_1089_p3);
    sensitive << ( or_cond3_reg_1765 );
    sensitive << ( s_7_6_reg_450 );
    sensitive << ( newSel5_fu_1082_p3 );

    SC_METHOD(thread_s_7_9_fu_977_p3);
    sensitive << ( or_cond_fu_935_p2 );
    sensitive << ( s_7_8_reg_462 );
    sensitive << ( newSel8_fu_969_p3 );

    SC_METHOD(thread_s_7_fu_1027_p3);
    sensitive << ( or_cond3_reg_1765 );
    sensitive << ( s_7_3_reg_402 );
    sensitive << ( newSel1_fu_1019_p3 );

    SC_METHOD(thread_s_DCT);
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( tmp_14_read_fu_214_p2 );

    SC_METHOD(thread_s_DCT_ap_vld);
    sensitive << ( ap_CS_fsm_state23 );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( tmp_14_read_fu_214_p2 );

    SC_METHOD(thread_s_working);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_read_fu_178_p2 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_s_working_ap_vld);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_read_fu_178_p2 );
    sensitive << ( ap_CS_fsm_state23 );

    SC_METHOD(thread_sc_FIFO_DCT_exec_cnt_o);
    sensitive << ( sc_FIFO_DCT_exec_cnt_i );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond1_fu_747_p2 );

    SC_METHOD(thread_sc_FIFO_DCT_exec_cnt_o_ap_vld);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond1_fu_747_p2 );

    SC_METHOD(thread_sc_FIFO_DCT_mA_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_7_cast_fu_845_p1 );

    SC_METHOD(thread_sc_FIFO_DCT_mA_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_sc_FIFO_DCT_mB_address0);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( tmp_8_cast_fu_1491_p1 );

    SC_METHOD(thread_sc_FIFO_DCT_mB_ce0);
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_sc_FIFO_DCT_mB_d0);
    sensitive << ( s_0_2_21_reg_1861 );
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_sc_FIFO_DCT_mB_we0);
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_sc_FIFO_DCT_mC_address0);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( tmp_16_cast_fu_1547_p1 );

    SC_METHOD(thread_sc_FIFO_DCT_mC_ce0);
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_sc_FIFO_DCT_mC_d0);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( tmp_15_fu_1536_p2 );

    SC_METHOD(thread_sc_FIFO_DCT_mC_we0);
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_sel_tmp10_fu_1310_p2);
    sensitive << ( tmp_30_reg_1840 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_sel_tmp11_fu_1315_p2);
    sensitive << ( tmp_30_reg_1840 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_sel_tmp12_fu_1320_p2);
    sensitive << ( tmp_30_reg_1840 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_sel_tmp13_fu_1325_p2);
    sensitive << ( tmp_30_reg_1840 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_sel_tmp1_fu_925_p2);
    sensitive << ( tmp_23_reg_1688 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_sel_tmp2_fu_905_p2);
    sensitive << ( tmp_23_reg_1688 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_sel_tmp3_fu_930_p2);
    sensitive << ( tmp_23_reg_1688 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_sel_tmp4_fu_910_p2);
    sensitive << ( tmp_23_reg_1688 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_sel_tmp5_fu_1305_p2);
    sensitive << ( tmp_30_reg_1840 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_sel_tmp6_fu_915_p2);
    sensitive << ( tmp_23_reg_1688 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_sel_tmp7_fu_1295_p2);
    sensitive << ( tmp_30_reg_1840 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_sel_tmp8_fu_920_p2);
    sensitive << ( tmp_23_reg_1688 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_sel_tmp9_fu_1300_p2);
    sensitive << ( tmp_30_reg_1840 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_sel_tmp_fu_900_p2);
    sensitive << ( tmp_23_reg_1688 );
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_tmp15_fu_850_p2);
    sensitive << ( s_6_3_reg_414 );
    sensitive << ( s_7_2_12_reg_426 );

    SC_METHOD(thread_tmp16_fu_856_p2);
    sensitive << ( s_7_4_reg_438 );
    sensitive << ( s_7_6_reg_450 );

    SC_METHOD(thread_tmp17_fu_862_p2);
    sensitive << ( tmp16_fu_856_p2 );
    sensitive << ( tmp15_fu_850_p2 );

    SC_METHOD(thread_tmp18_fu_868_p2);
    sensitive << ( s_7_8_reg_462 );
    sensitive << ( s_7_10_reg_486 );

    SC_METHOD(thread_tmp19_fu_874_p2);
    sensitive << ( s_7_3_reg_402 );
    sensitive << ( s_7_27_reg_474 );

    SC_METHOD(thread_tmp20_fu_880_p2);
    sensitive << ( tmp19_fu_874_p2 );
    sensitive << ( tmp18_fu_868_p2 );

    SC_METHOD(thread_tmp21_fu_1221_p2);
    sensitive << ( s_6_6_reg_619 );
    sensitive << ( s_7_32_reg_631 );

    SC_METHOD(thread_tmp22_fu_1227_p2);
    sensitive << ( s_7_11_reg_643 );
    sensitive << ( s_7_12_reg_655 );

    SC_METHOD(thread_tmp23_fu_1233_p2);
    sensitive << ( tmp22_fu_1227_p2 );
    sensitive << ( tmp21_fu_1221_p2 );

    SC_METHOD(thread_tmp24_fu_1239_p2);
    sensitive << ( s_7_13_reg_667 );
    sensitive << ( s_7_15_reg_691 );

    SC_METHOD(thread_tmp25_fu_1245_p2);
    sensitive << ( s_7_6_19_reg_607 );
    sensitive << ( s_7_14_reg_679 );

    SC_METHOD(thread_tmp26_fu_1251_p2);
    sensitive << ( tmp25_fu_1245_p2 );
    sensitive << ( tmp24_fu_1239_p2 );

    SC_METHOD(thread_tmp_10_cast_fu_1206_p1);
    sensitive << ( tmp_10_fu_1201_p2 );

    SC_METHOD(thread_tmp_10_fu_1201_p2);
    sensitive << ( i0_cast_reg_1645 );
    sensitive << ( tmp_9_fu_1193_p3 );

    SC_METHOD(thread_tmp_11_cast_fu_1216_p1);
    sensitive << ( tmp_11_fu_1211_p2 );

    SC_METHOD(thread_tmp_11_fu_1211_p2);
    sensitive << ( tmp_4_reg_1826 );
    sensitive << ( i2_2_cast_fu_1173_p1 );

    SC_METHOD(thread_tmp_13_cast_fu_1532_p1);
    sensitive << ( tmp_13_fu_1524_p3 );

    SC_METHOD(thread_tmp_13_fu_1524_p3);
    sensitive << ( tmp_29_fu_1495_p3 );
    sensitive << ( p_neg_t_fu_1505_p2 );
    sensitive << ( p_lshr_f_cast_fu_1520_p1 );

    SC_METHOD(thread_tmp_14_read_fu_214_p2);
    sensitive << ( s_done );
    sensitive << ( ap_CS_fsm_state24 );
    sensitive << ( tmp_14_read_fu_214_p2 );

    SC_METHOD(thread_tmp_15_fu_1536_p2);
    sensitive << ( tmp_13_cast_fu_1532_p1 );

    SC_METHOD(thread_tmp_16_cast_fu_1547_p1);
    sensitive << ( tmp_16_reg_1879 );

    SC_METHOD(thread_tmp_16_fu_1283_p2);
    sensitive << ( tmp_1_reg_1675 );
    sensitive << ( i1_1_cast_reg_1813 );

    SC_METHOD(thread_tmp_1_fu_794_p3);
    sensitive << ( tmp_20_fu_790_p1 );

    SC_METHOD(thread_tmp_20_fu_790_p1);
    sensitive << ( i0_reg_299 );

    SC_METHOD(thread_tmp_21_fu_778_p1);
    sensitive << ( i1_reg_391 );

    SC_METHOD(thread_tmp_22_fu_1121_p1);
    sensitive << ( i1_1_reg_596 );

    SC_METHOD(thread_tmp_23_fu_818_p1);
    sensitive << ( i2_reg_497 );

    SC_METHOD(thread_tmp_25_fu_1511_p4);
    sensitive << ( s_0_2_21_reg_1861 );

    SC_METHOD(thread_tmp_29_fu_1495_p3);
    sensitive << ( s_0_2_21_reg_1861 );

    SC_METHOD(thread_tmp_2_fu_782_p3);
    sensitive << ( tmp_21_fu_778_p1 );

    SC_METHOD(thread_tmp_30_fu_1189_p1);
    sensitive << ( i2_2_reg_702 );

    SC_METHOD(thread_tmp_3_cast_fu_1100_p1);
    sensitive << ( tmp_3_fu_1096_p2 );

    SC_METHOD(thread_tmp_3_fu_1096_p2);
    sensitive << ( i0_cast_reg_1645 );
    sensitive << ( tmp_2_reg_1669 );

    SC_METHOD(thread_tmp_4_fu_1125_p3);
    sensitive << ( tmp_22_fu_1121_p1 );

    SC_METHOD(thread_tmp_5_fu_822_p3);
    sensitive << ( tmp_23_fu_818_p1 );

    SC_METHOD(thread_tmp_6_cast_fu_835_p1);
    sensitive << ( tmp_6_fu_830_p2 );

    SC_METHOD(thread_tmp_6_fu_830_p2);
    sensitive << ( i0_cast_reg_1645 );
    sensitive << ( tmp_5_fu_822_p3 );

    SC_METHOD(thread_tmp_7_cast_fu_845_p1);
    sensitive << ( tmp_7_fu_840_p2 );

    SC_METHOD(thread_tmp_7_fu_840_p2);
    sensitive << ( tmp_2_reg_1669 );
    sensitive << ( i2_cast_fu_802_p1 );

    SC_METHOD(thread_tmp_8_cast_fu_1491_p1);
    sensitive << ( tmp_8_reg_1869 );

    SC_METHOD(thread_tmp_8_fu_1263_p2);
    sensitive << ( i0_cast_reg_1645 );
    sensitive << ( tmp_4_reg_1826 );

    SC_METHOD(thread_tmp_9_fu_1193_p3);
    sensitive << ( tmp_30_fu_1189_p1 );

    SC_METHOD(thread_tmp_read_fu_178_p2);
    sensitive << ( s_buffered );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_read_fu_178_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond2_fu_766_p2 );
    sensitive << ( exitcond4_fu_806_p2 );
    sensitive << ( exitcond3_fu_1109_p2 );
    sensitive << ( exitcond5_fu_1177_p2 );
    sensitive << ( tmp_read_fu_178_p2 );
    sensitive << ( exitcond1_fu_747_p2 );
    sensitive << ( tmp_14_read_fu_214_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sc_FIFO_DCT_DCT_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, sc_FIFO_DCT_mA_address0, "(port)sc_FIFO_DCT_mA_address0");
    sc_trace(mVcdFile, sc_FIFO_DCT_mA_ce0, "(port)sc_FIFO_DCT_mA_ce0");
    sc_trace(mVcdFile, sc_FIFO_DCT_mA_q0, "(port)sc_FIFO_DCT_mA_q0");
    sc_trace(mVcdFile, sc_FIFO_DCT_mB_address0, "(port)sc_FIFO_DCT_mB_address0");
    sc_trace(mVcdFile, sc_FIFO_DCT_mB_ce0, "(port)sc_FIFO_DCT_mB_ce0");
    sc_trace(mVcdFile, sc_FIFO_DCT_mB_we0, "(port)sc_FIFO_DCT_mB_we0");
    sc_trace(mVcdFile, sc_FIFO_DCT_mB_d0, "(port)sc_FIFO_DCT_mB_d0");
    sc_trace(mVcdFile, sc_FIFO_DCT_mC_address0, "(port)sc_FIFO_DCT_mC_address0");
    sc_trace(mVcdFile, sc_FIFO_DCT_mC_ce0, "(port)sc_FIFO_DCT_mC_ce0");
    sc_trace(mVcdFile, sc_FIFO_DCT_mC_we0, "(port)sc_FIFO_DCT_mC_we0");
    sc_trace(mVcdFile, sc_FIFO_DCT_mC_d0, "(port)sc_FIFO_DCT_mC_d0");
    sc_trace(mVcdFile, sc_FIFO_DCT_exec_cnt_i, "(port)sc_FIFO_DCT_exec_cnt_i");
    sc_trace(mVcdFile, sc_FIFO_DCT_exec_cnt_o, "(port)sc_FIFO_DCT_exec_cnt_o");
    sc_trace(mVcdFile, sc_FIFO_DCT_exec_cnt_o_ap_vld, "(port)sc_FIFO_DCT_exec_cnt_o_ap_vld");
    sc_trace(mVcdFile, s_buffered, "(port)s_buffered");
    sc_trace(mVcdFile, s_working, "(port)s_working");
    sc_trace(mVcdFile, s_working_ap_vld, "(port)s_working_ap_vld");
    sc_trace(mVcdFile, s_DCT, "(port)s_DCT");
    sc_trace(mVcdFile, s_DCT_ap_vld, "(port)s_DCT_ap_vld");
    sc_trace(mVcdFile, s_done, "(port)s_done");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, b_a_address0, "b_a_address0");
    sc_trace(mVcdFile, b_a_ce0, "b_a_ce0");
    sc_trace(mVcdFile, b_a_q0, "b_a_q0");
    sc_trace(mVcdFile, b_address0, "b_address0");
    sc_trace(mVcdFile, b_ce0, "b_ce0");
    sc_trace(mVcdFile, b_q0, "b_q0");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, i0_cast_fu_743_p1, "i0_cast_fu_743_p1");
    sc_trace(mVcdFile, i0_cast_reg_1645, "i0_cast_reg_1645");
    sc_trace(mVcdFile, i0_1_fu_753_p2, "i0_1_fu_753_p2");
    sc_trace(mVcdFile, i0_1_reg_1656, "i0_1_reg_1656");
    sc_trace(mVcdFile, i1_2_fu_772_p2, "i1_2_fu_772_p2");
    sc_trace(mVcdFile, i1_2_reg_1664, "i1_2_reg_1664");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_2_fu_782_p3, "tmp_2_fu_782_p3");
    sc_trace(mVcdFile, tmp_2_reg_1669, "tmp_2_reg_1669");
    sc_trace(mVcdFile, exitcond2_fu_766_p2, "exitcond2_fu_766_p2");
    sc_trace(mVcdFile, tmp_1_fu_794_p3, "tmp_1_fu_794_p3");
    sc_trace(mVcdFile, tmp_1_reg_1675, "tmp_1_reg_1675");
    sc_trace(mVcdFile, i2_1_fu_812_p2, "i2_1_fu_812_p2");
    sc_trace(mVcdFile, i2_1_reg_1683, "i2_1_reg_1683");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_23_fu_818_p1, "tmp_23_fu_818_p1");
    sc_trace(mVcdFile, tmp_23_reg_1688, "tmp_23_reg_1688");
    sc_trace(mVcdFile, exitcond4_fu_806_p2, "exitcond4_fu_806_p2");
    sc_trace(mVcdFile, s_0_fu_886_p2, "s_0_fu_886_p2");
    sc_trace(mVcdFile, s_0_reg_1709, "s_0_reg_1709");
    sc_trace(mVcdFile, b_a_load_reg_1715, "b_a_load_reg_1715");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, sc_FIFO_DCT_mA_load_reg_1720, "sc_FIFO_DCT_mA_load_reg_1720");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, grp_fu_895_p2, "grp_fu_895_p2");
    sc_trace(mVcdFile, s_0_5_reg_1730, "s_0_5_reg_1730");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, sel_tmp_fu_900_p2, "sel_tmp_fu_900_p2");
    sc_trace(mVcdFile, sel_tmp_reg_1738, "sel_tmp_reg_1738");
    sc_trace(mVcdFile, sel_tmp2_fu_905_p2, "sel_tmp2_fu_905_p2");
    sc_trace(mVcdFile, sel_tmp2_reg_1744, "sel_tmp2_reg_1744");
    sc_trace(mVcdFile, sel_tmp4_fu_910_p2, "sel_tmp4_fu_910_p2");
    sc_trace(mVcdFile, sel_tmp4_reg_1749, "sel_tmp4_reg_1749");
    sc_trace(mVcdFile, sel_tmp8_fu_920_p2, "sel_tmp8_fu_920_p2");
    sc_trace(mVcdFile, sel_tmp8_reg_1755, "sel_tmp8_reg_1755");
    sc_trace(mVcdFile, or_cond_fu_935_p2, "or_cond_fu_935_p2");
    sc_trace(mVcdFile, or_cond_reg_1760, "or_cond_reg_1760");
    sc_trace(mVcdFile, or_cond3_fu_947_p2, "or_cond3_fu_947_p2");
    sc_trace(mVcdFile, or_cond3_reg_1765, "or_cond3_reg_1765");
    sc_trace(mVcdFile, s_7_5_fu_961_p3, "s_7_5_fu_961_p3");
    sc_trace(mVcdFile, s_7_5_reg_1773, "s_7_5_reg_1773");
    sc_trace(mVcdFile, s_7_9_fu_977_p3, "s_7_9_fu_977_p3");
    sc_trace(mVcdFile, s_7_9_reg_1778, "s_7_9_reg_1778");
    sc_trace(mVcdFile, s_7_29_fu_993_p3, "s_7_29_fu_993_p3");
    sc_trace(mVcdFile, s_7_29_reg_1783, "s_7_29_reg_1783");
    sc_trace(mVcdFile, s_7_30_fu_1001_p3, "s_7_30_fu_1001_p3");
    sc_trace(mVcdFile, s_7_30_reg_1788, "s_7_30_reg_1788");
    sc_trace(mVcdFile, s_7_fu_1027_p3, "s_7_fu_1027_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, s_7_1_fu_1048_p3, "s_7_1_fu_1048_p3");
    sc_trace(mVcdFile, s_7_3_14_fu_1069_p3, "s_7_3_14_fu_1069_p3");
    sc_trace(mVcdFile, s_7_7_fu_1089_p3, "s_7_7_fu_1089_p3");
    sc_trace(mVcdFile, i1_1_cast_fu_1105_p1, "i1_1_cast_fu_1105_p1");
    sc_trace(mVcdFile, i1_1_cast_reg_1813, "i1_1_cast_reg_1813");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, i1_3_fu_1115_p2, "i1_3_fu_1115_p2");
    sc_trace(mVcdFile, i1_3_reg_1821, "i1_3_reg_1821");
    sc_trace(mVcdFile, tmp_4_fu_1125_p3, "tmp_4_fu_1125_p3");
    sc_trace(mVcdFile, tmp_4_reg_1826, "tmp_4_reg_1826");
    sc_trace(mVcdFile, exitcond3_fu_1109_p2, "exitcond3_fu_1109_p2");
    sc_trace(mVcdFile, i2_3_fu_1183_p2, "i2_3_fu_1183_p2");
    sc_trace(mVcdFile, i2_3_reg_1835, "i2_3_reg_1835");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, tmp_30_fu_1189_p1, "tmp_30_fu_1189_p1");
    sc_trace(mVcdFile, tmp_30_reg_1840, "tmp_30_reg_1840");
    sc_trace(mVcdFile, exitcond5_fu_1177_p2, "exitcond5_fu_1177_p2");
    sc_trace(mVcdFile, s_0_2_21_fu_1257_p2, "s_0_2_21_fu_1257_p2");
    sc_trace(mVcdFile, s_0_2_21_reg_1861, "s_0_2_21_reg_1861");
    sc_trace(mVcdFile, tmp_8_fu_1263_p2, "tmp_8_fu_1263_p2");
    sc_trace(mVcdFile, tmp_8_reg_1869, "tmp_8_reg_1869");
    sc_trace(mVcdFile, tmp_24_reg_1874, "tmp_24_reg_1874");
    sc_trace(mVcdFile, tmp_16_fu_1283_p2, "tmp_16_fu_1283_p2");
    sc_trace(mVcdFile, tmp_16_reg_1879, "tmp_16_reg_1879");
    sc_trace(mVcdFile, a_q0, "a_q0");
    sc_trace(mVcdFile, a_load_reg_1884, "a_load_reg_1884");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, b_load_reg_1889, "b_load_reg_1889");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, grp_fu_1290_p2, "grp_fu_1290_p2");
    sc_trace(mVcdFile, s_0_6_reg_1899, "s_0_6_reg_1899");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, sel_tmp7_fu_1295_p2, "sel_tmp7_fu_1295_p2");
    sc_trace(mVcdFile, sel_tmp7_reg_1907, "sel_tmp7_reg_1907");
    sc_trace(mVcdFile, sel_tmp9_fu_1300_p2, "sel_tmp9_fu_1300_p2");
    sc_trace(mVcdFile, sel_tmp9_reg_1913, "sel_tmp9_reg_1913");
    sc_trace(mVcdFile, sel_tmp5_fu_1305_p2, "sel_tmp5_fu_1305_p2");
    sc_trace(mVcdFile, sel_tmp5_reg_1918, "sel_tmp5_reg_1918");
    sc_trace(mVcdFile, sel_tmp11_fu_1315_p2, "sel_tmp11_fu_1315_p2");
    sc_trace(mVcdFile, sel_tmp11_reg_1924, "sel_tmp11_reg_1924");
    sc_trace(mVcdFile, or_cond4_fu_1330_p2, "or_cond4_fu_1330_p2");
    sc_trace(mVcdFile, or_cond4_reg_1929, "or_cond4_reg_1929");
    sc_trace(mVcdFile, or_cond7_fu_1342_p2, "or_cond7_fu_1342_p2");
    sc_trace(mVcdFile, or_cond7_reg_1934, "or_cond7_reg_1934");
    sc_trace(mVcdFile, s_7_34_fu_1356_p3, "s_7_34_fu_1356_p3");
    sc_trace(mVcdFile, s_7_34_reg_1942, "s_7_34_reg_1942");
    sc_trace(mVcdFile, s_7_36_fu_1372_p3, "s_7_36_fu_1372_p3");
    sc_trace(mVcdFile, s_7_36_reg_1947, "s_7_36_reg_1947");
    sc_trace(mVcdFile, s_7_38_fu_1388_p3, "s_7_38_fu_1388_p3");
    sc_trace(mVcdFile, s_7_38_reg_1952, "s_7_38_reg_1952");
    sc_trace(mVcdFile, s_7_39_fu_1396_p3, "s_7_39_fu_1396_p3");
    sc_trace(mVcdFile, s_7_39_reg_1957, "s_7_39_reg_1957");
    sc_trace(mVcdFile, s_7_16_fu_1422_p3, "s_7_16_fu_1422_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, s_7_17_fu_1443_p3, "s_7_17_fu_1443_p3");
    sc_trace(mVcdFile, s_7_33_fu_1464_p3, "s_7_33_fu_1464_p3");
    sc_trace(mVcdFile, s_7_35_fu_1484_p3, "s_7_35_fu_1484_p3");
    sc_trace(mVcdFile, a_address0, "a_address0");
    sc_trace(mVcdFile, a_ce0, "a_ce0");
    sc_trace(mVcdFile, a_we0, "a_we0");
    sc_trace(mVcdFile, i0_reg_299, "i0_reg_299");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_read_fu_178_p2, "tmp_read_fu_178_p2");
    sc_trace(mVcdFile, s_7_2_reg_311, "s_7_2_reg_311");
    sc_trace(mVcdFile, exitcond1_fu_747_p2, "exitcond1_fu_747_p2");
    sc_trace(mVcdFile, s_7_3_reg_402, "s_7_3_reg_402");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, s_6_2_reg_321, "s_6_2_reg_321");
    sc_trace(mVcdFile, s_6_3_reg_414, "s_6_3_reg_414");
    sc_trace(mVcdFile, s_5_2_reg_331, "s_5_2_reg_331");
    sc_trace(mVcdFile, s_7_2_12_reg_426, "s_7_2_12_reg_426");
    sc_trace(mVcdFile, s_4_2_reg_341, "s_4_2_reg_341");
    sc_trace(mVcdFile, s_7_4_reg_438, "s_7_4_reg_438");
    sc_trace(mVcdFile, s_3_2_reg_351, "s_3_2_reg_351");
    sc_trace(mVcdFile, s_7_6_reg_450, "s_7_6_reg_450");
    sc_trace(mVcdFile, s_2_2_reg_361, "s_2_2_reg_361");
    sc_trace(mVcdFile, s_7_8_reg_462, "s_7_8_reg_462");
    sc_trace(mVcdFile, s_1_2_reg_371, "s_1_2_reg_371");
    sc_trace(mVcdFile, s_7_27_reg_474, "s_7_27_reg_474");
    sc_trace(mVcdFile, s_0_2_reg_381, "s_0_2_reg_381");
    sc_trace(mVcdFile, i1_reg_391, "i1_reg_391");
    sc_trace(mVcdFile, s_7_10_reg_486, "s_7_10_reg_486");
    sc_trace(mVcdFile, i2_reg_497, "i2_reg_497");
    sc_trace(mVcdFile, s_7_5_16_reg_508, "s_7_5_16_reg_508");
    sc_trace(mVcdFile, s_7_6_19_reg_607, "s_7_6_19_reg_607");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, s_6_5_reg_519, "s_6_5_reg_519");
    sc_trace(mVcdFile, s_6_6_reg_619, "s_6_6_reg_619");
    sc_trace(mVcdFile, s_5_5_reg_530, "s_5_5_reg_530");
    sc_trace(mVcdFile, s_7_32_reg_631, "s_7_32_reg_631");
    sc_trace(mVcdFile, s_4_5_reg_541, "s_4_5_reg_541");
    sc_trace(mVcdFile, s_7_11_reg_643, "s_7_11_reg_643");
    sc_trace(mVcdFile, s_3_5_reg_552, "s_3_5_reg_552");
    sc_trace(mVcdFile, s_7_12_reg_655, "s_7_12_reg_655");
    sc_trace(mVcdFile, s_2_5_reg_563, "s_2_5_reg_563");
    sc_trace(mVcdFile, s_7_13_reg_667, "s_7_13_reg_667");
    sc_trace(mVcdFile, s_1_5_reg_574, "s_1_5_reg_574");
    sc_trace(mVcdFile, s_7_14_reg_679, "s_7_14_reg_679");
    sc_trace(mVcdFile, s_0_5_17_reg_585, "s_0_5_17_reg_585");
    sc_trace(mVcdFile, i1_1_reg_596, "i1_1_reg_596");
    sc_trace(mVcdFile, s_7_15_reg_691, "s_7_15_reg_691");
    sc_trace(mVcdFile, i2_2_reg_702, "i2_2_reg_702");
    sc_trace(mVcdFile, tmp_6_cast_fu_835_p1, "tmp_6_cast_fu_835_p1");
    sc_trace(mVcdFile, tmp_7_cast_fu_845_p1, "tmp_7_cast_fu_845_p1");
    sc_trace(mVcdFile, tmp_3_cast_fu_1100_p1, "tmp_3_cast_fu_1100_p1");
    sc_trace(mVcdFile, tmp_10_cast_fu_1206_p1, "tmp_10_cast_fu_1206_p1");
    sc_trace(mVcdFile, tmp_11_cast_fu_1216_p1, "tmp_11_cast_fu_1216_p1");
    sc_trace(mVcdFile, tmp_8_cast_fu_1491_p1, "tmp_8_cast_fu_1491_p1");
    sc_trace(mVcdFile, tmp_16_cast_fu_1547_p1, "tmp_16_cast_fu_1547_p1");
    sc_trace(mVcdFile, s_0_1_fu_142, "s_0_1_fu_142");
    sc_trace(mVcdFile, s_7_19_fu_146, "s_7_19_fu_146");
    sc_trace(mVcdFile, s_7_20_fu_150, "s_7_20_fu_150");
    sc_trace(mVcdFile, s_7_21_fu_154, "s_7_21_fu_154");
    sc_trace(mVcdFile, s_7_22_fu_158, "s_7_22_fu_158");
    sc_trace(mVcdFile, s_7_23_fu_162, "s_7_23_fu_162");
    sc_trace(mVcdFile, s_7_24_fu_166, "s_7_24_fu_166");
    sc_trace(mVcdFile, s_7_25_fu_170, "s_7_25_fu_170");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, tmp_14_read_fu_214_p2, "tmp_14_read_fu_214_p2");
    sc_trace(mVcdFile, tmp_21_fu_778_p1, "tmp_21_fu_778_p1");
    sc_trace(mVcdFile, tmp_20_fu_790_p1, "tmp_20_fu_790_p1");
    sc_trace(mVcdFile, tmp_5_fu_822_p3, "tmp_5_fu_822_p3");
    sc_trace(mVcdFile, tmp_6_fu_830_p2, "tmp_6_fu_830_p2");
    sc_trace(mVcdFile, i2_cast_fu_802_p1, "i2_cast_fu_802_p1");
    sc_trace(mVcdFile, tmp_7_fu_840_p2, "tmp_7_fu_840_p2");
    sc_trace(mVcdFile, tmp16_fu_856_p2, "tmp16_fu_856_p2");
    sc_trace(mVcdFile, tmp15_fu_850_p2, "tmp15_fu_850_p2");
    sc_trace(mVcdFile, tmp19_fu_874_p2, "tmp19_fu_874_p2");
    sc_trace(mVcdFile, tmp18_fu_868_p2, "tmp18_fu_868_p2");
    sc_trace(mVcdFile, tmp20_fu_880_p2, "tmp20_fu_880_p2");
    sc_trace(mVcdFile, tmp17_fu_862_p2, "tmp17_fu_862_p2");
    sc_trace(mVcdFile, sel_tmp3_fu_930_p2, "sel_tmp3_fu_930_p2");
    sc_trace(mVcdFile, sel_tmp1_fu_925_p2, "sel_tmp1_fu_925_p2");
    sc_trace(mVcdFile, sel_tmp6_fu_915_p2, "sel_tmp6_fu_915_p2");
    sc_trace(mVcdFile, or_cond1_fu_941_p2, "or_cond1_fu_941_p2");
    sc_trace(mVcdFile, newSel9_fu_953_p3, "newSel9_fu_953_p3");
    sc_trace(mVcdFile, newSel8_fu_969_p3, "newSel8_fu_969_p3");
    sc_trace(mVcdFile, s_7_28_fu_985_p3, "s_7_28_fu_985_p3");
    sc_trace(mVcdFile, or_cond2_fu_1009_p2, "or_cond2_fu_1009_p2");
    sc_trace(mVcdFile, newSel_fu_1013_p3, "newSel_fu_1013_p3");
    sc_trace(mVcdFile, newSel1_fu_1019_p3, "newSel1_fu_1019_p3");
    sc_trace(mVcdFile, newSel3_fu_1034_p3, "newSel3_fu_1034_p3");
    sc_trace(mVcdFile, newSel4_fu_1040_p3, "newSel4_fu_1040_p3");
    sc_trace(mVcdFile, newSel6_fu_1055_p3, "newSel6_fu_1055_p3");
    sc_trace(mVcdFile, newSel7_fu_1061_p3, "newSel7_fu_1061_p3");
    sc_trace(mVcdFile, newSel2_fu_1076_p3, "newSel2_fu_1076_p3");
    sc_trace(mVcdFile, newSel5_fu_1082_p3, "newSel5_fu_1082_p3");
    sc_trace(mVcdFile, tmp_3_fu_1096_p2, "tmp_3_fu_1096_p2");
    sc_trace(mVcdFile, tmp_22_fu_1121_p1, "tmp_22_fu_1121_p1");
    sc_trace(mVcdFile, tmp_9_fu_1193_p3, "tmp_9_fu_1193_p3");
    sc_trace(mVcdFile, tmp_10_fu_1201_p2, "tmp_10_fu_1201_p2");
    sc_trace(mVcdFile, i2_2_cast_fu_1173_p1, "i2_2_cast_fu_1173_p1");
    sc_trace(mVcdFile, tmp_11_fu_1211_p2, "tmp_11_fu_1211_p2");
    sc_trace(mVcdFile, tmp22_fu_1227_p2, "tmp22_fu_1227_p2");
    sc_trace(mVcdFile, tmp21_fu_1221_p2, "tmp21_fu_1221_p2");
    sc_trace(mVcdFile, tmp25_fu_1245_p2, "tmp25_fu_1245_p2");
    sc_trace(mVcdFile, tmp24_fu_1239_p2, "tmp24_fu_1239_p2");
    sc_trace(mVcdFile, tmp26_fu_1251_p2, "tmp26_fu_1251_p2");
    sc_trace(mVcdFile, tmp23_fu_1233_p2, "tmp23_fu_1233_p2");
    sc_trace(mVcdFile, p_neg_fu_1267_p2, "p_neg_fu_1267_p2");
    sc_trace(mVcdFile, sel_tmp13_fu_1325_p2, "sel_tmp13_fu_1325_p2");
    sc_trace(mVcdFile, sel_tmp12_fu_1320_p2, "sel_tmp12_fu_1320_p2");
    sc_trace(mVcdFile, sel_tmp10_fu_1310_p2, "sel_tmp10_fu_1310_p2");
    sc_trace(mVcdFile, or_cond5_fu_1336_p2, "or_cond5_fu_1336_p2");
    sc_trace(mVcdFile, newSel16_fu_1348_p3, "newSel16_fu_1348_p3");
    sc_trace(mVcdFile, newSel19_fu_1364_p3, "newSel19_fu_1364_p3");
    sc_trace(mVcdFile, s_7_37_fu_1380_p3, "s_7_37_fu_1380_p3");
    sc_trace(mVcdFile, or_cond6_fu_1404_p2, "or_cond6_fu_1404_p2");
    sc_trace(mVcdFile, newSel10_fu_1408_p3, "newSel10_fu_1408_p3");
    sc_trace(mVcdFile, newSel11_fu_1414_p3, "newSel11_fu_1414_p3");
    sc_trace(mVcdFile, newSel12_fu_1429_p3, "newSel12_fu_1429_p3");
    sc_trace(mVcdFile, newSel13_fu_1435_p3, "newSel13_fu_1435_p3");
    sc_trace(mVcdFile, newSel14_fu_1450_p3, "newSel14_fu_1450_p3");
    sc_trace(mVcdFile, newSel15_fu_1456_p3, "newSel15_fu_1456_p3");
    sc_trace(mVcdFile, newSel17_fu_1471_p3, "newSel17_fu_1471_p3");
    sc_trace(mVcdFile, newSel18_fu_1477_p3, "newSel18_fu_1477_p3");
    sc_trace(mVcdFile, p_lshr_cast_fu_1502_p1, "p_lshr_cast_fu_1502_p1");
    sc_trace(mVcdFile, tmp_25_fu_1511_p4, "tmp_25_fu_1511_p4");
    sc_trace(mVcdFile, tmp_29_fu_1495_p3, "tmp_29_fu_1495_p3");
    sc_trace(mVcdFile, p_neg_t_fu_1505_p2, "p_neg_t_fu_1505_p2");
    sc_trace(mVcdFile, p_lshr_f_cast_fu_1520_p1, "p_lshr_f_cast_fu_1520_p1");
    sc_trace(mVcdFile, tmp_13_fu_1524_p3, "tmp_13_fu_1524_p3");
    sc_trace(mVcdFile, tmp_13_cast_fu_1532_p1, "tmp_13_cast_fu_1532_p1");
    sc_trace(mVcdFile, tmp_15_fu_1536_p2, "tmp_15_fu_1536_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

sc_FIFO_DCT_DCT::~sc_FIFO_DCT_DCT() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete b_a_U;
    delete b_U;
    delete a_U;
    delete sc_FIFO_DCT_mul_8bkb_U0;
    delete sc_FIFO_DCT_mul_3cud_U1;
}

void sc_FIFO_DCT_DCT::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void sc_FIFO_DCT_DCT::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_1109_p2.read()))) {
        i0_reg_299 = i0_1_reg_1656.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
                !esl_seteq<1,1,1>(tmp_read_fu_178_p2.read(), ap_const_lv1_0))) {
        i0_reg_299 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()))) {
        i1_1_reg_596 = i1_3_reg_1821.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                !esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        i1_1_reg_596 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        i1_reg_391 = i1_2_reg_1664.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state4.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_747_p2.read()))) {
        i1_reg_391 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state21.read()))) {
        i2_2_reg_702 = i2_3_reg_1835.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_1109_p2.read()))) {
        i2_2_reg_702 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()))) {
        i2_reg_497 = i2_1_reg_1683.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        i2_reg_497 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        s_0_2_reg_381 = s_0_reg_1709.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state4.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_747_p2.read()))) {
        s_0_2_reg_381 = s_0_1_fu_142.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()))) {
        s_0_5_17_reg_585 = s_0_2_21_reg_1861.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                !esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        s_0_5_17_reg_585 = s_0_2_reg_381.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        s_1_2_reg_371 = s_7_27_reg_474.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state4.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_747_p2.read()))) {
        s_1_2_reg_371 = s_7_19_fu_146.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()))) {
        s_1_5_reg_574 = s_7_14_reg_679.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                !esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        s_1_5_reg_574 = s_1_2_reg_371.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        s_2_2_reg_361 = s_7_8_reg_462.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state4.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_747_p2.read()))) {
        s_2_2_reg_361 = s_7_20_fu_150.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()))) {
        s_2_5_reg_563 = s_7_13_reg_667.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                !esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        s_2_5_reg_563 = s_2_2_reg_361.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        s_3_2_reg_351 = s_7_6_reg_450.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state4.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_747_p2.read()))) {
        s_3_2_reg_351 = s_7_21_fu_154.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()))) {
        s_3_5_reg_552 = s_7_12_reg_655.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                !esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        s_3_5_reg_552 = s_3_2_reg_351.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        s_4_2_reg_341 = s_7_4_reg_438.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state4.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_747_p2.read()))) {
        s_4_2_reg_341 = s_7_22_fu_158.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()))) {
        s_4_5_reg_541 = s_7_11_reg_643.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                !esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        s_4_5_reg_541 = s_4_2_reg_341.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        s_5_2_reg_331 = s_7_2_12_reg_426.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state4.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_747_p2.read()))) {
        s_5_2_reg_331 = s_7_23_fu_162.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()))) {
        s_5_5_reg_530 = s_7_32_reg_631.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                !esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        s_5_5_reg_530 = s_5_2_reg_331.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        s_6_2_reg_321 = s_6_3_reg_414.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state4.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_747_p2.read()))) {
        s_6_2_reg_321 = s_7_24_fu_166.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()))) {
        s_6_3_reg_414 = s_7_1_fu_1048_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        s_6_3_reg_414 = s_6_2_reg_321.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()))) {
        s_6_5_reg_519 = s_6_6_reg_619.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                !esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        s_6_5_reg_519 = s_6_2_reg_321.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state21.read()))) {
        s_6_6_reg_619 = s_7_17_fu_1443_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_1109_p2.read()))) {
        s_6_6_reg_619 = s_6_5_reg_519.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()))) {
        s_7_10_reg_486 = s_7_30_reg_1788.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        s_7_10_reg_486 = s_0_2_reg_381.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state21.read()))) {
        s_7_11_reg_643 = s_7_34_reg_1942.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_1109_p2.read()))) {
        s_7_11_reg_643 = s_4_5_reg_541.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state21.read()))) {
        s_7_12_reg_655 = s_7_35_fu_1484_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_1109_p2.read()))) {
        s_7_12_reg_655 = s_3_5_reg_552.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state21.read()))) {
        s_7_13_reg_667 = s_7_36_reg_1947.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_1109_p2.read()))) {
        s_7_13_reg_667 = s_2_5_reg_563.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state21.read()))) {
        s_7_14_reg_679 = s_7_38_reg_1952.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_1109_p2.read()))) {
        s_7_14_reg_679 = s_1_5_reg_574.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state21.read()))) {
        s_7_15_reg_691 = s_7_39_reg_1957.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_1109_p2.read()))) {
        s_7_15_reg_691 = s_0_5_17_reg_585.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()))) {
        s_7_27_reg_474 = s_7_29_reg_1783.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        s_7_27_reg_474 = s_1_2_reg_371.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()))) {
        s_7_2_12_reg_426 = s_7_3_14_fu_1069_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        s_7_2_12_reg_426 = s_5_2_reg_331.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        s_7_2_reg_311 = s_7_3_reg_402.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state4.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_747_p2.read()))) {
        s_7_2_reg_311 = s_7_25_fu_170.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state21.read()))) {
        s_7_32_reg_631 = s_7_33_fu_1464_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_1109_p2.read()))) {
        s_7_32_reg_631 = s_5_5_reg_530.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()))) {
        s_7_3_reg_402 = s_7_fu_1027_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        s_7_3_reg_402 = s_7_2_reg_311.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()))) {
        s_7_4_reg_438 = s_7_5_reg_1773.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        s_7_4_reg_438 = s_4_2_reg_341.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()))) {
        s_7_5_16_reg_508 = s_7_6_19_reg_607.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                !esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        s_7_5_16_reg_508 = s_7_2_reg_311.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state21.read()))) {
        s_7_6_19_reg_607 = s_7_16_fu_1422_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_1109_p2.read()))) {
        s_7_6_19_reg_607 = s_7_5_16_reg_508.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()))) {
        s_7_6_reg_450 = s_7_7_fu_1089_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        s_7_6_reg_450 = s_3_2_reg_351.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()))) {
        s_7_8_reg_462 = s_7_9_reg_1778.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        s_7_8_reg_462 = s_2_2_reg_361.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state16.read()))) {
        a_load_reg_1884 = a_q0.read();
        b_load_reg_1889 = b_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()))) {
        b_a_load_reg_1715 = b_a_q0.read();
        sc_FIFO_DCT_mA_load_reg_1720 = sc_FIFO_DCT_mA_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state4.read(), ap_const_lv1_1))) {
        i0_1_reg_1656 = i0_1_fu_753_p2.read();
        i0_cast_reg_1645 = i0_cast_fu_743_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()))) {
        i1_1_cast_reg_1813 = i1_1_cast_fu_1105_p1.read();
        i1_3_reg_1821 = i1_3_fu_1115_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()))) {
        i1_2_reg_1664 = i1_2_fu_772_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        i2_1_reg_1683 = i2_1_fu_812_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read()))) {
        i2_3_reg_1835 = i2_3_fu_1183_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state11.read()))) {
        or_cond3_reg_1765 = or_cond3_fu_947_p2.read();
        or_cond_reg_1760 = or_cond_fu_935_p2.read();
        s_0_5_reg_1730 = grp_fu_895_p2.read();
        s_7_29_reg_1783 = s_7_29_fu_993_p3.read();
        s_7_30_reg_1788 = s_7_30_fu_1001_p3.read();
        s_7_5_reg_1773 = s_7_5_fu_961_p3.read();
        s_7_9_reg_1778 = s_7_9_fu_977_p3.read();
        sel_tmp2_reg_1744 = sel_tmp2_fu_905_p2.read();
        sel_tmp4_reg_1749 = sel_tmp4_fu_910_p2.read();
        sel_tmp8_reg_1755 = sel_tmp8_fu_920_p2.read();
        sel_tmp_reg_1738 = sel_tmp_fu_900_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state20.read()))) {
        or_cond4_reg_1929 = or_cond4_fu_1330_p2.read();
        or_cond7_reg_1934 = or_cond7_fu_1342_p2.read();
        s_0_6_reg_1899 = grp_fu_1290_p2.read();
        s_7_34_reg_1942 = s_7_34_fu_1356_p3.read();
        s_7_36_reg_1947 = s_7_36_fu_1372_p3.read();
        s_7_38_reg_1952 = s_7_38_fu_1388_p3.read();
        s_7_39_reg_1957 = s_7_39_fu_1396_p3.read();
        sel_tmp11_reg_1924 = sel_tmp11_fu_1315_p2.read();
        sel_tmp5_reg_1918 = sel_tmp5_fu_1305_p2.read();
        sel_tmp7_reg_1907 = sel_tmp7_fu_1295_p2.read();
        sel_tmp9_reg_1913 = sel_tmp9_fu_1300_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_1109_p2.read()))) {
        s_0_1_fu_142 = s_0_5_17_reg_585.read();
        s_7_19_fu_146 = s_1_5_reg_574.read();
        s_7_20_fu_150 = s_2_5_reg_563.read();
        s_7_21_fu_154 = s_3_5_reg_552.read();
        s_7_22_fu_158 = s_4_5_reg_541.read();
        s_7_23_fu_162 = s_5_5_reg_530.read();
        s_7_24_fu_166 = s_6_5_reg_519.read();
        s_7_25_fu_170 = s_7_5_16_reg_508.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_1177_p2.read()))) {
        s_0_2_21_reg_1861 = s_0_2_21_fu_1257_p2.read();
        tmp_16_reg_1879 = tmp_16_fu_1283_p2.read();
        tmp_24_reg_1874 = p_neg_fu_1267_p2.read().range(31, 19);
        tmp_8_reg_1869 = tmp_8_fu_1263_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_806_p2.read()))) {
        s_0_reg_1709 = s_0_fu_886_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && !esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        tmp_1_reg_1675 = tmp_1_fu_794_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_806_p2.read()))) {
        tmp_23_reg_1688 = tmp_23_fu_818_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0))) {
        tmp_2_reg_1669 = tmp_2_fu_782_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_1177_p2.read()))) {
        tmp_30_reg_1840 = tmp_30_fu_1189_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_1109_p2.read()))) {
        tmp_4_reg_1826 = tmp_4_fu_1125_p3.read();
    }
}

void sc_FIFO_DCT_DCT::thread_a_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read()))) {
        a_address0 =  (sc_lv<6>) (tmp_10_cast_fu_1206_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        a_address0 =  (sc_lv<6>) (tmp_3_cast_fu_1100_p1.read());
    } else {
        a_address0 = "XXXXXX";
    }
}

void sc_FIFO_DCT_DCT::thread_a_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read())))) {
        a_ce0 = ap_const_logic_1;
    } else {
        a_ce0 = ap_const_logic_0;
    }
}

void sc_FIFO_DCT_DCT::thread_a_we0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read())))) {
        a_we0 = ap_const_logic_1;
    } else {
        a_we0 = ap_const_logic_0;
    }
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read().range(10, 10);
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read().range(11, 11);
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read().range(12, 12);
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read().range(13, 13);
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read().range(14, 14);
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read().range(15, 15);
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read().range(16, 16);
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read().range(19, 19);
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read().range(20, 20);
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read().range(21, 21);
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read().range(22, 22);
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read().range(23, 23);
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read().range(2, 2);
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read().range(3, 3);
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read().range(4, 4);
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read().range(5, 5);
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read().range(6, 6);
}

void sc_FIFO_DCT_DCT::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read().range(7, 7);
}

void sc_FIFO_DCT_DCT::thread_b_a_address0() {
    b_a_address0 =  (sc_lv<6>) (tmp_6_cast_fu_835_p1.read());
}

void sc_FIFO_DCT_DCT::thread_b_a_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        b_a_ce0 = ap_const_logic_1;
    } else {
        b_a_ce0 = ap_const_logic_0;
    }
}

void sc_FIFO_DCT_DCT::thread_b_address0() {
    b_address0 =  (sc_lv<6>) (tmp_11_cast_fu_1216_p1.read());
}

void sc_FIFO_DCT_DCT::thread_b_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state15.read()))) {
        b_ce0 = ap_const_logic_1;
    } else {
        b_ce0 = ap_const_logic_0;
    }
}

void sc_FIFO_DCT_DCT::thread_exitcond1_fu_747_p2() {
    exitcond1_fu_747_p2 = (!i0_reg_299.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i0_reg_299.read() == ap_const_lv4_8);
}

void sc_FIFO_DCT_DCT::thread_exitcond2_fu_766_p2() {
    exitcond2_fu_766_p2 = (!i1_reg_391.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_391.read() == ap_const_lv4_8);
}

void sc_FIFO_DCT_DCT::thread_exitcond3_fu_1109_p2() {
    exitcond3_fu_1109_p2 = (!i1_1_reg_596.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i1_1_reg_596.read() == ap_const_lv4_8);
}

void sc_FIFO_DCT_DCT::thread_exitcond4_fu_806_p2() {
    exitcond4_fu_806_p2 = (!i2_reg_497.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i2_reg_497.read() == ap_const_lv4_8);
}

void sc_FIFO_DCT_DCT::thread_exitcond5_fu_1177_p2() {
    exitcond5_fu_1177_p2 = (!i2_2_reg_702.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i2_2_reg_702.read() == ap_const_lv4_8);
}

void sc_FIFO_DCT_DCT::thread_i0_1_fu_753_p2() {
    i0_1_fu_753_p2 = (!i0_reg_299.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i0_reg_299.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void sc_FIFO_DCT_DCT::thread_i0_cast_fu_743_p1() {
    i0_cast_fu_743_p1 = esl_zext<6,4>(i0_reg_299.read());
}

void sc_FIFO_DCT_DCT::thread_i1_1_cast_fu_1105_p1() {
    i1_1_cast_fu_1105_p1 = esl_zext<6,4>(i1_1_reg_596.read());
}

void sc_FIFO_DCT_DCT::thread_i1_2_fu_772_p2() {
    i1_2_fu_772_p2 = (!i1_reg_391.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i1_reg_391.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void sc_FIFO_DCT_DCT::thread_i1_3_fu_1115_p2() {
    i1_3_fu_1115_p2 = (!i1_1_reg_596.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i1_1_reg_596.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void sc_FIFO_DCT_DCT::thread_i2_1_fu_812_p2() {
    i2_1_fu_812_p2 = (!i2_reg_497.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i2_reg_497.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void sc_FIFO_DCT_DCT::thread_i2_2_cast_fu_1173_p1() {
    i2_2_cast_fu_1173_p1 = esl_zext<6,4>(i2_2_reg_702.read());
}

void sc_FIFO_DCT_DCT::thread_i2_3_fu_1183_p2() {
    i2_3_fu_1183_p2 = (!i2_2_reg_702.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i2_2_reg_702.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void sc_FIFO_DCT_DCT::thread_i2_cast_fu_802_p1() {
    i2_cast_fu_802_p1 = esl_zext<6,4>(i2_reg_497.read());
}

void sc_FIFO_DCT_DCT::thread_newSel10_fu_1408_p3() {
    newSel10_fu_1408_p3 = (!sel_tmp7_reg_1907.read()[0].is_01())? sc_lv<32>(): ((sel_tmp7_reg_1907.read()[0].to_bool())? s_7_6_19_reg_607.read(): s_0_6_reg_1899.read());
}

void sc_FIFO_DCT_DCT::thread_newSel11_fu_1414_p3() {
    newSel11_fu_1414_p3 = (!or_cond6_fu_1404_p2.read()[0].is_01())? sc_lv<32>(): ((or_cond6_fu_1404_p2.read()[0].to_bool())? s_7_6_19_reg_607.read(): newSel10_fu_1408_p3.read());
}

void sc_FIFO_DCT_DCT::thread_newSel12_fu_1429_p3() {
    newSel12_fu_1429_p3 = (!sel_tmp7_reg_1907.read()[0].is_01())? sc_lv<32>(): ((sel_tmp7_reg_1907.read()[0].to_bool())? s_0_6_reg_1899.read(): s_6_6_reg_619.read());
}

void sc_FIFO_DCT_DCT::thread_newSel13_fu_1435_p3() {
    newSel13_fu_1435_p3 = (!or_cond6_fu_1404_p2.read()[0].is_01())? sc_lv<32>(): ((or_cond6_fu_1404_p2.read()[0].to_bool())? s_6_6_reg_619.read(): newSel12_fu_1429_p3.read());
}

void sc_FIFO_DCT_DCT::thread_newSel14_fu_1450_p3() {
    newSel14_fu_1450_p3 = (!sel_tmp5_reg_1918.read()[0].is_01())? sc_lv<32>(): ((sel_tmp5_reg_1918.read()[0].to_bool())? s_7_32_reg_631.read(): s_0_6_reg_1899.read());
}

void sc_FIFO_DCT_DCT::thread_newSel15_fu_1456_p3() {
    newSel15_fu_1456_p3 = (!or_cond6_fu_1404_p2.read()[0].is_01())? sc_lv<32>(): ((or_cond6_fu_1404_p2.read()[0].to_bool())? newSel14_fu_1450_p3.read(): s_7_32_reg_631.read());
}

void sc_FIFO_DCT_DCT::thread_newSel16_fu_1348_p3() {
    newSel16_fu_1348_p3 = (!sel_tmp5_fu_1305_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp5_fu_1305_p2.read()[0].to_bool())? grp_fu_1290_p2.read(): s_7_11_reg_643.read());
}

void sc_FIFO_DCT_DCT::thread_newSel17_fu_1471_p3() {
    newSel17_fu_1471_p3 = (!sel_tmp11_reg_1924.read()[0].is_01())? sc_lv<32>(): ((sel_tmp11_reg_1924.read()[0].to_bool())? s_7_12_reg_655.read(): s_0_6_reg_1899.read());
}

void sc_FIFO_DCT_DCT::thread_newSel18_fu_1477_p3() {
    newSel18_fu_1477_p3 = (!or_cond4_reg_1929.read()[0].is_01())? sc_lv<32>(): ((or_cond4_reg_1929.read()[0].to_bool())? s_7_12_reg_655.read(): newSel17_fu_1471_p3.read());
}

void sc_FIFO_DCT_DCT::thread_newSel19_fu_1364_p3() {
    newSel19_fu_1364_p3 = (!sel_tmp11_fu_1315_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp11_fu_1315_p2.read()[0].to_bool())? grp_fu_1290_p2.read(): s_7_13_reg_667.read());
}

void sc_FIFO_DCT_DCT::thread_newSel1_fu_1019_p3() {
    newSel1_fu_1019_p3 = (!or_cond2_fu_1009_p2.read()[0].is_01())? sc_lv<32>(): ((or_cond2_fu_1009_p2.read()[0].to_bool())? s_7_3_reg_402.read(): newSel_fu_1013_p3.read());
}

void sc_FIFO_DCT_DCT::thread_newSel2_fu_1076_p3() {
    newSel2_fu_1076_p3 = (!sel_tmp8_reg_1755.read()[0].is_01())? sc_lv<32>(): ((sel_tmp8_reg_1755.read()[0].to_bool())? s_7_6_reg_450.read(): s_0_5_reg_1730.read());
}

void sc_FIFO_DCT_DCT::thread_newSel3_fu_1034_p3() {
    newSel3_fu_1034_p3 = (!sel_tmp_reg_1738.read()[0].is_01())? sc_lv<32>(): ((sel_tmp_reg_1738.read()[0].to_bool())? s_0_5_reg_1730.read(): s_6_3_reg_414.read());
}

void sc_FIFO_DCT_DCT::thread_newSel4_fu_1040_p3() {
    newSel4_fu_1040_p3 = (!or_cond2_fu_1009_p2.read()[0].is_01())? sc_lv<32>(): ((or_cond2_fu_1009_p2.read()[0].to_bool())? s_6_3_reg_414.read(): newSel3_fu_1034_p3.read());
}

void sc_FIFO_DCT_DCT::thread_newSel5_fu_1082_p3() {
    newSel5_fu_1082_p3 = (!or_cond_reg_1760.read()[0].is_01())? sc_lv<32>(): ((or_cond_reg_1760.read()[0].to_bool())? s_7_6_reg_450.read(): newSel2_fu_1076_p3.read());
}

void sc_FIFO_DCT_DCT::thread_newSel6_fu_1055_p3() {
    newSel6_fu_1055_p3 = (!sel_tmp4_reg_1749.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_reg_1749.read()[0].to_bool())? s_7_2_12_reg_426.read(): s_0_5_reg_1730.read());
}

void sc_FIFO_DCT_DCT::thread_newSel7_fu_1061_p3() {
    newSel7_fu_1061_p3 = (!or_cond2_fu_1009_p2.read()[0].is_01())? sc_lv<32>(): ((or_cond2_fu_1009_p2.read()[0].to_bool())? newSel6_fu_1055_p3.read(): s_7_2_12_reg_426.read());
}

void sc_FIFO_DCT_DCT::thread_newSel8_fu_969_p3() {
    newSel8_fu_969_p3 = (!sel_tmp8_fu_920_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp8_fu_920_p2.read()[0].to_bool())? grp_fu_895_p2.read(): s_7_8_reg_462.read());
}

void sc_FIFO_DCT_DCT::thread_newSel9_fu_953_p3() {
    newSel9_fu_953_p3 = (!sel_tmp4_fu_910_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp4_fu_910_p2.read()[0].to_bool())? grp_fu_895_p2.read(): s_7_4_reg_438.read());
}

void sc_FIFO_DCT_DCT::thread_newSel_fu_1013_p3() {
    newSel_fu_1013_p3 = (!sel_tmp_reg_1738.read()[0].is_01())? sc_lv<32>(): ((sel_tmp_reg_1738.read()[0].to_bool())? s_7_3_reg_402.read(): s_0_5_reg_1730.read());
}

void sc_FIFO_DCT_DCT::thread_or_cond1_fu_941_p2() {
    or_cond1_fu_941_p2 = (sel_tmp8_fu_920_p2.read() | sel_tmp6_fu_915_p2.read());
}

void sc_FIFO_DCT_DCT::thread_or_cond2_fu_1009_p2() {
    or_cond2_fu_1009_p2 = (sel_tmp4_reg_1749.read() | sel_tmp2_reg_1744.read());
}

void sc_FIFO_DCT_DCT::thread_or_cond3_fu_947_p2() {
    or_cond3_fu_947_p2 = (or_cond_fu_935_p2.read() | or_cond1_fu_941_p2.read());
}

void sc_FIFO_DCT_DCT::thread_or_cond4_fu_1330_p2() {
    or_cond4_fu_1330_p2 = (sel_tmp13_fu_1325_p2.read() | sel_tmp12_fu_1320_p2.read());
}

void sc_FIFO_DCT_DCT::thread_or_cond5_fu_1336_p2() {
    or_cond5_fu_1336_p2 = (sel_tmp11_fu_1315_p2.read() | sel_tmp10_fu_1310_p2.read());
}

void sc_FIFO_DCT_DCT::thread_or_cond6_fu_1404_p2() {
    or_cond6_fu_1404_p2 = (sel_tmp5_reg_1918.read() | sel_tmp9_reg_1913.read());
}

void sc_FIFO_DCT_DCT::thread_or_cond7_fu_1342_p2() {
    or_cond7_fu_1342_p2 = (or_cond4_fu_1330_p2.read() | or_cond5_fu_1336_p2.read());
}

void sc_FIFO_DCT_DCT::thread_or_cond_fu_935_p2() {
    or_cond_fu_935_p2 = (sel_tmp3_fu_930_p2.read() | sel_tmp1_fu_925_p2.read());
}

void sc_FIFO_DCT_DCT::thread_p_lshr_cast_fu_1502_p1() {
    p_lshr_cast_fu_1502_p1 = esl_zext<14,13>(tmp_24_reg_1874.read());
}

void sc_FIFO_DCT_DCT::thread_p_lshr_f_cast_fu_1520_p1() {
    p_lshr_f_cast_fu_1520_p1 = esl_zext<14,13>(tmp_25_fu_1511_p4.read());
}

void sc_FIFO_DCT_DCT::thread_p_neg_fu_1267_p2() {
    p_neg_fu_1267_p2 = (!ap_const_lv32_0.is_01() || !s_0_2_21_fu_1257_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(s_0_2_21_fu_1257_p2.read()));
}

void sc_FIFO_DCT_DCT::thread_p_neg_t_fu_1505_p2() {
    p_neg_t_fu_1505_p2 = (!ap_const_lv14_0.is_01() || !p_lshr_cast_fu_1502_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(ap_const_lv14_0) - sc_biguint<14>(p_lshr_cast_fu_1502_p1.read()));
}

void sc_FIFO_DCT_DCT::thread_s_0_2_21_fu_1257_p2() {
    s_0_2_21_fu_1257_p2 = (!tmp26_fu_1251_p2.read().is_01() || !tmp23_fu_1233_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp26_fu_1251_p2.read()) + sc_biguint<32>(tmp23_fu_1233_p2.read()));
}

void sc_FIFO_DCT_DCT::thread_s_0_fu_886_p2() {
    s_0_fu_886_p2 = (!tmp20_fu_880_p2.read().is_01() || !tmp17_fu_862_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp20_fu_880_p2.read()) + sc_biguint<32>(tmp17_fu_862_p2.read()));
}

void sc_FIFO_DCT_DCT::thread_s_7_16_fu_1422_p3() {
    s_7_16_fu_1422_p3 = (!or_cond7_reg_1934.read()[0].is_01())? sc_lv<32>(): ((or_cond7_reg_1934.read()[0].to_bool())? s_7_6_19_reg_607.read(): newSel11_fu_1414_p3.read());
}

void sc_FIFO_DCT_DCT::thread_s_7_17_fu_1443_p3() {
    s_7_17_fu_1443_p3 = (!or_cond7_reg_1934.read()[0].is_01())? sc_lv<32>(): ((or_cond7_reg_1934.read()[0].to_bool())? s_6_6_reg_619.read(): newSel13_fu_1435_p3.read());
}

void sc_FIFO_DCT_DCT::thread_s_7_1_fu_1048_p3() {
    s_7_1_fu_1048_p3 = (!or_cond3_reg_1765.read()[0].is_01())? sc_lv<32>(): ((or_cond3_reg_1765.read()[0].to_bool())? s_6_3_reg_414.read(): newSel4_fu_1040_p3.read());
}

void sc_FIFO_DCT_DCT::thread_s_7_28_fu_985_p3() {
    s_7_28_fu_985_p3 = (!sel_tmp1_fu_925_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp1_fu_925_p2.read()[0].to_bool())? grp_fu_895_p2.read(): s_7_27_reg_474.read());
}

void sc_FIFO_DCT_DCT::thread_s_7_29_fu_993_p3() {
    s_7_29_fu_993_p3 = (!sel_tmp3_fu_930_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp3_fu_930_p2.read()[0].to_bool())? s_7_27_reg_474.read(): s_7_28_fu_985_p3.read());
}

void sc_FIFO_DCT_DCT::thread_s_7_30_fu_1001_p3() {
    s_7_30_fu_1001_p3 = (!sel_tmp3_fu_930_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp3_fu_930_p2.read()[0].to_bool())? grp_fu_895_p2.read(): s_7_10_reg_486.read());
}

void sc_FIFO_DCT_DCT::thread_s_7_33_fu_1464_p3() {
    s_7_33_fu_1464_p3 = (!or_cond7_reg_1934.read()[0].is_01())? sc_lv<32>(): ((or_cond7_reg_1934.read()[0].to_bool())? s_7_32_reg_631.read(): newSel15_fu_1456_p3.read());
}

void sc_FIFO_DCT_DCT::thread_s_7_34_fu_1356_p3() {
    s_7_34_fu_1356_p3 = (!or_cond7_fu_1342_p2.read()[0].is_01())? sc_lv<32>(): ((or_cond7_fu_1342_p2.read()[0].to_bool())? s_7_11_reg_643.read(): newSel16_fu_1348_p3.read());
}

void sc_FIFO_DCT_DCT::thread_s_7_35_fu_1484_p3() {
    s_7_35_fu_1484_p3 = (!or_cond7_reg_1934.read()[0].is_01())? sc_lv<32>(): ((or_cond7_reg_1934.read()[0].to_bool())? newSel18_fu_1477_p3.read(): s_7_12_reg_655.read());
}

void sc_FIFO_DCT_DCT::thread_s_7_36_fu_1372_p3() {
    s_7_36_fu_1372_p3 = (!or_cond4_fu_1330_p2.read()[0].is_01())? sc_lv<32>(): ((or_cond4_fu_1330_p2.read()[0].to_bool())? s_7_13_reg_667.read(): newSel19_fu_1364_p3.read());
}

void sc_FIFO_DCT_DCT::thread_s_7_37_fu_1380_p3() {
    s_7_37_fu_1380_p3 = (!sel_tmp12_fu_1320_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp12_fu_1320_p2.read()[0].to_bool())? grp_fu_1290_p2.read(): s_7_14_reg_679.read());
}

void sc_FIFO_DCT_DCT::thread_s_7_38_fu_1388_p3() {
    s_7_38_fu_1388_p3 = (!sel_tmp13_fu_1325_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp13_fu_1325_p2.read()[0].to_bool())? s_7_14_reg_679.read(): s_7_37_fu_1380_p3.read());
}

void sc_FIFO_DCT_DCT::thread_s_7_39_fu_1396_p3() {
    s_7_39_fu_1396_p3 = (!sel_tmp13_fu_1325_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp13_fu_1325_p2.read()[0].to_bool())? grp_fu_1290_p2.read(): s_7_15_reg_691.read());
}

void sc_FIFO_DCT_DCT::thread_s_7_3_14_fu_1069_p3() {
    s_7_3_14_fu_1069_p3 = (!or_cond3_reg_1765.read()[0].is_01())? sc_lv<32>(): ((or_cond3_reg_1765.read()[0].to_bool())? s_7_2_12_reg_426.read(): newSel7_fu_1061_p3.read());
}

void sc_FIFO_DCT_DCT::thread_s_7_5_fu_961_p3() {
    s_7_5_fu_961_p3 = (!or_cond3_fu_947_p2.read()[0].is_01())? sc_lv<32>(): ((or_cond3_fu_947_p2.read()[0].to_bool())? s_7_4_reg_438.read(): newSel9_fu_953_p3.read());
}

void sc_FIFO_DCT_DCT::thread_s_7_7_fu_1089_p3() {
    s_7_7_fu_1089_p3 = (!or_cond3_reg_1765.read()[0].is_01())? sc_lv<32>(): ((or_cond3_reg_1765.read()[0].to_bool())? newSel5_fu_1082_p3.read(): s_7_6_reg_450.read());
}

void sc_FIFO_DCT_DCT::thread_s_7_9_fu_977_p3() {
    s_7_9_fu_977_p3 = (!or_cond_fu_935_p2.read()[0].is_01())? sc_lv<32>(): ((or_cond_fu_935_p2.read()[0].to_bool())? s_7_8_reg_462.read(): newSel8_fu_969_p3.read());
}

void sc_FIFO_DCT_DCT::thread_s_7_fu_1027_p3() {
    s_7_fu_1027_p3 = (!or_cond3_reg_1765.read()[0].is_01())? sc_lv<32>(): ((or_cond3_reg_1765.read()[0].to_bool())? s_7_3_reg_402.read(): newSel1_fu_1019_p3.read());
}

void sc_FIFO_DCT_DCT::thread_s_DCT() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state24.read()) && 
         !esl_seteq<1,1,1>(tmp_14_read_fu_214_p2.read(), ap_const_lv1_0))) {
        s_DCT =  (sc_logic) (ap_const_lv1_0[0]);
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state23.read()))) {
        s_DCT =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        s_DCT = sc_logic('X');
    }
}

void sc_FIFO_DCT_DCT::thread_s_DCT_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state23.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state24.read()) && 
          !esl_seteq<1,1,1>(tmp_14_read_fu_214_p2.read(), ap_const_lv1_0)))) {
        s_DCT_ap_vld = ap_const_logic_1;
    } else {
        s_DCT_ap_vld = ap_const_logic_0;
    }
}

void sc_FIFO_DCT_DCT::thread_s_working() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state23.read()))) {
        s_working =  (sc_logic) (ap_const_lv1_0[0]);
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
                !esl_seteq<1,1,1>(tmp_read_fu_178_p2.read(), ap_const_lv1_0))) {
        s_working =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        s_working = sc_logic('X');
    }
}

void sc_FIFO_DCT_DCT::thread_s_working_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
          !esl_seteq<1,1,1>(tmp_read_fu_178_p2.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state23.read())))) {
        s_working_ap_vld = ap_const_logic_1;
    } else {
        s_working_ap_vld = ap_const_logic_0;
    }
}

void sc_FIFO_DCT_DCT::thread_sc_FIFO_DCT_exec_cnt_o() {
    sc_FIFO_DCT_exec_cnt_o = (!sc_FIFO_DCT_exec_cnt_i.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(sc_FIFO_DCT_exec_cnt_i.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void sc_FIFO_DCT_DCT::thread_sc_FIFO_DCT_exec_cnt_o_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_CS_fsm_state4.read(), ap_const_lv1_1) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_747_p2.read()))) {
        sc_FIFO_DCT_exec_cnt_o_ap_vld = ap_const_logic_1;
    } else {
        sc_FIFO_DCT_exec_cnt_o_ap_vld = ap_const_logic_0;
    }
}

void sc_FIFO_DCT_DCT::thread_sc_FIFO_DCT_mA_address0() {
    sc_FIFO_DCT_mA_address0 =  (sc_lv<6>) (tmp_7_cast_fu_845_p1.read());
}

void sc_FIFO_DCT_DCT::thread_sc_FIFO_DCT_mA_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        sc_FIFO_DCT_mA_ce0 = ap_const_logic_1;
    } else {
        sc_FIFO_DCT_mA_ce0 = ap_const_logic_0;
    }
}

void sc_FIFO_DCT_DCT::thread_sc_FIFO_DCT_mB_address0() {
    sc_FIFO_DCT_mB_address0 =  (sc_lv<6>) (tmp_8_cast_fu_1491_p1.read());
}

void sc_FIFO_DCT_DCT::thread_sc_FIFO_DCT_mB_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()))) {
        sc_FIFO_DCT_mB_ce0 = ap_const_logic_1;
    } else {
        sc_FIFO_DCT_mB_ce0 = ap_const_logic_0;
    }
}

void sc_FIFO_DCT_DCT::thread_sc_FIFO_DCT_mB_d0() {
    sc_FIFO_DCT_mB_d0 = s_0_2_21_reg_1861.read();
}

void sc_FIFO_DCT_DCT::thread_sc_FIFO_DCT_mB_we0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read())))) {
        sc_FIFO_DCT_mB_we0 = ap_const_logic_1;
    } else {
        sc_FIFO_DCT_mB_we0 = ap_const_logic_0;
    }
}

void sc_FIFO_DCT_DCT::thread_sc_FIFO_DCT_mC_address0() {
    sc_FIFO_DCT_mC_address0 =  (sc_lv<6>) (tmp_16_cast_fu_1547_p1.read());
}

void sc_FIFO_DCT_DCT::thread_sc_FIFO_DCT_mC_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read()))) {
        sc_FIFO_DCT_mC_ce0 = ap_const_logic_1;
    } else {
        sc_FIFO_DCT_mC_ce0 = ap_const_logic_0;
    }
}

void sc_FIFO_DCT_DCT::thread_sc_FIFO_DCT_mC_d0() {
    sc_FIFO_DCT_mC_d0 = esl_sext<32,15>(tmp_15_fu_1536_p2.read());
}

void sc_FIFO_DCT_DCT::thread_sc_FIFO_DCT_mC_we0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state22.read())))) {
        sc_FIFO_DCT_mC_we0 = ap_const_logic_1;
    } else {
        sc_FIFO_DCT_mC_we0 = ap_const_logic_0;
    }
}

void sc_FIFO_DCT_DCT::thread_sel_tmp10_fu_1310_p2() {
    sel_tmp10_fu_1310_p2 = (!tmp_30_reg_1840.read().is_01() || !ap_const_lv3_3.is_01())? sc_lv<1>(): sc_lv<1>(tmp_30_reg_1840.read() == ap_const_lv3_3);
}

void sc_FIFO_DCT_DCT::thread_sel_tmp11_fu_1315_p2() {
    sel_tmp11_fu_1315_p2 = (!tmp_30_reg_1840.read().is_01() || !ap_const_lv3_2.is_01())? sc_lv<1>(): sc_lv<1>(tmp_30_reg_1840.read() == ap_const_lv3_2);
}

void sc_FIFO_DCT_DCT::thread_sel_tmp12_fu_1320_p2() {
    sel_tmp12_fu_1320_p2 = (!tmp_30_reg_1840.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_30_reg_1840.read() == ap_const_lv3_1);
}

void sc_FIFO_DCT_DCT::thread_sel_tmp13_fu_1325_p2() {
    sel_tmp13_fu_1325_p2 = (!tmp_30_reg_1840.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_30_reg_1840.read() == ap_const_lv3_0);
}

void sc_FIFO_DCT_DCT::thread_sel_tmp1_fu_925_p2() {
    sel_tmp1_fu_925_p2 = (!tmp_23_reg_1688.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<1>(): sc_lv<1>(tmp_23_reg_1688.read() == ap_const_lv3_1);
}

void sc_FIFO_DCT_DCT::thread_sel_tmp2_fu_905_p2() {
    sel_tmp2_fu_905_p2 = (!tmp_23_reg_1688.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(tmp_23_reg_1688.read() == ap_const_lv3_5);
}

void sc_FIFO_DCT_DCT::thread_sel_tmp3_fu_930_p2() {
    sel_tmp3_fu_930_p2 = (!tmp_23_reg_1688.read().is_01() || !ap_const_lv3_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_23_reg_1688.read() == ap_const_lv3_0);
}

void sc_FIFO_DCT_DCT::thread_sel_tmp4_fu_910_p2() {
    sel_tmp4_fu_910_p2 = (!tmp_23_reg_1688.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(tmp_23_reg_1688.read() == ap_const_lv3_4);
}

void sc_FIFO_DCT_DCT::thread_sel_tmp5_fu_1305_p2() {
    sel_tmp5_fu_1305_p2 = (!tmp_30_reg_1840.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(tmp_30_reg_1840.read() == ap_const_lv3_4);
}

void sc_FIFO_DCT_DCT::thread_sel_tmp6_fu_915_p2() {
    sel_tmp6_fu_915_p2 = (!tmp_23_reg_1688.read().is_01() || !ap_const_lv3_3.is_01())? sc_lv<1>(): sc_lv<1>(tmp_23_reg_1688.read() == ap_const_lv3_3);
}

void sc_FIFO_DCT_DCT::thread_sel_tmp7_fu_1295_p2() {
    sel_tmp7_fu_1295_p2 = (!tmp_30_reg_1840.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(tmp_30_reg_1840.read() == ap_const_lv3_6);
}

void sc_FIFO_DCT_DCT::thread_sel_tmp8_fu_920_p2() {
    sel_tmp8_fu_920_p2 = (!tmp_23_reg_1688.read().is_01() || !ap_const_lv3_2.is_01())? sc_lv<1>(): sc_lv<1>(tmp_23_reg_1688.read() == ap_const_lv3_2);
}

void sc_FIFO_DCT_DCT::thread_sel_tmp9_fu_1300_p2() {
    sel_tmp9_fu_1300_p2 = (!tmp_30_reg_1840.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<1>(): sc_lv<1>(tmp_30_reg_1840.read() == ap_const_lv3_5);
}

void sc_FIFO_DCT_DCT::thread_sel_tmp_fu_900_p2() {
    sel_tmp_fu_900_p2 = (!tmp_23_reg_1688.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(tmp_23_reg_1688.read() == ap_const_lv3_6);
}

void sc_FIFO_DCT_DCT::thread_tmp15_fu_850_p2() {
    tmp15_fu_850_p2 = (!s_7_2_12_reg_426.read().is_01() || !s_6_3_reg_414.read().is_01())? sc_lv<32>(): (sc_biguint<32>(s_7_2_12_reg_426.read()) + sc_biguint<32>(s_6_3_reg_414.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp16_fu_856_p2() {
    tmp16_fu_856_p2 = (!s_7_4_reg_438.read().is_01() || !s_7_6_reg_450.read().is_01())? sc_lv<32>(): (sc_biguint<32>(s_7_4_reg_438.read()) + sc_biguint<32>(s_7_6_reg_450.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp17_fu_862_p2() {
    tmp17_fu_862_p2 = (!tmp16_fu_856_p2.read().is_01() || !tmp15_fu_850_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp16_fu_856_p2.read()) + sc_biguint<32>(tmp15_fu_850_p2.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp18_fu_868_p2() {
    tmp18_fu_868_p2 = (!s_7_10_reg_486.read().is_01() || !s_7_8_reg_462.read().is_01())? sc_lv<32>(): (sc_biguint<32>(s_7_10_reg_486.read()) + sc_biguint<32>(s_7_8_reg_462.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp19_fu_874_p2() {
    tmp19_fu_874_p2 = (!s_7_27_reg_474.read().is_01() || !s_7_3_reg_402.read().is_01())? sc_lv<32>(): (sc_biguint<32>(s_7_27_reg_474.read()) + sc_biguint<32>(s_7_3_reg_402.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp20_fu_880_p2() {
    tmp20_fu_880_p2 = (!tmp19_fu_874_p2.read().is_01() || !tmp18_fu_868_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp19_fu_874_p2.read()) + sc_biguint<32>(tmp18_fu_868_p2.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp21_fu_1221_p2() {
    tmp21_fu_1221_p2 = (!s_7_32_reg_631.read().is_01() || !s_6_6_reg_619.read().is_01())? sc_lv<32>(): (sc_biguint<32>(s_7_32_reg_631.read()) + sc_biguint<32>(s_6_6_reg_619.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp22_fu_1227_p2() {
    tmp22_fu_1227_p2 = (!s_7_11_reg_643.read().is_01() || !s_7_12_reg_655.read().is_01())? sc_lv<32>(): (sc_biguint<32>(s_7_11_reg_643.read()) + sc_biguint<32>(s_7_12_reg_655.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp23_fu_1233_p2() {
    tmp23_fu_1233_p2 = (!tmp22_fu_1227_p2.read().is_01() || !tmp21_fu_1221_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp22_fu_1227_p2.read()) + sc_biguint<32>(tmp21_fu_1221_p2.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp24_fu_1239_p2() {
    tmp24_fu_1239_p2 = (!s_7_15_reg_691.read().is_01() || !s_7_13_reg_667.read().is_01())? sc_lv<32>(): (sc_biguint<32>(s_7_15_reg_691.read()) + sc_biguint<32>(s_7_13_reg_667.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp25_fu_1245_p2() {
    tmp25_fu_1245_p2 = (!s_7_14_reg_679.read().is_01() || !s_7_6_19_reg_607.read().is_01())? sc_lv<32>(): (sc_biguint<32>(s_7_14_reg_679.read()) + sc_biguint<32>(s_7_6_19_reg_607.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp26_fu_1251_p2() {
    tmp26_fu_1251_p2 = (!tmp25_fu_1245_p2.read().is_01() || !tmp24_fu_1239_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp25_fu_1245_p2.read()) + sc_biguint<32>(tmp24_fu_1239_p2.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp_10_cast_fu_1206_p1() {
    tmp_10_cast_fu_1206_p1 = esl_zext<32,6>(tmp_10_fu_1201_p2.read());
}

void sc_FIFO_DCT_DCT::thread_tmp_10_fu_1201_p2() {
    tmp_10_fu_1201_p2 = (!i0_cast_reg_1645.read().is_01() || !tmp_9_fu_1193_p3.read().is_01())? sc_lv<6>(): (sc_biguint<6>(i0_cast_reg_1645.read()) + sc_biguint<6>(tmp_9_fu_1193_p3.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp_11_cast_fu_1216_p1() {
    tmp_11_cast_fu_1216_p1 = esl_zext<32,6>(tmp_11_fu_1211_p2.read());
}

void sc_FIFO_DCT_DCT::thread_tmp_11_fu_1211_p2() {
    tmp_11_fu_1211_p2 = (!tmp_4_reg_1826.read().is_01() || !i2_2_cast_fu_1173_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_4_reg_1826.read()) + sc_biguint<6>(i2_2_cast_fu_1173_p1.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp_13_cast_fu_1532_p1() {
    tmp_13_cast_fu_1532_p1 = esl_sext<15,14>(tmp_13_fu_1524_p3.read());
}

void sc_FIFO_DCT_DCT::thread_tmp_13_fu_1524_p3() {
    tmp_13_fu_1524_p3 = (!tmp_29_fu_1495_p3.read()[0].is_01())? sc_lv<14>(): ((tmp_29_fu_1495_p3.read()[0].to_bool())? p_neg_t_fu_1505_p2.read(): p_lshr_f_cast_fu_1520_p1.read());
}

void sc_FIFO_DCT_DCT::thread_tmp_14_read_fu_214_p2() {
    tmp_14_read_fu_214_p2 =  (sc_lv<1>) (s_done.read());
}

void sc_FIFO_DCT_DCT::thread_tmp_15_fu_1536_p2() {
    tmp_15_fu_1536_p2 = (!tmp_13_cast_fu_1532_p1.read().is_01() || !ap_const_lv15_7F.is_01())? sc_lv<15>(): (sc_bigint<15>(tmp_13_cast_fu_1532_p1.read()) + sc_biguint<15>(ap_const_lv15_7F));
}

void sc_FIFO_DCT_DCT::thread_tmp_16_cast_fu_1547_p1() {
    tmp_16_cast_fu_1547_p1 = esl_zext<32,6>(tmp_16_reg_1879.read());
}

void sc_FIFO_DCT_DCT::thread_tmp_16_fu_1283_p2() {
    tmp_16_fu_1283_p2 = (!tmp_1_reg_1675.read().is_01() || !i1_1_cast_reg_1813.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_1_reg_1675.read()) + sc_biguint<6>(i1_1_cast_reg_1813.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp_1_fu_794_p3() {
    tmp_1_fu_794_p3 = esl_concat<3,3>(tmp_20_fu_790_p1.read(), ap_const_lv3_0);
}

void sc_FIFO_DCT_DCT::thread_tmp_20_fu_790_p1() {
    tmp_20_fu_790_p1 = i0_reg_299.read().range(3-1, 0);
}

void sc_FIFO_DCT_DCT::thread_tmp_21_fu_778_p1() {
    tmp_21_fu_778_p1 = i1_reg_391.read().range(3-1, 0);
}

void sc_FIFO_DCT_DCT::thread_tmp_22_fu_1121_p1() {
    tmp_22_fu_1121_p1 = i1_1_reg_596.read().range(3-1, 0);
}

void sc_FIFO_DCT_DCT::thread_tmp_23_fu_818_p1() {
    tmp_23_fu_818_p1 = i2_reg_497.read().range(3-1, 0);
}

void sc_FIFO_DCT_DCT::thread_tmp_25_fu_1511_p4() {
    tmp_25_fu_1511_p4 = s_0_2_21_reg_1861.read().range(31, 19);
}

void sc_FIFO_DCT_DCT::thread_tmp_29_fu_1495_p3() {
    tmp_29_fu_1495_p3 = s_0_2_21_reg_1861.read().range(31, 31);
}

void sc_FIFO_DCT_DCT::thread_tmp_2_fu_782_p3() {
    tmp_2_fu_782_p3 = esl_concat<3,3>(tmp_21_fu_778_p1.read(), ap_const_lv3_0);
}

void sc_FIFO_DCT_DCT::thread_tmp_30_fu_1189_p1() {
    tmp_30_fu_1189_p1 = i2_2_reg_702.read().range(3-1, 0);
}

void sc_FIFO_DCT_DCT::thread_tmp_3_cast_fu_1100_p1() {
    tmp_3_cast_fu_1100_p1 = esl_zext<32,6>(tmp_3_fu_1096_p2.read());
}

void sc_FIFO_DCT_DCT::thread_tmp_3_fu_1096_p2() {
    tmp_3_fu_1096_p2 = (!tmp_2_reg_1669.read().is_01() || !i0_cast_reg_1645.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_2_reg_1669.read()) + sc_biguint<6>(i0_cast_reg_1645.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp_4_fu_1125_p3() {
    tmp_4_fu_1125_p3 = esl_concat<3,3>(tmp_22_fu_1121_p1.read(), ap_const_lv3_0);
}

void sc_FIFO_DCT_DCT::thread_tmp_5_fu_822_p3() {
    tmp_5_fu_822_p3 = esl_concat<3,3>(tmp_23_fu_818_p1.read(), ap_const_lv3_0);
}

void sc_FIFO_DCT_DCT::thread_tmp_6_cast_fu_835_p1() {
    tmp_6_cast_fu_835_p1 = esl_zext<32,6>(tmp_6_fu_830_p2.read());
}

void sc_FIFO_DCT_DCT::thread_tmp_6_fu_830_p2() {
    tmp_6_fu_830_p2 = (!i0_cast_reg_1645.read().is_01() || !tmp_5_fu_822_p3.read().is_01())? sc_lv<6>(): (sc_biguint<6>(i0_cast_reg_1645.read()) + sc_biguint<6>(tmp_5_fu_822_p3.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp_7_cast_fu_845_p1() {
    tmp_7_cast_fu_845_p1 = esl_zext<32,6>(tmp_7_fu_840_p2.read());
}

void sc_FIFO_DCT_DCT::thread_tmp_7_fu_840_p2() {
    tmp_7_fu_840_p2 = (!tmp_2_reg_1669.read().is_01() || !i2_cast_fu_802_p1.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_2_reg_1669.read()) + sc_biguint<6>(i2_cast_fu_802_p1.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp_8_cast_fu_1491_p1() {
    tmp_8_cast_fu_1491_p1 = esl_zext<32,6>(tmp_8_reg_1869.read());
}

void sc_FIFO_DCT_DCT::thread_tmp_8_fu_1263_p2() {
    tmp_8_fu_1263_p2 = (!i0_cast_reg_1645.read().is_01() || !tmp_4_reg_1826.read().is_01())? sc_lv<6>(): (sc_biguint<6>(i0_cast_reg_1645.read()) + sc_biguint<6>(tmp_4_reg_1826.read()));
}

void sc_FIFO_DCT_DCT::thread_tmp_9_fu_1193_p3() {
    tmp_9_fu_1193_p3 = esl_concat<3,3>(tmp_30_fu_1189_p1.read(), ap_const_lv3_0);
}

void sc_FIFO_DCT_DCT::thread_tmp_read_fu_178_p2() {
    tmp_read_fu_178_p2 =  (sc_lv<1>) (s_buffered.read());
}

void sc_FIFO_DCT_DCT::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            if (!esl_seteq<1,1,1>(tmp_read_fu_178_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 8 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_747_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state23;
            }
            break;
        case 16 : 
            if (!esl_seteq<1,1,1>(exitcond2_fu_766_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_806_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 8192 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_1109_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state15;
            }
            break;
        case 16384 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_fu_1177_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state22;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            if (!esl_seteq<1,1,1>(tmp_14_read_fu_214_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_fsm_state25;
            } else {
                ap_NS_fsm = ap_ST_fsm_state24;
            }
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<25>) ("XXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

