// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __sc_FIFO_DCT_Prc2_b_H__
#define __sc_FIFO_DCT_Prc2_b_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct sc_FIFO_DCT_Prc2_b_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 8;
  static const unsigned AddressRange = 64;
  static const unsigned AddressWidth = 6;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(sc_FIFO_DCT_Prc2_b_ram) {
        for (unsigned i = 0; i < 8 ; i = i + 1) {
            ram[i] = "0b01011010";
        }
        ram[8] = "0b01111101";
        ram[9] = "0b01101010";
        ram[10] = "0b01000111";
        ram[11] = "0b00011000";
        ram[12] = "0b11101000";
        ram[13] = "0b10111001";
        ram[14] = "0b10010110";
        ram[15] = "0b10000011";
        ram[16] = "0b01110110";
        ram[17] = "0b00110000";
        ram[18] = "0b11010000";
        ram[19] = "0b10001010";
        ram[20] = "0b10001010";
        ram[21] = "0b11010000";
        ram[22] = "0b00110000";
        ram[23] = "0b01110110";
        ram[24] = "0b01101010";
        ram[25] = "0b11101000";
        ram[26] = "0b10000011";
        ram[27] = "0b10111001";
        ram[28] = "0b01000111";
        ram[29] = "0b01111101";
        ram[30] = "0b00011000";
        ram[31] = "0b10010110";
        ram[32] = "0b01011010";
        ram[33] = "0b10100110";
        ram[34] = "0b10100110";
        ram[35] = "0b01011010";
        ram[36] = "0b01011010";
        ram[37] = "0b10100110";
        ram[38] = "0b10100110";
        ram[39] = "0b01011010";
        ram[40] = "0b01000111";
        ram[41] = "0b10000011";
        ram[42] = "0b00011000";
        ram[43] = "0b01101010";
        ram[44] = "0b10010110";
        ram[45] = "0b11101000";
        ram[46] = "0b01111101";
        ram[47] = "0b10111001";
        ram[48] = "0b00110000";
        ram[49] = "0b10001010";
        ram[50] = "0b01110110";
        ram[51] = "0b11010000";
        ram[52] = "0b11010000";
        ram[53] = "0b01110110";
        ram[54] = "0b10001010";
        ram[55] = "0b00110000";
        ram[56] = "0b00011000";
        ram[57] = "0b10111001";
        ram[58] = "0b01101010";
        ram[59] = "0b10000011";
        ram[60] = "0b01111101";
        ram[61] = "0b10010110";
        ram[62] = "0b01000111";
        ram[63] = "0b11101000";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(sc_FIFO_DCT_Prc2_b) {


static const unsigned DataWidth = 8;
static const unsigned AddressRange = 64;
static const unsigned AddressWidth = 6;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_FIFO_DCT_Prc2_b_ram* meminst;


SC_CTOR(sc_FIFO_DCT_Prc2_b) {
meminst = new sc_FIFO_DCT_Prc2_b_ram("sc_FIFO_DCT_Prc2_b_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~sc_FIFO_DCT_Prc2_b() {
    delete meminst;
}


};//endmodule
#endif
