// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _sc_FIFO_DCT_Prc2_HH_
#define _sc_FIFO_DCT_Prc2_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "sc_FIFO_DCT_mac_mcud.h"
#include "sc_FIFO_DCT_mac_mdEe.h"
#include "sc_FIFO_DCT_Prc2_bkb.h"
#include "sc_FIFO_DCT_Prc2_b.h"
#include "sc_FIFO_DCT_Prc2_a.h"

namespace ap_rtl {

struct sc_FIFO_DCT_Prc2 : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_out< sc_logic > data_ok;
    sc_out< sc_logic > data_ok_ap_vld;
    sc_out< sc_logic > done;
    sc_out< sc_logic > done_ap_vld;
    sc_out< sc_lv<8> > dout;
    sc_out< sc_logic > dout_ap_vld;
    sc_in< sc_logic > s_start_i;
    sc_out< sc_logic > s_start_o;
    sc_out< sc_logic > s_start_o_ap_vld;
    sc_out< sc_logic > s_working;
    sc_out< sc_logic > s_working_ap_vld;
    sc_out< sc_lv<6> > sc_FIFO_DCT_mA_V_address0;
    sc_out< sc_logic > sc_FIFO_DCT_mA_V_ce0;
    sc_in< sc_lv<18> > sc_FIFO_DCT_mA_V_q0;
    sc_out< sc_lv<6> > sc_FIFO_DCT_mB_V_address0;
    sc_out< sc_logic > sc_FIFO_DCT_mB_V_ce0;
    sc_out< sc_logic > sc_FIFO_DCT_mB_V_we0;
    sc_out< sc_lv<18> > sc_FIFO_DCT_mB_V_d0;


    // Module declarations
    sc_FIFO_DCT_Prc2(sc_module_name name);
    SC_HAS_PROCESS(sc_FIFO_DCT_Prc2);

    ~sc_FIFO_DCT_Prc2();

    sc_trace_file* mVcdFile;

    sc_FIFO_DCT_Prc2_bkb* b_a_U;
    sc_FIFO_DCT_Prc2_b* b_U;
    sc_FIFO_DCT_Prc2_a* a_U;
    sc_FIFO_DCT_mac_mcud<1,1,8,18,32,32>* sc_FIFO_DCT_mac_mcud_U6;
    sc_FIFO_DCT_mac_mdEe<1,1,18,8,18,18>* sc_FIFO_DCT_mac_mdEe_U7;
    sc_signal< sc_lv<6> > b_a_address0;
    sc_signal< sc_logic > b_a_ce0;
    sc_signal< sc_lv<8> > b_a_q0;
    sc_signal< sc_lv<6> > b_address0;
    sc_signal< sc_logic > b_ce0;
    sc_signal< sc_lv<8> > b_q0;
    sc_signal< sc_lv<6> > i0_cast5_fu_316_p1;
    sc_signal< sc_lv<6> > i0_cast5_reg_524;
    sc_signal< sc_lv<14> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state4;
    sc_signal< sc_lv<4> > i0_1_fu_326_p2;
    sc_signal< sc_lv<4> > i0_1_reg_535;
    sc_signal< sc_lv<4> > i1_2_fu_338_p2;
    sc_signal< sc_lv<4> > i1_2_reg_543;
    sc_signal< sc_lv<1> > ap_CS_fsm_state5;
    sc_signal< sc_lv<6> > tmp_1_fu_348_p3;
    sc_signal< sc_lv<6> > tmp_1_reg_548;
    sc_signal< sc_lv<1> > exitcond2_fu_332_p2;
    sc_signal< sc_lv<6> > a_addr_reg_553;
    sc_signal< sc_lv<4> > i2_2_fu_376_p2;
    sc_signal< sc_lv<4> > i2_2_reg_561;
    sc_signal< sc_lv<1> > ap_CS_fsm_state6;
    sc_signal< sc_lv<1> > exitcond4_fu_370_p2;
    sc_signal< sc_lv<8> > b_a_load_reg_576;
    sc_signal< sc_lv<1> > ap_CS_fsm_state7;
    sc_signal< sc_lv<18> > sc_FIFO_DCT_mA_V_loa_reg_581;
    sc_signal< sc_lv<32> > grp_fu_509_p3;
    sc_signal< sc_lv<1> > ap_CS_fsm_state8;
    sc_signal< sc_lv<4> > i1_3_fu_426_p2;
    sc_signal< sc_lv<4> > i1_3_reg_594;
    sc_signal< sc_lv<1> > ap_CS_fsm_state9;
    sc_signal< sc_lv<6> > tmp_4_fu_436_p3;
    sc_signal< sc_lv<6> > tmp_4_reg_599;
    sc_signal< sc_lv<1> > exitcond3_fu_420_p2;
    sc_signal< sc_lv<6> > sc_FIFO_DCT_mB_V_add_reg_604;
    sc_signal< sc_lv<4> > i2_3_fu_464_p2;
    sc_signal< sc_lv<4> > i2_3_reg_612;
    sc_signal< sc_lv<1> > ap_CS_fsm_state10;
    sc_signal< sc_lv<1> > exitcond_fu_458_p2;
    sc_signal< sc_lv<8> > b_load_reg_627;
    sc_signal< sc_lv<1> > ap_CS_fsm_state11;
    sc_signal< sc_lv<18> > tmp_20_fu_502_p1;
    sc_signal< sc_lv<18> > tmp_20_reg_632;
    sc_signal< sc_lv<18> > grp_fu_517_p3;
    sc_signal< sc_lv<1> > ap_CS_fsm_state12;
    sc_signal< sc_lv<6> > a_address0;
    sc_signal< sc_logic > a_ce0;
    sc_signal< sc_logic > a_we0;
    sc_signal< sc_lv<32> > a_q0;
    sc_signal< sc_lv<4> > i0_reg_229;
    sc_signal< sc_lv<1> > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > tmp_read_fu_124_p2;
    sc_signal< sc_lv<4> > i1_reg_240;
    sc_signal< sc_lv<1> > exitcond1_fu_320_p2;
    sc_signal< sc_lv<32> > a_load_reg_251;
    sc_signal< sc_lv<4> > i2_reg_264;
    sc_signal< sc_lv<4> > i1_1_reg_275;
    sc_signal< sc_lv<1> > ap_CS_fsm_state13;
    sc_signal< sc_lv<18> > sc_FIFO_DCT_mB_V_loa_reg_286;
    sc_signal< sc_lv<4> > i2_1_reg_299;
    sc_signal< sc_lv<32> > tmp_2_cast_fu_361_p1;
    sc_signal< sc_lv<32> > tmp_6_cast_fu_399_p1;
    sc_signal< sc_lv<32> > tmp_9_cast_fu_409_p1;
    sc_signal< sc_lv<32> > tmp_5_cast_fu_449_p1;
    sc_signal< sc_lv<32> > tmp_12_cast_fu_487_p1;
    sc_signal< sc_lv<32> > tmp_13_cast_fu_497_p1;
    sc_signal< sc_lv<3> > tmp_16_fu_344_p1;
    sc_signal< sc_lv<6> > tmp_2_fu_356_p2;
    sc_signal< sc_lv<3> > tmp_18_fu_382_p1;
    sc_signal< sc_lv<6> > tmp_3_fu_386_p3;
    sc_signal< sc_lv<6> > tmp_6_fu_394_p2;
    sc_signal< sc_lv<6> > i2_cast3_fu_366_p1;
    sc_signal< sc_lv<6> > tmp_9_fu_404_p2;
    sc_signal< sc_lv<3> > tmp_17_fu_432_p1;
    sc_signal< sc_lv<6> > tmp_5_fu_444_p2;
    sc_signal< sc_lv<3> > tmp_19_fu_470_p1;
    sc_signal< sc_lv<6> > tmp_10_fu_474_p3;
    sc_signal< sc_lv<6> > tmp_11_fu_482_p2;
    sc_signal< sc_lv<6> > i2_1_cast1_fu_454_p1;
    sc_signal< sc_lv<6> > tmp_12_fu_492_p2;
    sc_signal< sc_lv<18> > grp_fu_509_p1;
    sc_signal< sc_lv<14> > ap_NS_fsm;
    sc_signal< sc_lv<26> > grp_fu_509_p10;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<14> ap_ST_fsm_state1;
    static const sc_lv<14> ap_ST_fsm_state2;
    static const sc_lv<14> ap_ST_fsm_state3;
    static const sc_lv<14> ap_ST_fsm_state4;
    static const sc_lv<14> ap_ST_fsm_state5;
    static const sc_lv<14> ap_ST_fsm_state6;
    static const sc_lv<14> ap_ST_fsm_state7;
    static const sc_lv<14> ap_ST_fsm_state8;
    static const sc_lv<14> ap_ST_fsm_state9;
    static const sc_lv<14> ap_ST_fsm_state10;
    static const sc_lv<14> ap_ST_fsm_state11;
    static const sc_lv<14> ap_ST_fsm_state12;
    static const sc_lv<14> ap_ST_fsm_state13;
    static const sc_lv<14> ap_ST_fsm_state14;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<18> ap_const_lv18_0;
    static const sc_lv<8> ap_const_lv8_7F;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<3> ap_const_lv3_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_a_address0();
    void thread_a_ce0();
    void thread_a_we0();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_b_a_address0();
    void thread_b_a_ce0();
    void thread_b_address0();
    void thread_b_ce0();
    void thread_data_ok();
    void thread_data_ok_ap_vld();
    void thread_done();
    void thread_done_ap_vld();
    void thread_dout();
    void thread_dout_ap_vld();
    void thread_exitcond1_fu_320_p2();
    void thread_exitcond2_fu_332_p2();
    void thread_exitcond3_fu_420_p2();
    void thread_exitcond4_fu_370_p2();
    void thread_exitcond_fu_458_p2();
    void thread_grp_fu_509_p1();
    void thread_grp_fu_509_p10();
    void thread_i0_1_fu_326_p2();
    void thread_i0_cast5_fu_316_p1();
    void thread_i1_2_fu_338_p2();
    void thread_i1_3_fu_426_p2();
    void thread_i2_1_cast1_fu_454_p1();
    void thread_i2_2_fu_376_p2();
    void thread_i2_3_fu_464_p2();
    void thread_i2_cast3_fu_366_p1();
    void thread_s_start_o();
    void thread_s_start_o_ap_vld();
    void thread_s_working();
    void thread_s_working_ap_vld();
    void thread_sc_FIFO_DCT_mA_V_address0();
    void thread_sc_FIFO_DCT_mA_V_ce0();
    void thread_sc_FIFO_DCT_mB_V_address0();
    void thread_sc_FIFO_DCT_mB_V_ce0();
    void thread_sc_FIFO_DCT_mB_V_d0();
    void thread_sc_FIFO_DCT_mB_V_we0();
    void thread_tmp_10_fu_474_p3();
    void thread_tmp_11_fu_482_p2();
    void thread_tmp_12_cast_fu_487_p1();
    void thread_tmp_12_fu_492_p2();
    void thread_tmp_13_cast_fu_497_p1();
    void thread_tmp_16_fu_344_p1();
    void thread_tmp_17_fu_432_p1();
    void thread_tmp_18_fu_382_p1();
    void thread_tmp_19_fu_470_p1();
    void thread_tmp_1_fu_348_p3();
    void thread_tmp_20_fu_502_p1();
    void thread_tmp_2_cast_fu_361_p1();
    void thread_tmp_2_fu_356_p2();
    void thread_tmp_3_fu_386_p3();
    void thread_tmp_4_fu_436_p3();
    void thread_tmp_5_cast_fu_449_p1();
    void thread_tmp_5_fu_444_p2();
    void thread_tmp_6_cast_fu_399_p1();
    void thread_tmp_6_fu_394_p2();
    void thread_tmp_9_cast_fu_409_p1();
    void thread_tmp_9_fu_404_p2();
    void thread_tmp_read_fu_124_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
