// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sc_FIFO_DCT_DCT (
        ap_clk,
        ap_rst,
        sc_FIFO_DCT_mA_address0,
        sc_FIFO_DCT_mA_ce0,
        sc_FIFO_DCT_mA_q0,
        sc_FIFO_DCT_mB_address0,
        sc_FIFO_DCT_mB_ce0,
        sc_FIFO_DCT_mB_we0,
        sc_FIFO_DCT_mB_d0,
        sc_FIFO_DCT_mC_address0,
        sc_FIFO_DCT_mC_ce0,
        sc_FIFO_DCT_mC_we0,
        sc_FIFO_DCT_mC_d0,
        sc_FIFO_DCT_exec_cnt_i,
        sc_FIFO_DCT_exec_cnt_o,
        sc_FIFO_DCT_exec_cnt_o_ap_vld,
        s_buffered,
        s_working,
        s_working_ap_vld,
        s_DCT,
        s_DCT_ap_vld,
        s_done
);

parameter    ap_ST_fsm_state1 = 25'b1;
parameter    ap_ST_fsm_state2 = 25'b10;
parameter    ap_ST_fsm_state3 = 25'b100;
parameter    ap_ST_fsm_state4 = 25'b1000;
parameter    ap_ST_fsm_state5 = 25'b10000;
parameter    ap_ST_fsm_state6 = 25'b100000;
parameter    ap_ST_fsm_state7 = 25'b1000000;
parameter    ap_ST_fsm_state8 = 25'b10000000;
parameter    ap_ST_fsm_state9 = 25'b100000000;
parameter    ap_ST_fsm_state10 = 25'b1000000000;
parameter    ap_ST_fsm_state11 = 25'b10000000000;
parameter    ap_ST_fsm_state12 = 25'b100000000000;
parameter    ap_ST_fsm_state13 = 25'b1000000000000;
parameter    ap_ST_fsm_state14 = 25'b10000000000000;
parameter    ap_ST_fsm_state15 = 25'b100000000000000;
parameter    ap_ST_fsm_state16 = 25'b1000000000000000;
parameter    ap_ST_fsm_state17 = 25'b10000000000000000;
parameter    ap_ST_fsm_state18 = 25'b100000000000000000;
parameter    ap_ST_fsm_state19 = 25'b1000000000000000000;
parameter    ap_ST_fsm_state20 = 25'b10000000000000000000;
parameter    ap_ST_fsm_state21 = 25'b100000000000000000000;
parameter    ap_ST_fsm_state22 = 25'b1000000000000000000000;
parameter    ap_ST_fsm_state23 = 25'b10000000000000000000000;
parameter    ap_ST_fsm_state24 = 25'b100000000000000000000000;
parameter    ap_ST_fsm_state25 = 25'b1000000000000000000000000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv32_10 = 32'b10000;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv32_14 = 32'b10100;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv32_16 = 32'b10110;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv4_8 = 4'b1000;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv3_6 = 3'b110;
parameter    ap_const_lv3_5 = 3'b101;
parameter    ap_const_lv3_4 = 3'b100;
parameter    ap_const_lv3_3 = 3'b11;
parameter    ap_const_lv3_2 = 3'b10;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv32_1F = 32'b11111;
parameter    ap_const_lv14_0 = 14'b00000000000000;
parameter    ap_const_lv15_7F = 15'b1111111;

input   ap_clk;
input   ap_rst;
output  [5:0] sc_FIFO_DCT_mA_address0;
output   sc_FIFO_DCT_mA_ce0;
input  [31:0] sc_FIFO_DCT_mA_q0;
output  [5:0] sc_FIFO_DCT_mB_address0;
output   sc_FIFO_DCT_mB_ce0;
output   sc_FIFO_DCT_mB_we0;
output  [31:0] sc_FIFO_DCT_mB_d0;
output  [5:0] sc_FIFO_DCT_mC_address0;
output   sc_FIFO_DCT_mC_ce0;
output   sc_FIFO_DCT_mC_we0;
output  [31:0] sc_FIFO_DCT_mC_d0;
input  [31:0] sc_FIFO_DCT_exec_cnt_i;
output  [31:0] sc_FIFO_DCT_exec_cnt_o;
output   sc_FIFO_DCT_exec_cnt_o_ap_vld;
input   s_buffered;
output   s_working;
output   s_working_ap_vld;
output   s_DCT;
output   s_DCT_ap_vld;
input   s_done;

reg sc_FIFO_DCT_mA_ce0;
reg sc_FIFO_DCT_mB_ce0;
reg sc_FIFO_DCT_mB_we0;
reg sc_FIFO_DCT_mC_ce0;
reg sc_FIFO_DCT_mC_we0;
reg sc_FIFO_DCT_exec_cnt_o_ap_vld;
reg s_working;
reg s_working_ap_vld;
reg s_DCT;
reg s_DCT_ap_vld;

wire   [5:0] b_a_address0;
reg    b_a_ce0;
wire   [7:0] b_a_q0;
wire   [5:0] b_address0;
reg    b_ce0;
wire   [7:0] b_q0;
(* fsm_encoding = "none" *) reg   [24:0] ap_CS_fsm;
wire   [0:0] ap_CS_fsm_state4;
wire   [5:0] i0_cast_fu_743_p1;
reg   [5:0] i0_cast_reg_1645;
wire   [3:0] i0_1_fu_753_p2;
reg   [3:0] i0_1_reg_1656;
wire   [3:0] i1_2_fu_772_p2;
reg   [3:0] i1_2_reg_1664;
wire   [0:0] ap_CS_fsm_state5;
wire   [5:0] tmp_2_fu_782_p3;
reg   [5:0] tmp_2_reg_1669;
wire   [0:0] exitcond2_fu_766_p2;
wire   [5:0] tmp_1_fu_794_p3;
reg   [5:0] tmp_1_reg_1675;
wire   [3:0] i2_1_fu_812_p2;
reg   [3:0] i2_1_reg_1683;
wire   [0:0] ap_CS_fsm_state6;
wire   [2:0] tmp_23_fu_818_p1;
reg   [2:0] tmp_23_reg_1688;
wire   [0:0] exitcond4_fu_806_p2;
wire   [31:0] s_0_fu_886_p2;
reg   [31:0] s_0_reg_1709;
reg  signed [7:0] b_a_load_reg_1715;
wire   [0:0] ap_CS_fsm_state7;
reg  signed [31:0] sc_FIFO_DCT_mA_load_reg_1720;
wire   [0:0] ap_CS_fsm_state8;
wire   [31:0] grp_fu_895_p2;
reg   [31:0] s_0_5_reg_1730;
wire   [0:0] ap_CS_fsm_state11;
wire   [0:0] sel_tmp_fu_900_p2;
reg   [0:0] sel_tmp_reg_1738;
wire   [0:0] sel_tmp2_fu_905_p2;
reg   [0:0] sel_tmp2_reg_1744;
wire   [0:0] sel_tmp4_fu_910_p2;
reg   [0:0] sel_tmp4_reg_1749;
wire   [0:0] sel_tmp8_fu_920_p2;
reg   [0:0] sel_tmp8_reg_1755;
wire   [0:0] or_cond_fu_935_p2;
reg   [0:0] or_cond_reg_1760;
wire   [0:0] or_cond3_fu_947_p2;
reg   [0:0] or_cond3_reg_1765;
wire   [31:0] s_7_5_fu_961_p3;
reg   [31:0] s_7_5_reg_1773;
wire   [31:0] s_7_9_fu_977_p3;
reg   [31:0] s_7_9_reg_1778;
wire   [31:0] s_7_29_fu_993_p3;
reg   [31:0] s_7_29_reg_1783;
wire   [31:0] s_7_30_fu_1001_p3;
reg   [31:0] s_7_30_reg_1788;
wire   [31:0] s_7_fu_1027_p3;
wire   [0:0] ap_CS_fsm_state12;
wire   [31:0] s_7_1_fu_1048_p3;
wire   [31:0] s_7_3_14_fu_1069_p3;
wire   [31:0] s_7_7_fu_1089_p3;
wire   [5:0] i1_1_cast_fu_1105_p1;
reg   [5:0] i1_1_cast_reg_1813;
wire   [0:0] ap_CS_fsm_state14;
wire   [3:0] i1_3_fu_1115_p2;
reg   [3:0] i1_3_reg_1821;
wire   [5:0] tmp_4_fu_1125_p3;
reg   [5:0] tmp_4_reg_1826;
wire   [0:0] exitcond3_fu_1109_p2;
wire   [3:0] i2_3_fu_1183_p2;
reg   [3:0] i2_3_reg_1835;
wire   [0:0] ap_CS_fsm_state15;
wire   [2:0] tmp_30_fu_1189_p1;
reg   [2:0] tmp_30_reg_1840;
wire   [0:0] exitcond5_fu_1177_p2;
wire   [31:0] s_0_2_21_fu_1257_p2;
reg   [31:0] s_0_2_21_reg_1861;
wire   [5:0] tmp_8_fu_1263_p2;
reg   [5:0] tmp_8_reg_1869;
reg   [12:0] tmp_24_reg_1874;
wire   [5:0] tmp_16_fu_1283_p2;
reg   [5:0] tmp_16_reg_1879;
wire   [31:0] a_q0;
reg  signed [31:0] a_load_reg_1884;
wire   [0:0] ap_CS_fsm_state16;
reg  signed [7:0] b_load_reg_1889;
wire   [0:0] ap_CS_fsm_state17;
wire   [31:0] grp_fu_1290_p2;
reg   [31:0] s_0_6_reg_1899;
wire   [0:0] ap_CS_fsm_state20;
wire   [0:0] sel_tmp7_fu_1295_p2;
reg   [0:0] sel_tmp7_reg_1907;
wire   [0:0] sel_tmp9_fu_1300_p2;
reg   [0:0] sel_tmp9_reg_1913;
wire   [0:0] sel_tmp5_fu_1305_p2;
reg   [0:0] sel_tmp5_reg_1918;
wire   [0:0] sel_tmp11_fu_1315_p2;
reg   [0:0] sel_tmp11_reg_1924;
wire   [0:0] or_cond4_fu_1330_p2;
reg   [0:0] or_cond4_reg_1929;
wire   [0:0] or_cond7_fu_1342_p2;
reg   [0:0] or_cond7_reg_1934;
wire   [31:0] s_7_34_fu_1356_p3;
reg   [31:0] s_7_34_reg_1942;
wire   [31:0] s_7_36_fu_1372_p3;
reg   [31:0] s_7_36_reg_1947;
wire   [31:0] s_7_38_fu_1388_p3;
reg   [31:0] s_7_38_reg_1952;
wire   [31:0] s_7_39_fu_1396_p3;
reg   [31:0] s_7_39_reg_1957;
wire   [31:0] s_7_16_fu_1422_p3;
wire   [0:0] ap_CS_fsm_state21;
wire   [31:0] s_7_17_fu_1443_p3;
wire   [31:0] s_7_33_fu_1464_p3;
wire   [31:0] s_7_35_fu_1484_p3;
reg   [5:0] a_address0;
reg    a_ce0;
reg    a_we0;
reg   [3:0] i0_reg_299;
wire   [0:0] ap_CS_fsm_state3;
wire   [0:0] tmp_read_fu_178_p2;
reg   [31:0] s_7_2_reg_311;
wire   [0:0] exitcond1_fu_747_p2;
reg   [31:0] s_7_3_reg_402;
wire   [0:0] ap_CS_fsm_state13;
reg   [31:0] s_6_2_reg_321;
reg   [31:0] s_6_3_reg_414;
reg   [31:0] s_5_2_reg_331;
reg   [31:0] s_7_2_12_reg_426;
reg   [31:0] s_4_2_reg_341;
reg   [31:0] s_7_4_reg_438;
reg   [31:0] s_3_2_reg_351;
reg   [31:0] s_7_6_reg_450;
reg   [31:0] s_2_2_reg_361;
reg   [31:0] s_7_8_reg_462;
reg   [31:0] s_1_2_reg_371;
reg   [31:0] s_7_27_reg_474;
reg   [31:0] s_0_2_reg_381;
reg   [3:0] i1_reg_391;
reg   [31:0] s_7_10_reg_486;
reg   [3:0] i2_reg_497;
reg   [31:0] s_7_5_16_reg_508;
reg   [31:0] s_7_6_19_reg_607;
wire   [0:0] ap_CS_fsm_state22;
reg   [31:0] s_6_5_reg_519;
reg   [31:0] s_6_6_reg_619;
reg   [31:0] s_5_5_reg_530;
reg   [31:0] s_7_32_reg_631;
reg   [31:0] s_4_5_reg_541;
reg   [31:0] s_7_11_reg_643;
reg   [31:0] s_3_5_reg_552;
reg   [31:0] s_7_12_reg_655;
reg   [31:0] s_2_5_reg_563;
reg   [31:0] s_7_13_reg_667;
reg   [31:0] s_1_5_reg_574;
reg   [31:0] s_7_14_reg_679;
reg   [31:0] s_0_5_17_reg_585;
reg   [3:0] i1_1_reg_596;
reg   [31:0] s_7_15_reg_691;
reg   [3:0] i2_2_reg_702;
wire   [31:0] tmp_6_cast_fu_835_p1;
wire   [31:0] tmp_7_cast_fu_845_p1;
wire   [31:0] tmp_3_cast_fu_1100_p1;
wire   [31:0] tmp_10_cast_fu_1206_p1;
wire   [31:0] tmp_11_cast_fu_1216_p1;
wire   [31:0] tmp_8_cast_fu_1491_p1;
wire   [31:0] tmp_16_cast_fu_1547_p1;
reg   [31:0] s_0_1_fu_142;
reg   [31:0] s_7_19_fu_146;
reg   [31:0] s_7_20_fu_150;
reg   [31:0] s_7_21_fu_154;
reg   [31:0] s_7_22_fu_158;
reg   [31:0] s_7_23_fu_162;
reg   [31:0] s_7_24_fu_166;
reg   [31:0] s_7_25_fu_170;
wire   [0:0] ap_CS_fsm_state23;
wire   [0:0] ap_CS_fsm_state24;
wire   [0:0] tmp_14_read_fu_214_p2;
wire   [2:0] tmp_21_fu_778_p1;
wire   [2:0] tmp_20_fu_790_p1;
wire   [5:0] tmp_5_fu_822_p3;
wire   [5:0] tmp_6_fu_830_p2;
wire   [5:0] i2_cast_fu_802_p1;
wire   [5:0] tmp_7_fu_840_p2;
wire   [31:0] tmp16_fu_856_p2;
wire   [31:0] tmp15_fu_850_p2;
wire   [31:0] tmp19_fu_874_p2;
wire   [31:0] tmp18_fu_868_p2;
wire   [31:0] tmp20_fu_880_p2;
wire   [31:0] tmp17_fu_862_p2;
wire   [0:0] sel_tmp3_fu_930_p2;
wire   [0:0] sel_tmp1_fu_925_p2;
wire   [0:0] sel_tmp6_fu_915_p2;
wire   [0:0] or_cond1_fu_941_p2;
wire   [31:0] newSel9_fu_953_p3;
wire   [31:0] newSel8_fu_969_p3;
wire   [31:0] s_7_28_fu_985_p3;
wire   [0:0] or_cond2_fu_1009_p2;
wire   [31:0] newSel_fu_1013_p3;
wire   [31:0] newSel1_fu_1019_p3;
wire   [31:0] newSel3_fu_1034_p3;
wire   [31:0] newSel4_fu_1040_p3;
wire   [31:0] newSel6_fu_1055_p3;
wire   [31:0] newSel7_fu_1061_p3;
wire   [31:0] newSel2_fu_1076_p3;
wire   [31:0] newSel5_fu_1082_p3;
wire   [5:0] tmp_3_fu_1096_p2;
wire   [2:0] tmp_22_fu_1121_p1;
wire   [5:0] tmp_9_fu_1193_p3;
wire   [5:0] tmp_10_fu_1201_p2;
wire   [5:0] i2_2_cast_fu_1173_p1;
wire   [5:0] tmp_11_fu_1211_p2;
wire   [31:0] tmp22_fu_1227_p2;
wire   [31:0] tmp21_fu_1221_p2;
wire   [31:0] tmp25_fu_1245_p2;
wire   [31:0] tmp24_fu_1239_p2;
wire   [31:0] tmp26_fu_1251_p2;
wire   [31:0] tmp23_fu_1233_p2;
wire   [31:0] p_neg_fu_1267_p2;
wire   [0:0] sel_tmp13_fu_1325_p2;
wire   [0:0] sel_tmp12_fu_1320_p2;
wire   [0:0] sel_tmp10_fu_1310_p2;
wire   [0:0] or_cond5_fu_1336_p2;
wire   [31:0] newSel16_fu_1348_p3;
wire   [31:0] newSel19_fu_1364_p3;
wire   [31:0] s_7_37_fu_1380_p3;
wire   [0:0] or_cond6_fu_1404_p2;
wire   [31:0] newSel10_fu_1408_p3;
wire   [31:0] newSel11_fu_1414_p3;
wire   [31:0] newSel12_fu_1429_p3;
wire   [31:0] newSel13_fu_1435_p3;
wire   [31:0] newSel14_fu_1450_p3;
wire   [31:0] newSel15_fu_1456_p3;
wire   [31:0] newSel17_fu_1471_p3;
wire   [31:0] newSel18_fu_1477_p3;
wire   [13:0] p_lshr_cast_fu_1502_p1;
wire   [12:0] tmp_25_fu_1511_p4;
wire   [0:0] tmp_29_fu_1495_p3;
wire   [13:0] p_neg_t_fu_1505_p2;
wire   [13:0] p_lshr_f_cast_fu_1520_p1;
wire   [13:0] tmp_13_fu_1524_p3;
wire  signed [14:0] tmp_13_cast_fu_1532_p1;
wire   [14:0] tmp_15_fu_1536_p2;
reg   [24:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 25'b1;
end

sc_FIFO_DCT_DCT_b_a #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
b_a_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b_a_address0),
    .ce0(b_a_ce0),
    .q0(b_a_q0)
);

sc_FIFO_DCT_DCT_b #(
    .DataWidth( 8 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
b_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b_address0),
    .ce0(b_ce0),
    .q0(b_q0)
);

sc_FIFO_DCT_DCT_a #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
a_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(a_address0),
    .ce0(a_ce0),
    .we0(a_we0),
    .d0(s_0_reg_1709),
    .q0(a_q0)
);

sc_FIFO_DCT_mul_8bkb #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
sc_FIFO_DCT_mul_8bkb_U0(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(b_a_load_reg_1715),
    .din1(sc_FIFO_DCT_mA_load_reg_1720),
    .ce(1'b1),
    .dout(grp_fu_895_p2)
);

sc_FIFO_DCT_mul_3cud #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
sc_FIFO_DCT_mul_3cud_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(a_load_reg_1884),
    .din1(b_load_reg_1889),
    .ce(1'b1),
    .dout(grp_fu_1290_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & ~(1'b0 == exitcond3_fu_1109_p2))) begin
        i0_reg_299 <= i0_1_reg_1656;
    end else if (((1'b1 == ap_CS_fsm_state3) & ~(tmp_read_fu_178_p2 == 1'b0))) begin
        i0_reg_299 <= ap_const_lv4_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        i1_1_reg_596 <= i1_3_reg_1821;
    end else if (((1'b1 == ap_CS_fsm_state5) & ~(exitcond2_fu_766_p2 == 1'b0))) begin
        i1_1_reg_596 <= ap_const_lv4_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        i1_reg_391 <= i1_2_reg_1664;
    end else if (((ap_CS_fsm_state4 == 1'b1) & (1'b0 == exitcond1_fu_747_p2))) begin
        i1_reg_391 <= ap_const_lv4_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        i2_2_reg_702 <= i2_3_reg_1835;
    end else if (((1'b1 == ap_CS_fsm_state14) & (1'b0 == exitcond3_fu_1109_p2))) begin
        i2_2_reg_702 <= ap_const_lv4_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        i2_reg_497 <= i2_1_reg_1683;
    end else if (((1'b1 == ap_CS_fsm_state5) & (exitcond2_fu_766_p2 == 1'b0))) begin
        i2_reg_497 <= ap_const_lv4_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        s_0_2_reg_381 <= s_0_reg_1709;
    end else if (((ap_CS_fsm_state4 == 1'b1) & (1'b0 == exitcond1_fu_747_p2))) begin
        s_0_2_reg_381 <= s_0_1_fu_142;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        s_0_5_17_reg_585 <= s_0_2_21_reg_1861;
    end else if (((1'b1 == ap_CS_fsm_state5) & ~(exitcond2_fu_766_p2 == 1'b0))) begin
        s_0_5_17_reg_585 <= s_0_2_reg_381;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        s_1_2_reg_371 <= s_7_27_reg_474;
    end else if (((ap_CS_fsm_state4 == 1'b1) & (1'b0 == exitcond1_fu_747_p2))) begin
        s_1_2_reg_371 <= s_7_19_fu_146;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        s_1_5_reg_574 <= s_7_14_reg_679;
    end else if (((1'b1 == ap_CS_fsm_state5) & ~(exitcond2_fu_766_p2 == 1'b0))) begin
        s_1_5_reg_574 <= s_1_2_reg_371;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        s_2_2_reg_361 <= s_7_8_reg_462;
    end else if (((ap_CS_fsm_state4 == 1'b1) & (1'b0 == exitcond1_fu_747_p2))) begin
        s_2_2_reg_361 <= s_7_20_fu_150;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        s_2_5_reg_563 <= s_7_13_reg_667;
    end else if (((1'b1 == ap_CS_fsm_state5) & ~(exitcond2_fu_766_p2 == 1'b0))) begin
        s_2_5_reg_563 <= s_2_2_reg_361;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        s_3_2_reg_351 <= s_7_6_reg_450;
    end else if (((ap_CS_fsm_state4 == 1'b1) & (1'b0 == exitcond1_fu_747_p2))) begin
        s_3_2_reg_351 <= s_7_21_fu_154;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        s_3_5_reg_552 <= s_7_12_reg_655;
    end else if (((1'b1 == ap_CS_fsm_state5) & ~(exitcond2_fu_766_p2 == 1'b0))) begin
        s_3_5_reg_552 <= s_3_2_reg_351;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        s_4_2_reg_341 <= s_7_4_reg_438;
    end else if (((ap_CS_fsm_state4 == 1'b1) & (1'b0 == exitcond1_fu_747_p2))) begin
        s_4_2_reg_341 <= s_7_22_fu_158;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        s_4_5_reg_541 <= s_7_11_reg_643;
    end else if (((1'b1 == ap_CS_fsm_state5) & ~(exitcond2_fu_766_p2 == 1'b0))) begin
        s_4_5_reg_541 <= s_4_2_reg_341;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        s_5_2_reg_331 <= s_7_2_12_reg_426;
    end else if (((ap_CS_fsm_state4 == 1'b1) & (1'b0 == exitcond1_fu_747_p2))) begin
        s_5_2_reg_331 <= s_7_23_fu_162;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        s_5_5_reg_530 <= s_7_32_reg_631;
    end else if (((1'b1 == ap_CS_fsm_state5) & ~(exitcond2_fu_766_p2 == 1'b0))) begin
        s_5_5_reg_530 <= s_5_2_reg_331;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        s_6_2_reg_321 <= s_6_3_reg_414;
    end else if (((ap_CS_fsm_state4 == 1'b1) & (1'b0 == exitcond1_fu_747_p2))) begin
        s_6_2_reg_321 <= s_7_24_fu_166;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        s_6_3_reg_414 <= s_7_1_fu_1048_p3;
    end else if (((1'b1 == ap_CS_fsm_state5) & (exitcond2_fu_766_p2 == 1'b0))) begin
        s_6_3_reg_414 <= s_6_2_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        s_6_5_reg_519 <= s_6_6_reg_619;
    end else if (((1'b1 == ap_CS_fsm_state5) & ~(exitcond2_fu_766_p2 == 1'b0))) begin
        s_6_5_reg_519 <= s_6_2_reg_321;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        s_6_6_reg_619 <= s_7_17_fu_1443_p3;
    end else if (((1'b1 == ap_CS_fsm_state14) & (1'b0 == exitcond3_fu_1109_p2))) begin
        s_6_6_reg_619 <= s_6_5_reg_519;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        s_7_10_reg_486 <= s_7_30_reg_1788;
    end else if (((1'b1 == ap_CS_fsm_state5) & (exitcond2_fu_766_p2 == 1'b0))) begin
        s_7_10_reg_486 <= s_0_2_reg_381;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        s_7_11_reg_643 <= s_7_34_reg_1942;
    end else if (((1'b1 == ap_CS_fsm_state14) & (1'b0 == exitcond3_fu_1109_p2))) begin
        s_7_11_reg_643 <= s_4_5_reg_541;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        s_7_12_reg_655 <= s_7_35_fu_1484_p3;
    end else if (((1'b1 == ap_CS_fsm_state14) & (1'b0 == exitcond3_fu_1109_p2))) begin
        s_7_12_reg_655 <= s_3_5_reg_552;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        s_7_13_reg_667 <= s_7_36_reg_1947;
    end else if (((1'b1 == ap_CS_fsm_state14) & (1'b0 == exitcond3_fu_1109_p2))) begin
        s_7_13_reg_667 <= s_2_5_reg_563;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        s_7_14_reg_679 <= s_7_38_reg_1952;
    end else if (((1'b1 == ap_CS_fsm_state14) & (1'b0 == exitcond3_fu_1109_p2))) begin
        s_7_14_reg_679 <= s_1_5_reg_574;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        s_7_15_reg_691 <= s_7_39_reg_1957;
    end else if (((1'b1 == ap_CS_fsm_state14) & (1'b0 == exitcond3_fu_1109_p2))) begin
        s_7_15_reg_691 <= s_0_5_17_reg_585;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        s_7_27_reg_474 <= s_7_29_reg_1783;
    end else if (((1'b1 == ap_CS_fsm_state5) & (exitcond2_fu_766_p2 == 1'b0))) begin
        s_7_27_reg_474 <= s_1_2_reg_371;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        s_7_2_12_reg_426 <= s_7_3_14_fu_1069_p3;
    end else if (((1'b1 == ap_CS_fsm_state5) & (exitcond2_fu_766_p2 == 1'b0))) begin
        s_7_2_12_reg_426 <= s_5_2_reg_331;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        s_7_2_reg_311 <= s_7_3_reg_402;
    end else if (((ap_CS_fsm_state4 == 1'b1) & (1'b0 == exitcond1_fu_747_p2))) begin
        s_7_2_reg_311 <= s_7_25_fu_170;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        s_7_32_reg_631 <= s_7_33_fu_1464_p3;
    end else if (((1'b1 == ap_CS_fsm_state14) & (1'b0 == exitcond3_fu_1109_p2))) begin
        s_7_32_reg_631 <= s_5_5_reg_530;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        s_7_3_reg_402 <= s_7_fu_1027_p3;
    end else if (((1'b1 == ap_CS_fsm_state5) & (exitcond2_fu_766_p2 == 1'b0))) begin
        s_7_3_reg_402 <= s_7_2_reg_311;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        s_7_4_reg_438 <= s_7_5_reg_1773;
    end else if (((1'b1 == ap_CS_fsm_state5) & (exitcond2_fu_766_p2 == 1'b0))) begin
        s_7_4_reg_438 <= s_4_2_reg_341;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        s_7_5_16_reg_508 <= s_7_6_19_reg_607;
    end else if (((1'b1 == ap_CS_fsm_state5) & ~(exitcond2_fu_766_p2 == 1'b0))) begin
        s_7_5_16_reg_508 <= s_7_2_reg_311;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        s_7_6_19_reg_607 <= s_7_16_fu_1422_p3;
    end else if (((1'b1 == ap_CS_fsm_state14) & (1'b0 == exitcond3_fu_1109_p2))) begin
        s_7_6_19_reg_607 <= s_7_5_16_reg_508;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        s_7_6_reg_450 <= s_7_7_fu_1089_p3;
    end else if (((1'b1 == ap_CS_fsm_state5) & (exitcond2_fu_766_p2 == 1'b0))) begin
        s_7_6_reg_450 <= s_3_2_reg_351;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        s_7_8_reg_462 <= s_7_9_reg_1778;
    end else if (((1'b1 == ap_CS_fsm_state5) & (exitcond2_fu_766_p2 == 1'b0))) begin
        s_7_8_reg_462 <= s_2_2_reg_361;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        a_load_reg_1884 <= a_q0;
        b_load_reg_1889 <= b_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        b_a_load_reg_1715 <= b_a_q0;
        sc_FIFO_DCT_mA_load_reg_1720 <= sc_FIFO_DCT_mA_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_CS_fsm_state4 == 1'b1)) begin
        i0_1_reg_1656 <= i0_1_fu_753_p2;
        i0_cast_reg_1645[3 : 0] <= i0_cast_fu_743_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        i1_1_cast_reg_1813[3 : 0] <= i1_1_cast_fu_1105_p1[3 : 0];
        i1_3_reg_1821 <= i1_3_fu_1115_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i1_2_reg_1664 <= i1_2_fu_772_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        i2_1_reg_1683 <= i2_1_fu_812_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        i2_3_reg_1835 <= i2_3_fu_1183_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        or_cond3_reg_1765 <= or_cond3_fu_947_p2;
        or_cond_reg_1760 <= or_cond_fu_935_p2;
        s_0_5_reg_1730 <= grp_fu_895_p2;
        s_7_29_reg_1783 <= s_7_29_fu_993_p3;
        s_7_30_reg_1788 <= s_7_30_fu_1001_p3;
        s_7_5_reg_1773 <= s_7_5_fu_961_p3;
        s_7_9_reg_1778 <= s_7_9_fu_977_p3;
        sel_tmp2_reg_1744 <= sel_tmp2_fu_905_p2;
        sel_tmp4_reg_1749 <= sel_tmp4_fu_910_p2;
        sel_tmp8_reg_1755 <= sel_tmp8_fu_920_p2;
        sel_tmp_reg_1738 <= sel_tmp_fu_900_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        or_cond4_reg_1929 <= or_cond4_fu_1330_p2;
        or_cond7_reg_1934 <= or_cond7_fu_1342_p2;
        s_0_6_reg_1899 <= grp_fu_1290_p2;
        s_7_34_reg_1942 <= s_7_34_fu_1356_p3;
        s_7_36_reg_1947 <= s_7_36_fu_1372_p3;
        s_7_38_reg_1952 <= s_7_38_fu_1388_p3;
        s_7_39_reg_1957 <= s_7_39_fu_1396_p3;
        sel_tmp11_reg_1924 <= sel_tmp11_fu_1315_p2;
        sel_tmp5_reg_1918 <= sel_tmp5_fu_1305_p2;
        sel_tmp7_reg_1907 <= sel_tmp7_fu_1295_p2;
        sel_tmp9_reg_1913 <= sel_tmp9_fu_1300_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & ~(1'b0 == exitcond3_fu_1109_p2))) begin
        s_0_1_fu_142 <= s_0_5_17_reg_585;
        s_7_19_fu_146 <= s_1_5_reg_574;
        s_7_20_fu_150 <= s_2_5_reg_563;
        s_7_21_fu_154 <= s_3_5_reg_552;
        s_7_22_fu_158 <= s_4_5_reg_541;
        s_7_23_fu_162 <= s_5_5_reg_530;
        s_7_24_fu_166 <= s_6_5_reg_519;
        s_7_25_fu_170 <= s_7_5_16_reg_508;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) & ~(1'b0 == exitcond5_fu_1177_p2))) begin
        s_0_2_21_reg_1861 <= s_0_2_21_fu_1257_p2;
        tmp_16_reg_1879 <= tmp_16_fu_1283_p2;
        tmp_24_reg_1874 <= {{p_neg_fu_1267_p2[ap_const_lv32_1F : ap_const_lv32_13]}};
        tmp_8_reg_1869 <= tmp_8_fu_1263_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & ~(1'b0 == exitcond4_fu_806_p2))) begin
        s_0_reg_1709 <= s_0_fu_886_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & ~(exitcond2_fu_766_p2 == 1'b0))) begin
        tmp_1_reg_1675[5 : 3] <= tmp_1_fu_794_p3[5 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == exitcond4_fu_806_p2))) begin
        tmp_23_reg_1688 <= tmp_23_fu_818_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (exitcond2_fu_766_p2 == 1'b0))) begin
        tmp_2_reg_1669[5 : 3] <= tmp_2_fu_782_p3[5 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state15) & (1'b0 == exitcond5_fu_1177_p2))) begin
        tmp_30_reg_1840 <= tmp_30_fu_1189_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & (1'b0 == exitcond3_fu_1109_p2))) begin
        tmp_4_reg_1826[5 : 3] <= tmp_4_fu_1125_p3[5 : 3];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        a_address0 = tmp_10_cast_fu_1206_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        a_address0 = tmp_3_cast_fu_1100_p1;
    end else begin
        a_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state13))) begin
        a_ce0 = 1'b1;
    end else begin
        a_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        a_we0 = 1'b1;
    end else begin
        a_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        b_a_ce0 = 1'b1;
    end else begin
        b_a_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        b_ce0 = 1'b1;
    end else begin
        b_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) & ~(tmp_14_read_fu_214_p2 == 1'b0))) begin
        s_DCT = 1'b0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        s_DCT = 1'b1;
    end else begin
        s_DCT = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state23) | ((1'b1 == ap_CS_fsm_state24) & ~(tmp_14_read_fu_214_p2 == 1'b0)))) begin
        s_DCT_ap_vld = 1'b1;
    end else begin
        s_DCT_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        s_working = 1'b0;
    end else if (((1'b1 == ap_CS_fsm_state3) & ~(tmp_read_fu_178_p2 == 1'b0))) begin
        s_working = 1'b1;
    end else begin
        s_working = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state3) & ~(tmp_read_fu_178_p2 == 1'b0)) | (1'b1 == ap_CS_fsm_state23))) begin
        s_working_ap_vld = 1'b1;
    end else begin
        s_working_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_CS_fsm_state4 == 1'b1) & ~(1'b0 == exitcond1_fu_747_p2))) begin
        sc_FIFO_DCT_exec_cnt_o_ap_vld = 1'b1;
    end else begin
        sc_FIFO_DCT_exec_cnt_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        sc_FIFO_DCT_mA_ce0 = 1'b1;
    end else begin
        sc_FIFO_DCT_mA_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        sc_FIFO_DCT_mB_ce0 = 1'b1;
    end else begin
        sc_FIFO_DCT_mB_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        sc_FIFO_DCT_mB_we0 = 1'b1;
    end else begin
        sc_FIFO_DCT_mB_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        sc_FIFO_DCT_mC_ce0 = 1'b1;
    end else begin
        sc_FIFO_DCT_mC_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        sc_FIFO_DCT_mC_we0 = 1'b1;
    end else begin
        sc_FIFO_DCT_mC_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (~(tmp_read_fu_178_p2 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((1'b0 == exitcond1_fu_747_p2)) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state5 : begin
            if (~(exitcond2_fu_766_p2 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (~(1'b0 == exitcond4_fu_806_p2)) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state14 : begin
            if (~(1'b0 == exitcond3_fu_1109_p2)) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            if (~(1'b0 == exitcond5_fu_1177_p2)) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            if (~(tmp_14_read_fu_214_p2 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state11 = ap_CS_fsm[ap_const_lv32_A];

assign ap_CS_fsm_state12 = ap_CS_fsm[ap_const_lv32_B];

assign ap_CS_fsm_state13 = ap_CS_fsm[ap_const_lv32_C];

assign ap_CS_fsm_state14 = ap_CS_fsm[ap_const_lv32_D];

assign ap_CS_fsm_state15 = ap_CS_fsm[ap_const_lv32_E];

assign ap_CS_fsm_state16 = ap_CS_fsm[ap_const_lv32_F];

assign ap_CS_fsm_state17 = ap_CS_fsm[ap_const_lv32_10];

assign ap_CS_fsm_state20 = ap_CS_fsm[ap_const_lv32_13];

assign ap_CS_fsm_state21 = ap_CS_fsm[ap_const_lv32_14];

assign ap_CS_fsm_state22 = ap_CS_fsm[ap_const_lv32_15];

assign ap_CS_fsm_state23 = ap_CS_fsm[ap_const_lv32_16];

assign ap_CS_fsm_state24 = ap_CS_fsm[ap_const_lv32_17];

assign ap_CS_fsm_state3 = ap_CS_fsm[ap_const_lv32_2];

assign ap_CS_fsm_state4 = ap_CS_fsm[ap_const_lv32_3];

assign ap_CS_fsm_state5 = ap_CS_fsm[ap_const_lv32_4];

assign ap_CS_fsm_state6 = ap_CS_fsm[ap_const_lv32_5];

assign ap_CS_fsm_state7 = ap_CS_fsm[ap_const_lv32_6];

assign ap_CS_fsm_state8 = ap_CS_fsm[ap_const_lv32_7];

assign b_a_address0 = tmp_6_cast_fu_835_p1;

assign b_address0 = tmp_11_cast_fu_1216_p1;

assign exitcond1_fu_747_p2 = ((i0_reg_299 == ap_const_lv4_8) ? 1'b1 : 1'b0);

assign exitcond2_fu_766_p2 = ((i1_reg_391 == ap_const_lv4_8) ? 1'b1 : 1'b0);

assign exitcond3_fu_1109_p2 = ((i1_1_reg_596 == ap_const_lv4_8) ? 1'b1 : 1'b0);

assign exitcond4_fu_806_p2 = ((i2_reg_497 == ap_const_lv4_8) ? 1'b1 : 1'b0);

assign exitcond5_fu_1177_p2 = ((i2_2_reg_702 == ap_const_lv4_8) ? 1'b1 : 1'b0);

assign i0_1_fu_753_p2 = (i0_reg_299 + ap_const_lv4_1);

assign i0_cast_fu_743_p1 = i0_reg_299;

assign i1_1_cast_fu_1105_p1 = i1_1_reg_596;

assign i1_2_fu_772_p2 = (i1_reg_391 + ap_const_lv4_1);

assign i1_3_fu_1115_p2 = (i1_1_reg_596 + ap_const_lv4_1);

assign i2_1_fu_812_p2 = (i2_reg_497 + ap_const_lv4_1);

assign i2_2_cast_fu_1173_p1 = i2_2_reg_702;

assign i2_3_fu_1183_p2 = (i2_2_reg_702 + ap_const_lv4_1);

assign i2_cast_fu_802_p1 = i2_reg_497;

assign newSel10_fu_1408_p3 = ((sel_tmp7_reg_1907[0:0] === 1'b1) ? s_7_6_19_reg_607 : s_0_6_reg_1899);

assign newSel11_fu_1414_p3 = ((or_cond6_fu_1404_p2[0:0] === 1'b1) ? s_7_6_19_reg_607 : newSel10_fu_1408_p3);

assign newSel12_fu_1429_p3 = ((sel_tmp7_reg_1907[0:0] === 1'b1) ? s_0_6_reg_1899 : s_6_6_reg_619);

assign newSel13_fu_1435_p3 = ((or_cond6_fu_1404_p2[0:0] === 1'b1) ? s_6_6_reg_619 : newSel12_fu_1429_p3);

assign newSel14_fu_1450_p3 = ((sel_tmp5_reg_1918[0:0] === 1'b1) ? s_7_32_reg_631 : s_0_6_reg_1899);

assign newSel15_fu_1456_p3 = ((or_cond6_fu_1404_p2[0:0] === 1'b1) ? newSel14_fu_1450_p3 : s_7_32_reg_631);

assign newSel16_fu_1348_p3 = ((sel_tmp5_fu_1305_p2[0:0] === 1'b1) ? grp_fu_1290_p2 : s_7_11_reg_643);

assign newSel17_fu_1471_p3 = ((sel_tmp11_reg_1924[0:0] === 1'b1) ? s_7_12_reg_655 : s_0_6_reg_1899);

assign newSel18_fu_1477_p3 = ((or_cond4_reg_1929[0:0] === 1'b1) ? s_7_12_reg_655 : newSel17_fu_1471_p3);

assign newSel19_fu_1364_p3 = ((sel_tmp11_fu_1315_p2[0:0] === 1'b1) ? grp_fu_1290_p2 : s_7_13_reg_667);

assign newSel1_fu_1019_p3 = ((or_cond2_fu_1009_p2[0:0] === 1'b1) ? s_7_3_reg_402 : newSel_fu_1013_p3);

assign newSel2_fu_1076_p3 = ((sel_tmp8_reg_1755[0:0] === 1'b1) ? s_7_6_reg_450 : s_0_5_reg_1730);

assign newSel3_fu_1034_p3 = ((sel_tmp_reg_1738[0:0] === 1'b1) ? s_0_5_reg_1730 : s_6_3_reg_414);

assign newSel4_fu_1040_p3 = ((or_cond2_fu_1009_p2[0:0] === 1'b1) ? s_6_3_reg_414 : newSel3_fu_1034_p3);

assign newSel5_fu_1082_p3 = ((or_cond_reg_1760[0:0] === 1'b1) ? s_7_6_reg_450 : newSel2_fu_1076_p3);

assign newSel6_fu_1055_p3 = ((sel_tmp4_reg_1749[0:0] === 1'b1) ? s_7_2_12_reg_426 : s_0_5_reg_1730);

assign newSel7_fu_1061_p3 = ((or_cond2_fu_1009_p2[0:0] === 1'b1) ? newSel6_fu_1055_p3 : s_7_2_12_reg_426);

assign newSel8_fu_969_p3 = ((sel_tmp8_fu_920_p2[0:0] === 1'b1) ? grp_fu_895_p2 : s_7_8_reg_462);

assign newSel9_fu_953_p3 = ((sel_tmp4_fu_910_p2[0:0] === 1'b1) ? grp_fu_895_p2 : s_7_4_reg_438);

assign newSel_fu_1013_p3 = ((sel_tmp_reg_1738[0:0] === 1'b1) ? s_7_3_reg_402 : s_0_5_reg_1730);

assign or_cond1_fu_941_p2 = (sel_tmp8_fu_920_p2 | sel_tmp6_fu_915_p2);

assign or_cond2_fu_1009_p2 = (sel_tmp4_reg_1749 | sel_tmp2_reg_1744);

assign or_cond3_fu_947_p2 = (or_cond_fu_935_p2 | or_cond1_fu_941_p2);

assign or_cond4_fu_1330_p2 = (sel_tmp13_fu_1325_p2 | sel_tmp12_fu_1320_p2);

assign or_cond5_fu_1336_p2 = (sel_tmp11_fu_1315_p2 | sel_tmp10_fu_1310_p2);

assign or_cond6_fu_1404_p2 = (sel_tmp5_reg_1918 | sel_tmp9_reg_1913);

assign or_cond7_fu_1342_p2 = (or_cond4_fu_1330_p2 | or_cond5_fu_1336_p2);

assign or_cond_fu_935_p2 = (sel_tmp3_fu_930_p2 | sel_tmp1_fu_925_p2);

assign p_lshr_cast_fu_1502_p1 = tmp_24_reg_1874;

assign p_lshr_f_cast_fu_1520_p1 = tmp_25_fu_1511_p4;

assign p_neg_fu_1267_p2 = (ap_const_lv32_0 - s_0_2_21_fu_1257_p2);

assign p_neg_t_fu_1505_p2 = (ap_const_lv14_0 - p_lshr_cast_fu_1502_p1);

assign s_0_2_21_fu_1257_p2 = (tmp26_fu_1251_p2 + tmp23_fu_1233_p2);

assign s_0_fu_886_p2 = (tmp20_fu_880_p2 + tmp17_fu_862_p2);

assign s_7_16_fu_1422_p3 = ((or_cond7_reg_1934[0:0] === 1'b1) ? s_7_6_19_reg_607 : newSel11_fu_1414_p3);

assign s_7_17_fu_1443_p3 = ((or_cond7_reg_1934[0:0] === 1'b1) ? s_6_6_reg_619 : newSel13_fu_1435_p3);

assign s_7_1_fu_1048_p3 = ((or_cond3_reg_1765[0:0] === 1'b1) ? s_6_3_reg_414 : newSel4_fu_1040_p3);

assign s_7_28_fu_985_p3 = ((sel_tmp1_fu_925_p2[0:0] === 1'b1) ? grp_fu_895_p2 : s_7_27_reg_474);

assign s_7_29_fu_993_p3 = ((sel_tmp3_fu_930_p2[0:0] === 1'b1) ? s_7_27_reg_474 : s_7_28_fu_985_p3);

assign s_7_30_fu_1001_p3 = ((sel_tmp3_fu_930_p2[0:0] === 1'b1) ? grp_fu_895_p2 : s_7_10_reg_486);

assign s_7_33_fu_1464_p3 = ((or_cond7_reg_1934[0:0] === 1'b1) ? s_7_32_reg_631 : newSel15_fu_1456_p3);

assign s_7_34_fu_1356_p3 = ((or_cond7_fu_1342_p2[0:0] === 1'b1) ? s_7_11_reg_643 : newSel16_fu_1348_p3);

assign s_7_35_fu_1484_p3 = ((or_cond7_reg_1934[0:0] === 1'b1) ? newSel18_fu_1477_p3 : s_7_12_reg_655);

assign s_7_36_fu_1372_p3 = ((or_cond4_fu_1330_p2[0:0] === 1'b1) ? s_7_13_reg_667 : newSel19_fu_1364_p3);

assign s_7_37_fu_1380_p3 = ((sel_tmp12_fu_1320_p2[0:0] === 1'b1) ? grp_fu_1290_p2 : s_7_14_reg_679);

assign s_7_38_fu_1388_p3 = ((sel_tmp13_fu_1325_p2[0:0] === 1'b1) ? s_7_14_reg_679 : s_7_37_fu_1380_p3);

assign s_7_39_fu_1396_p3 = ((sel_tmp13_fu_1325_p2[0:0] === 1'b1) ? grp_fu_1290_p2 : s_7_15_reg_691);

assign s_7_3_14_fu_1069_p3 = ((or_cond3_reg_1765[0:0] === 1'b1) ? s_7_2_12_reg_426 : newSel7_fu_1061_p3);

assign s_7_5_fu_961_p3 = ((or_cond3_fu_947_p2[0:0] === 1'b1) ? s_7_4_reg_438 : newSel9_fu_953_p3);

assign s_7_7_fu_1089_p3 = ((or_cond3_reg_1765[0:0] === 1'b1) ? newSel5_fu_1082_p3 : s_7_6_reg_450);

assign s_7_9_fu_977_p3 = ((or_cond_fu_935_p2[0:0] === 1'b1) ? s_7_8_reg_462 : newSel8_fu_969_p3);

assign s_7_fu_1027_p3 = ((or_cond3_reg_1765[0:0] === 1'b1) ? s_7_3_reg_402 : newSel1_fu_1019_p3);

assign sc_FIFO_DCT_exec_cnt_o = (sc_FIFO_DCT_exec_cnt_i + ap_const_lv32_1);

assign sc_FIFO_DCT_mA_address0 = tmp_7_cast_fu_845_p1;

assign sc_FIFO_DCT_mB_address0 = tmp_8_cast_fu_1491_p1;

assign sc_FIFO_DCT_mB_d0 = s_0_2_21_reg_1861;

assign sc_FIFO_DCT_mC_address0 = tmp_16_cast_fu_1547_p1;

assign sc_FIFO_DCT_mC_d0 = $signed(tmp_15_fu_1536_p2);

assign sel_tmp10_fu_1310_p2 = ((tmp_30_reg_1840 == ap_const_lv3_3) ? 1'b1 : 1'b0);

assign sel_tmp11_fu_1315_p2 = ((tmp_30_reg_1840 == ap_const_lv3_2) ? 1'b1 : 1'b0);

assign sel_tmp12_fu_1320_p2 = ((tmp_30_reg_1840 == ap_const_lv3_1) ? 1'b1 : 1'b0);

assign sel_tmp13_fu_1325_p2 = ((tmp_30_reg_1840 == ap_const_lv3_0) ? 1'b1 : 1'b0);

assign sel_tmp1_fu_925_p2 = ((tmp_23_reg_1688 == ap_const_lv3_1) ? 1'b1 : 1'b0);

assign sel_tmp2_fu_905_p2 = ((tmp_23_reg_1688 == ap_const_lv3_5) ? 1'b1 : 1'b0);

assign sel_tmp3_fu_930_p2 = ((tmp_23_reg_1688 == ap_const_lv3_0) ? 1'b1 : 1'b0);

assign sel_tmp4_fu_910_p2 = ((tmp_23_reg_1688 == ap_const_lv3_4) ? 1'b1 : 1'b0);

assign sel_tmp5_fu_1305_p2 = ((tmp_30_reg_1840 == ap_const_lv3_4) ? 1'b1 : 1'b0);

assign sel_tmp6_fu_915_p2 = ((tmp_23_reg_1688 == ap_const_lv3_3) ? 1'b1 : 1'b0);

assign sel_tmp7_fu_1295_p2 = ((tmp_30_reg_1840 == ap_const_lv3_6) ? 1'b1 : 1'b0);

assign sel_tmp8_fu_920_p2 = ((tmp_23_reg_1688 == ap_const_lv3_2) ? 1'b1 : 1'b0);

assign sel_tmp9_fu_1300_p2 = ((tmp_30_reg_1840 == ap_const_lv3_5) ? 1'b1 : 1'b0);

assign sel_tmp_fu_900_p2 = ((tmp_23_reg_1688 == ap_const_lv3_6) ? 1'b1 : 1'b0);

assign tmp15_fu_850_p2 = (s_7_2_12_reg_426 + s_6_3_reg_414);

assign tmp16_fu_856_p2 = (s_7_4_reg_438 + s_7_6_reg_450);

assign tmp17_fu_862_p2 = (tmp16_fu_856_p2 + tmp15_fu_850_p2);

assign tmp18_fu_868_p2 = (s_7_10_reg_486 + s_7_8_reg_462);

assign tmp19_fu_874_p2 = (s_7_27_reg_474 + s_7_3_reg_402);

assign tmp20_fu_880_p2 = (tmp19_fu_874_p2 + tmp18_fu_868_p2);

assign tmp21_fu_1221_p2 = (s_7_32_reg_631 + s_6_6_reg_619);

assign tmp22_fu_1227_p2 = (s_7_11_reg_643 + s_7_12_reg_655);

assign tmp23_fu_1233_p2 = (tmp22_fu_1227_p2 + tmp21_fu_1221_p2);

assign tmp24_fu_1239_p2 = (s_7_15_reg_691 + s_7_13_reg_667);

assign tmp25_fu_1245_p2 = (s_7_14_reg_679 + s_7_6_19_reg_607);

assign tmp26_fu_1251_p2 = (tmp25_fu_1245_p2 + tmp24_fu_1239_p2);

assign tmp_10_cast_fu_1206_p1 = tmp_10_fu_1201_p2;

assign tmp_10_fu_1201_p2 = (i0_cast_reg_1645 + tmp_9_fu_1193_p3);

assign tmp_11_cast_fu_1216_p1 = tmp_11_fu_1211_p2;

assign tmp_11_fu_1211_p2 = (tmp_4_reg_1826 + i2_2_cast_fu_1173_p1);

assign tmp_13_cast_fu_1532_p1 = $signed(tmp_13_fu_1524_p3);

assign tmp_13_fu_1524_p3 = ((tmp_29_fu_1495_p3[0:0] === 1'b1) ? p_neg_t_fu_1505_p2 : p_lshr_f_cast_fu_1520_p1);

assign tmp_14_read_fu_214_p2 = s_done;

assign tmp_15_fu_1536_p2 = ($signed(tmp_13_cast_fu_1532_p1) + $signed(ap_const_lv15_7F));

assign tmp_16_cast_fu_1547_p1 = tmp_16_reg_1879;

assign tmp_16_fu_1283_p2 = (tmp_1_reg_1675 + i1_1_cast_reg_1813);

assign tmp_1_fu_794_p3 = {{tmp_20_fu_790_p1}, {ap_const_lv3_0}};

assign tmp_20_fu_790_p1 = i0_reg_299[2:0];

assign tmp_21_fu_778_p1 = i1_reg_391[2:0];

assign tmp_22_fu_1121_p1 = i1_1_reg_596[2:0];

assign tmp_23_fu_818_p1 = i2_reg_497[2:0];

assign tmp_25_fu_1511_p4 = {{s_0_2_21_reg_1861[ap_const_lv32_1F : ap_const_lv32_13]}};

assign tmp_29_fu_1495_p3 = s_0_2_21_reg_1861[ap_const_lv32_1F];

assign tmp_2_fu_782_p3 = {{tmp_21_fu_778_p1}, {ap_const_lv3_0}};

assign tmp_30_fu_1189_p1 = i2_2_reg_702[2:0];

assign tmp_3_cast_fu_1100_p1 = tmp_3_fu_1096_p2;

assign tmp_3_fu_1096_p2 = (tmp_2_reg_1669 + i0_cast_reg_1645);

assign tmp_4_fu_1125_p3 = {{tmp_22_fu_1121_p1}, {ap_const_lv3_0}};

assign tmp_5_fu_822_p3 = {{tmp_23_fu_818_p1}, {ap_const_lv3_0}};

assign tmp_6_cast_fu_835_p1 = tmp_6_fu_830_p2;

assign tmp_6_fu_830_p2 = (i0_cast_reg_1645 + tmp_5_fu_822_p3);

assign tmp_7_cast_fu_845_p1 = tmp_7_fu_840_p2;

assign tmp_7_fu_840_p2 = (tmp_2_reg_1669 + i2_cast_fu_802_p1);

assign tmp_8_cast_fu_1491_p1 = tmp_8_reg_1869;

assign tmp_8_fu_1263_p2 = (i0_cast_reg_1645 + tmp_4_reg_1826);

assign tmp_9_fu_1193_p3 = {{tmp_30_fu_1189_p1}, {ap_const_lv3_0}};

assign tmp_read_fu_178_p2 = s_buffered;

always @ (posedge ap_clk) begin
    i0_cast_reg_1645[5:4] <= 2'b00;
    tmp_2_reg_1669[2:0] <= 3'b000;
    tmp_1_reg_1675[2:0] <= 3'b000;
    i1_1_cast_reg_1813[5:4] <= 2'b00;
    tmp_4_reg_1826[2:0] <= 3'b000;
end

endmodule //sc_FIFO_DCT_DCT
