-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.3
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity sc_FIFO_DCT_Prc2_b_rom is 
    generic(
             dwidth     : integer := 8; 
             awidth     : integer := 6; 
             mem_size    : integer := 64
    ); 
    port (
          addr0      : in std_logic_vector(awidth-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(dwidth-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of sc_FIFO_DCT_Prc2_b_rom is 

signal addr0_tmp : std_logic_vector(awidth-1 downto 0); 
type mem_array is array (0 to mem_size-1) of std_logic_vector (dwidth-1 downto 0); 
signal mem : mem_array := (
    0 to 7=> "01011010", 8 => "01111101", 9 => "01101010", 10 => "01000111", 
    11 => "00011000", 12 => "11101000", 13 => "10111001", 14 => "10010110", 
    15 => "10000011", 16 => "01110110", 17 => "00110000", 18 => "11010000", 
    19 to 20=> "10001010", 21 => "11010000", 22 => "00110000", 23 => "01110110", 
    24 => "01101010", 25 => "11101000", 26 => "10000011", 27 => "10111001", 
    28 => "01000111", 29 => "01111101", 30 => "00011000", 31 => "10010110", 
    32 => "01011010", 33 to 34=> "10100110", 35 to 36=> "01011010", 37 to 38=> "10100110", 
    39 => "01011010", 40 => "01000111", 41 => "10000011", 42 => "00011000", 
    43 => "01101010", 44 => "10010110", 45 => "11101000", 46 => "01111101", 
    47 => "10111001", 48 => "00110000", 49 => "10001010", 50 => "01110110", 
    51 to 52=> "11010000", 53 => "01110110", 54 => "10001010", 55 => "00110000", 
    56 => "00011000", 57 => "10111001", 58 => "01101010", 59 => "10000011", 
    60 => "01111101", 61 => "10010110", 62 => "01000111", 63 => "11101000" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "select_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "distributed";

attribute EQUIVALENT_REGISTER_REMOVAL : string;
begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity sc_FIFO_DCT_Prc2_b is
    generic (
        DataWidth : INTEGER := 8;
        AddressRange : INTEGER := 64;
        AddressWidth : INTEGER := 6);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of sc_FIFO_DCT_Prc2_b is
    component sc_FIFO_DCT_Prc2_b_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    sc_FIFO_DCT_Prc2_b_rom_U :  component sc_FIFO_DCT_Prc2_b_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


